Implement cosign on docker image
element-hq/synapse pull request #16774
Opened 2024-01-03 09:33 UTC by gaelgatelement

2024-01-03 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=16774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=16774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=16774) it.</sub>

2024-01-03 10:28 UTC, erikjohnston commented
I've temporarily added a commit to enable running the docker workflow to test it. That commit should be reverted and the uploaded test image to ghcr deleted before merging.

2024-01-03 11:11 UTC, erikjohnston requested changes
Looks like the signing failed

2024-01-03 13:33 UTC, gaelgatelement commented
It seems to work now!

```
cosign verify ghcr.io/element-hq/synapse:test-cosign \
  --certificate-github-workflow-repository  element-hq/synapse \
  --certificate-oidc-issuer https://token.actions.githubusercontent.com \
  --certificate-github-workflow-name "Build docker images" \
  --certificate-github-workflow-ref refs/pull/16774/merge \
 --certificate-identity https://github.com/element-hq/synapse/.github/workflows/docker.yml@refs/pull/16774/merge 

Verification for ghcr.io/element-hq/synapse:test-cosign --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The code-signing certificate was verified using trusted certificate authority certificates

[{"critical":{"identity":{"docker-reference":"ghcr.io/element-hq/synapse"},"image":{"docker-manifest-digest":"sha256:2e6f5f4c30174fd3a12ef8a84aaf7afb48ba0918f61ce9f109cde8e515ee804c"},"type":"cosign container image signature"},"optional":{"1.3.6.1.4.1.57264.1.1":"https://token.actions.githubusercontent.com","1.3.6.1.4.1.57264.1.2":"pull_request","1.3.6.1.4.1.57264.1.3":"8c6c9cc49563e629de03124cbb821db1e655ac12","1.3.6.1.4.1.57264.1.4":"Build docker images","1.3.6.1.4.1.57264.1.5":"element-hq/synapse","1.3.6.1.4.1.57264.1.6":"refs/pull/16774/merge","Bundle":{"SignedEntryTimestamp":"MEUCIQDAGfh2AuBo+tVMMoPuEpqcs0Y54jYSloTQtgUch8WTxAIgU2vHTVqKY36sNuBuGO7F6L44QMCrj3899JVSeiuTIbM=","Payload":{"body":"eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI5OTYxYjdjMzA0OTMxZDU2Yzc5YmM4YTQzYTYyZmIzYTVkMmNkM2RiYzUxNzg1Yjk1ZTZiN2FhYjUzMDAxYjY3In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FVUNJSGdJQ25UTWRNZC9oQzMyNWdGZ1Y0VThyOG9DVGY0TUdOdGROWG1XTmJtbEFpRUF4eTAwS0xUci9nUU9VT0dxR3ZGK1lhTkZrNDduR0dCYVp3RHpycjRhMTRZPSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVYzBla05EUW0xcFowRjNTVUpCWjBsVlFucENTbWRUZUdkemVtVm5MMkl6UWtnNGFITmthekpaVW1oM2QwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcFJkMDFVUVhwTlZFbDZUVVJWTlZkb1kwNU5hbEYzVFZSQmVrMVVTVEJOUkZVMVYycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVV6VEhobU5FbG1kMUJtYldOSFdVWjJObFowTUdVeVJWZFRla0k1Wm1vd1ZrMUpVbTBLYlRSUVMyTkpNMU4xVnpsNlR6WjZaRFpITld3MGJscEVTRlpUY21kWVlYVk5ObEI2V1hoMlNFMVdaRzlNWmxSTFJFdFBRMEpaWTNkbloxZEVUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlZTTjNGTUNtcGxRV3RHUVZGNmJTODVlbGQ1WjBOemJHMXBkbUp2ZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDFwbldVUldVakJTUVZGSUwwSkdkM2RYYjFwWllVaFNNR05JVFRaTWVUbHVZVmhTYjJSWFNYVlpNamwwVERKV2MxcFhNV3hpYmxGMFlVaEZkZ3BqTTJ4MVdWaENlbHBUT0hWYU1td3dZVWhXYVV3elpIWmpiWFJ0WWtjNU0yTjVPV3RpTWs1eVdsaEpkV1ZYTVhOUlNFcHNXbTVOZG1OSVZuTmlRemg0Q2s1cVl6Tk9RemwwV2xoS2JscFVRVFZDWjI5eVFtZEZSVUZaVHk5TlFVVkNRa04wYjJSSVVuZGplbTkyVEROU2RtRXlWblZNYlVacVpFZHNkbUp1VFhVS1dqSnNNR0ZJVm1sa1dFNXNZMjFPZG1KdVVteGlibEYxV1RJNWRFMUNiMGREYVhOSFFWRlJRbWMzT0hkQlVVbEZSRWhDTVdKSGVHWmpiVlo0WkZkV2VncGtSRUV5UW1kdmNrSm5SVVZCV1U4dlRVRkZSRUpEWnpSWmVscHFUMWRPYWs1RWF6Rk9hazVzVG1wSk5WcEhWWGROZWtWNVRrZE9hVmxxWjNsTlYxSnBDazFYVlRKT1ZGWm9XWHBGZVUxRFJVZERhWE5IUVZGUlFtYzNPSGRCVVZGRlJUQktNV0ZYZUd0SlIxSjJXVEowYkdOcFFuQmlWMFp1V2xoTmQwbEJXVXNLUzNkWlFrSkJSMFIyZWtGQ1FsRlJVMXBYZUd4aVYxWjFaRU14YjJOVE9YcGxWelZvWTBoT2JFMURUVWREYVhOSFFWRlJRbWMzT0hkQlVWbEZSbGhLYkFwYWJrMTJZMGhXYzJKRE9IaE9hbU16VGtNNWRGcFlTbTVhVkVFM1FtZHZja0puUlVWQldVOHZUVUZGU1VKRE1FMUxNbWd3WkVoQ2VrOXBPSFprUnpseUNscFhOSFZaVjA0d1lWYzVkV041Tlc1aFdGSnZaRmRLTVdNeVZubFpNamwxWkVkV2RXUkROV3BpTWpCM1lVRlpTMHQzV1VKQ1FVZEVkbnBCUWtOUlVtRUtSRVpvYjJSSVVuZGplbTkyVERKa2NHUkhhREZaYVRWcVlqSXdkbHBYZUd4aVYxWjFaRU14YjJOVE9YcGxWelZvWTBoT2JFeDVOVzVoV0ZKdlpGZEpkZ3BrTWpsNVlUSmFjMkl6WkhwTU1sSjJXVEowYkdOcE5UVmlWM2hCWTIxV2JXTjVPWGRrVjNoelRIcEZNazU2WXpCTU1qRnNZMjFrYkUxRVowZERhWE5IQ2tGUlVVSm5OemgzUVZGdlJVdG5kMjlQUjAweVdYcHNhbGw2VVRWT1ZGbDZXbFJaZVU5WFVteE5SRTE0VFdwU2FsbHRTVFJOYWtacldXcEdiRTVxVlRFS1dWZE5lRTFxUVdSQ1oyOXlRbWRGUlVGWlR5OU5RVVZNUWtFNFRVUlhaSEJrUjJneFdXa3hiMkl6VGpCYVYxRjNUbEZaUzB0M1dVSkNRVWRFZG5wQlFncEVRVkZ1UkVOV2IyUklVbmRqZW05MlRESmtjR1JIYURGWmFUVnFZakl3ZGxwWGVHeGlWMVoxWkVNeGIyTlRPWHBsVnpWb1kwaE9iRTFFWjBkRGFYTkhDa0ZSVVVKbk56aDNRVkV3UlV0bmQyOVBSMDB5V1hwc2FsbDZVVFZPVkZsNldsUlplVTlYVW14TlJFMTRUV3BTYWxsdFNUUk5ha1pyV1dwR2JFNXFWVEVLV1ZkTmVFMXFRV3hDWjI5eVFtZEZSVUZaVHk5TlFVVlBRa0pqVFVaWVNteGFiazEyWTBoV2MySkRPSGhPYW1NelRrTTVkRnBZU201YVZFRmFRbWR2Y2dwQ1owVkZRVmxQTDAxQlJWQkNRWE5OUTFSamVrMVVSVFZOUkVGNFRWUkJkRUpuYjNKQ1owVkZRVmxQTDAxQlJWRkNRamhOU0Zkb01HUklRbnBQYVRoMkNsb3liREJoU0ZacFRHMU9kbUpUT1d4aVIxWjBXbGMxTUV4WGFIaE5RbWRIUTJselIwRlJVVUpuTnpoM1FWSkZSVU5uZDBsTlZFMHdUa1JaZWsxNlkzY0tZVUZaUzB0M1dVSkNRVWRFZG5wQlFrVm5VbUZFUm1odlpFaFNkMk42YjNaTU1tUndaRWRvTVZscE5XcGlNakIyV2xkNGJHSlhWblZrUXpGdlkxTTVlZ3BsVnpWb1kwaE9iRXg1Tlc1aFdGSnZaRmRKZG1ReU9YbGhNbHB6WWpOa2Vrd3lVblpaTW5Sc1kyazFOV0pYZUVGamJWWnRZM2s1ZDJSWGVITk1la1V5Q2s1Nll6Qk1NakZzWTIxa2JFMUVaMGREYVhOSFFWRlJRbWMzT0hkQlVrMUZTMmQzYjA5SFRUSlplbXhxV1hwUk5VNVVXWHBhVkZsNVQxZFNiRTFFVFhnS1RXcFNhbGx0U1RSTmFrWnJXV3BHYkU1cVZURlpWMDE0VFdwQlkwSm5iM0pDWjBWRlFWbFBMMDFCUlZWQ1FUUk5SRWhDTVdKSGVHWmpiVlo0WkZkV2VncGtSRUpaUW1kdmNrSm5SVVZCV1U4dlRVRkZWa0pGYjAxVFIyZ3daRWhDZWs5cE9IWmFNbXd3WVVoV2FVeHRUblppVXpsc1lrZFdkRnBYTlRCTVYyaDRDa3d6VGpWaWJVWjNZekpWZGxsWFRqQmhWemwxWTNrNWVXUlhOWHBNZW1ONlQxUlpOVTlFVVhkT2FrVjJXVmhTTUZwWE1YZGtTRTEyVFZSQlYwSm5iM0lLUW1kRlJVRlpUeTlOUVVWWFFrRm5UVUp1UWpGWmJYaHdXWHBEUW1sbldVdExkMWxDUWtGSVYyVlJTVVZCWjFJNFFraHZRV1ZCUWpKQlRqQTVUVWR5UndwNGVFVjVXWGhyWlVoS2JHNU9kMHRwVTJ3Mk5ETnFlWFF2TkdWTFkyOUJka3RsTms5QlFVRkNhazA1VDA5aGMwRkJRVkZFUVVWamQxSlJTV2hCVGtsb0NrOTNaMkpOUVRGYWVWWkZOWFU0VjJsaFFXeFJZa3BVTVV0VVJFcG1iV2hJU25ZNVdFazBObGhCYVVGUlNHUTNjakZWUTNKbFMzUnphRlpPWjFoVE5qY0tSMUJ2TUU4M2RYUjVNa2swUzFWd01pdGxiMUpxUkVGTFFtZG5jV2hyYWs5UVVWRkVRWGRPY0VGRVFtMUJha1ZCZFV0MVpEQXlTVXNyUlZCck1qTTNiUXBMUlZSVGVHOXFhRTVaYVN0Sk5GRnZjMVJSTjNWT2RGSnJVbmRsWjNJNE9ITm5WbkF6SzBWb2RGRkRlVE5KYVVkQmFrVkJNRVp1UW5VcmQzcFplRVYxQ25kTWNqbHRhSEJOTDJwRE5uRTFTV2xIVlVGRFZXbFdWRGx4UlZCaFJ6UlRNV0Z4TW1vMmNHWldVbGw0VDBJM05XbFlLMFVLTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89In19fX0=","integratedTime":1704285060,"logIndex":61082691,"logID":"c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d"}},"Issuer":"https://token.actions.githubusercontent.com","Subject":"https://github.com/element-hq/synapse/.github/workflows/docker.yml@refs/pull/16774/merge","githubWorkflowName":"Build docker images","githubWorkflowRef":"refs/pull/16774/merge","githubWorkflowRepository":"element-hq/synapse","githubWorkflowSha":"8c6c9cc49563e629de03124cbb821db1e655ac12","githubWorkflowTrigger":"pull_request"}}]
```

2024-01-04 11:49 UTC, erikjohnston approved these changes

2024-01-04 11:49 UTC, merged