feat: add msc4028 to versions api
element-hq/synapse pull request #16787
Opened 2024-01-08 13:42 UTC by hanadi92

Fixes/Closes: https://github.com/element-hq/synapse/issues/16786

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Hanadi <hanadi.tamimi@gmail.com>

2024-01-08 13:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=16787) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=16787) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=16787) it.</sub>

2024-01-09 09:42 UTC, anoadragon453 requested changes
Hi @hanadi92, thanks for your contribution, and the context behind it.

We will need to see the `/_matrix/clients/versions` endpoint and `org.matrix.msc4028` mentioned in MSC4028 first before we add it to Synapse, otherwise the implementation is not compliant with the MSC.

It appears as if @giomfo alluded to doing so in https://github.com/matrix-org/matrix-rust-sdk/pull/2840#issuecomment-1875587994, so I suggest following up there.

2024-01-10 10:09 UTC, giomfo commented
@anoadragon453 @hanadi92 fyi I updated MSC4028 on this point: https://github.com/matrix-org/matrix-spec-proposals/pull/4028/commits/d3a1e87c26bd811372bf4819413ed685242612b7

2024-01-16 09:59 UTC, hanadi92 commented
Thanks @giomfo 
do I re-request a review? or are we waiting for something else?

2024-01-16 14:12 UTC, anoadragon453 approved these changes
Ah! Sorry, I had been waiting for https://github.com/matrix-org/matrix-spec-proposals/pull/4028#discussion_r1447392602 to be resolved, but had missed it when it happened. Thank you for the poke, and sorry for the delay.

This PR now looks good to me!

2024-01-16 14:12 UTC, anoadragon453 commented on changelog.d/16787.feature
> +Add msc4028 experimental feature config value to /_matrix/clients/versions api. Contributed by @hanadi92.
```suggestion
Advertise experimental support for [MSC4028](https://github.com/matrix-org/matrix-spec-proposals/pull/4028) through `/_matrix/clients/versions` if enabled. Contributed by @hanadi92.
```

2024-01-16 14:36 UTC, merged