listen http2 deprecated nginx
element-hq/synapse pull request #16831
Opened 2024-01-22 01:06 UTC by altf4arnold

# Listen HTTP2 deprecated since nginx 1.25.1

More info [here](https://www.nginx.com/blog/nginx-plus-r30-released/).

Nginx threw error's at me when I used all the options of the doc

2024-01-22 01:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=16831) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=16831) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=16831) it.</sub>

2024-01-22 14:05 UTC, erikjohnston requested changes
Looks good, can you just add a quick changelog in `changelog.d/16831.doc` as per the [contributing guide](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog) please?

2024-01-22 14:10 UTC, altf4arnold commented
There you go ;-) (was reading the doc)

2024-01-22 14:11 UTC, erikjohnston commented on changelog.d/16831.doc
> +NGINX listen http2 deprecation in documentation template for reverse proxy
```suggestion
NGINX listen http2 deprecation in documentation template for reverse proxy.
```

2024-01-22 14:20 UTC, altf4arnold reviewed
added the changelog

2024-01-22 14:22 UTC, erikjohnston approved these changes
Thanks!

2024-01-22 14:22 UTC, merged

2024-01-24 14:16 UTC, altf4arnold commented
> Why remove it instead of replace it with the new synatax?
> 
> > Change this:
> > ```
> > listen 443 ssl http2;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To this:
> > ```
> > listen 443 ssl;
> > http2 on;
> > ```

Hey,

I tested specifically on debian 12. There are 2 ways of installing nginx on it via APT. There is the nginx of debian.org and the nginx of the actual nginx (if you add their repo).

Due to the fact that debian tends to be kinda slow to update their packages, the new syntax breaks the debian version while the old one breaks the new version. I thought that making a "universal" config template might be better than making one that only supports latest version.

But that could definitely be a add on