An federation whitelist query endpoint extension
element-hq/synapse pull request #16848
Opened 2024-01-24 13:02 UTC by erikjohnston

This is to allow clients to query the configured federation whitelist. Disabled by default.

2024-04-16 23:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=16848) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=16848) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=16848) it.</sub>

2024-05-07 10:52 UTC, anoadragon453 requested changes
The logic looks correct! Just a few wording changes and a q about the config option placement.

I'll admit that introducing a new section for extensions still doesn't quite sit right with me.

2024-05-07 10:52 UTC, anoadragon453 commented on synapse/config/extensions.py
> +        self.federation_whitelist_endpoint: bool = config.get(
Previously @erikjohnston noted that the "extension" config section was created as this option didn't fit in anywhere else.

But would it not fit under "federation"?

https://github.com/element-hq/synapse/blob/23740eaa3da94fbe2e25180376961979fc4e8cd3/synapse/config/federation.py#L28

2024-05-07 10:52 UTC, anoadragon453 commented on tests/rest/synapse/client/test_federation_whitelist.py
> +        )
An additional test case could be adding multiple instances of the same domain to the whitelist and checking that only one appears under `whitelist`.

2024-05-07 10:52 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
> +The request path is `/_synapse/client/config/federation_whitelist`, and the
```suggestion
The request method and path is `GET /_synapse/client/config/federation_whitelist`, and the
```

2024-05-07 10:52 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
> +    "whitelist": [  // Which hosts are allowed by the whitelist
```suggestion
    "whitelist_enabled": true,  // Whether the federation whitelist is being enforced
    "whitelist": [  // Which server names are allowed by the whitelist
```

likewise in the docstring of `FederationWhitelistResource`.

2024-05-07 10:52 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
> +If `whitelist_enabled` is `false` then the server can federate with all others.
nit

```suggestion
If `whitelist_enabled` is `false` then the server is permitted to federate with all others.
```

2024-05-07 10:52 UTC, anoadragon453 commented on tests/rest/synapse/client/test_federation_whitelist.py
> +        "By default the endpoint should 404"
```suggestion
        "If the config option is not enabled, the endpoint should 404"
```

2024-05-07 18:35 UTC, devonh commented on synapse/config/extensions.py
> +        self.federation_whitelist_endpoint: bool = config.get(
It could be beneficial to follow the approach mentioned here: https://github.com/element-hq/synapse/pull/17147#discussion_r1592629098

ie. to move this to an in-tree-module and have the config follow the normal module config rules.

2024-05-08 15:12 UTC, devonh commented on synapse/config/extensions.py
> +        self.federation_whitelist_endpoint: bool = config.get(
The approach mentioned in that PR was deemed undesirable for now.

2024-05-09 10:56 UTC, anoadragon453 commented on synapse/config/extensions.py
> +        self.federation_whitelist_endpoint: bool = config.get(
> But would it not fit under "federation"?

On this, @erikjohnston wrote on Matrix:

> Yeah, maybe. I suppose the federation section is relatively small. I'm just thinking of what this will look like if we have e.g. 10 optional features like this, and whether we'd want them grouped together in one place in the docs or not
> and whether its clearer in the code or not
> I suppose we can cross that bridge when we come to it

I don't see this as an optional feature, more a config option like any other. And they won't end up all under federation of course, but spread across the config. I don't think they'll build up in any noticeable way as a group.

2024-05-09 10:59 UTC, anoadragon453 requested changes
[This comment](https://github.com/element-hq/synapse/pull/16848#discussion_r1592233490) on the previous review is still a concern of mine, but everything else lgtm.

2024-05-09 16:22 UTC, devonh commented on synapse/config/extensions.py
> +        self.federation_whitelist_endpoint: bool = config.get(
I agree. I'll move it under the federation section.

2024-05-09 18:29 UTC, devonh commented
If you're happy with everything the way it is now, I'll merge it in :smile:

2024-05-10 09:42 UTC, anoadragon453 requested changes
LGTM otherwise!

2024-05-10 09:42 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
> +response format is:
Sorry, last minute change. We should be versioning this endpoint, in case we need to make a change to it in the future.

```
GET /_synapse/client/v1/config/federation_whitelist
```

2024-05-10 14:18 UTC, devonh commented on docs/usage/configuration/config_documentation.md
> +response format is:
Indeed, good catch. Will do

2024-05-13 13:15 UTC, anoadragon453 commented on synapse/rest/synapse/client/federation_whitelist.py
> +    enabled.
There's still a reference to "extension features" here.

2024-05-13 19:38 UTC, merged