deactivated flag refactored to filter deactivated users.
element-hq/synapse pull request #16874
Opened 2024-01-30 07:34 UTC by afechler

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Alexander Fechler <alexander.fechler@bwi.de>

2024-01-30 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=16874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=16874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=16874) it.</sub>

2024-01-31 15:22 UTC, dklimpel commented on changelog.d/16874.feature
> +Query parameter `deactivated` of [List Accounts](https://matrix-org.github.io/synapse/v1.99/admin_api/user_admin_api.html#list-accounts) [admin API](https://matrix-org.github.io/synapse/v1.99/usage/a
Current doc links: https://element-hq.github.io/synapse/v1.99/

2024-02-01 09:19 UTC, afechler commented on changelog.d/16874.feature
> +Query parameter `deactivated` of [List Accounts](https://matrix-org.github.io/synapse/v1.99/admin_api/user_admin_api.html#list-accounts) [admin API](https://matrix-org.github.io/synapse/v1.99/usage/a
I have the doc links adjusted.

2024-02-19 13:44 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
I'm afraid that this is a backward-incompatible change (the same query would return different results before and after merging this PR).

I can see the value in only returning deactivated users from this API, and I like the chosen behaviour of the new API. Would you be willing to refactor this PR to add a `/v3` version of the "List Accounts" endpoint, where the `deactivated` endpoint behaves as you desire? While preserving the `/v2` endpoint with the original behaviour?

2024-02-23 12:49 UTC, afechler commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
I've refactored the PR. Now the pipeline breaks. But I don't understand the reason. The markdown looks fine for me.

2024-02-23 14:27 UTC, dklimpel commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
This looks like that other documents have links to `#list-accounts` but this does not exists anymore because of renaming the headline.

2024-02-23 14:51 UTC, afechler commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
Thank you, i've adjusted it.

2024-03-01 11:47 UTC, anoadragon453 requested changes
Hi @afechler, thanks for your patience on this one. I've left some minor changes, but overall things look good. Thanks for adding unit tests!

2024-03-01 11:47 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +    ) -> Union[bool, None]:
`Optional[bool]` is the more idiomatic way to handle a value that could be `None`.

```suggestion
    ) -> Optional[bool]:
```

Likewise below.

2024-03-01 11:47 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
```suggestion
- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are returned.
```

2024-03-01 11:47 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +  search results.
```suggestion
  users are not filtered by deactivation status.
```

2024-03-01 11:47 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +        return None if parse_boolean(request, "deactivated") else False
Just to document this function, as I needed a moment to think about it personally:

```suggestion
        """
        Return None (no filtering) if `deactivated` is `true`, otherwise return `False`
        (exclude deactivated users from the results).
        """
        return None if parse_boolean(request, "deactivated") else False
```

The other implementation of `_parse_parameter_deactivated` is simpler and probably doesn't need a docstring.

2024-03-01 11:47 UTC, anoadragon453 commented on tests/rest/admin/test_user.py
> +        # Query deactivated users
```suggestion
        # Query non-deactivated users
```

2024-03-01 11:47 UTC, anoadragon453 commented on changelog.d/16874.feature
> +Handling of the query parameter `deactivated` in [List Accounts](https://element-hq.github.io/synapse/v1.99/admin_api/user_admin_api.html#list-accounts) [admin API](https://element-hq.github.io/synap
```suggestion
Add a new [List Accounts v3](https://element-hq.github.io/synapse/v1.103/admin_api/user_admin_api.html#list-accounts-v3) Admin API with improved deactivated user filtering capabilities.
```

2024-03-01 11:48 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- `deactivated` - Optional flag to filter deactivated users. If `true`, only deactivated users are queried.
I believe this was just a race condition in SyTest and can be ignored. Sorry about that!

2024-03-11 16:07 UTC, anoadragon453 approved these changes
LGTM. Thank you for your patience :)

2024-03-11 16:08 UTC, merged