bugfix: always prefer unthreaded receipt when >1 exist (MSC4102)
element-hq/synapse pull request #16927
Opened 2024-02-16 11:19 UTC by kegsay

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-02-16 12:00 UTC, anoadragon453 commented
As this PR references server behaviour specified by an MSC, my initial reaction was that "this needs an `experimental_features` flag"! However, I think we can make an exception here, as:

1. This does not communicate any unstable prefixes for clients to start relying on.
2. The MSC selects a specific action for cases where the spec previously had undefined and implementation-dependent behaviour.

In essence this change already fits within the current spec version, which was ambiguous. Today, this change in Synapse wouldn't require an MSC. However, I commend @kegsay for going and clarifying the spec as well by writing an MSC.

2024-02-16 12:30 UTC, kegsay commented
Yeah @turt2live said much the same in that it doesn't really need to be an MSC, it's a clarification of previously undefined behaviour.

2024-02-20 10:51 UTC, anoadragon453 requested changes
Thanks for taking this on! A couple small suggestions.

2024-02-20 10:51 UTC, anoadragon453 commented on synapse/storage/databases/main/receipts.py
> +            if user_id in receipt_type_dict:  # existing receipt
I think the first arm of this `if` statement does not handle the following cases:

* there is an existing receipt, and it is unthreaded
* there is an existing receipt and it is threaded, but there is an incoming threaded receipt

In both of those cases, `receipt_type_dict` is not modified. Is this on purpose? If not, perhaps it'd be best to pull line 490 up and out of this `if` statement, so that it is run regardless (and then potentially overridden later).

2024-02-20 13:52 UTC, kegsay commented on synapse/storage/databases/main/receipts.py
> +            if user_id in receipt_type_dict:  # existing receipt
If there is an existing receipt, and it is unthreaded then it should not be replaced so I would expect the conditional to fail.

It is impossible for there to be a threaded receipt and then _another_ threaded receipt for the same (user, event, type) tuple. If that did happen, it's undefined behaviour.

2024-02-20 14:12 UTC, merged