Parse json validation
element-hq/synapse pull request #16923
Opened 2024-02-15 09:06 UTC by TrevisGordan

This pull request introduces a new servlet function named `parse_json`, aimed at simplifying and standardizing the process of parsing JSON objects from query parameters. This function complements our existing utility functions such as `parse_integer` and `parse_string`, offering a unified approach to parameter parsing across our application.

The necessity for `parse_json` arises from the requirement to handle JSON formatted data in query parameters (in `filter`parameters, on room endpoints), which, lacked a dedicated parsing mechanism. By incorporating `parse_json`, we streamline the parsing process and also enforce stricter validation of input data, ensuring that only valid JSON objects are processed, preventing internal server errors. This is achieved through the inclusion of an `INVALID_PARAM` error response, which is triggered when the parsed data fails to meet the JSON object criteria. The error message explicitly states that the parameter "must be a valid JSON object," thereby providing clear feedback for troubleshooting.

#### Key Features:
- **Unified JSON Parsing**: Harmonizes with existing parsing functions, offering a consistent parsing approach.
- **Enhanced Validation**: Incorporates error handling for non-compliant JSON input, improving parameter validation. This should fix https://github.com/element-hq/synapse/issues/16922.

#### Implementation Snippet:
Below is an example snippet demonstrating the usage of `parse_json` to parse a JSON object from the `filter` query parameter:

```python
filter_json = parse_json(request, "filter", encoding="utf-8")
```

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x]  Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x]  [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-02-17 20:46 UTC, TrevisGordan commented
Yes, I've also seen that thanks. Exactly. Coming from FastAPI, I'm a big fan of Pydantic and would advocate for its use in model validation. This, though, is meant for a step before—checking if the input is actually JSON, particularly in the case of query parameters. From what I've seen, this is mostly used for the filtering functionality. I even already thought about it as a point for consideration on "where to go from here" for the next steps. I found a filter validation function (jsonschema) [def check_valid_filter(self, user_filter_json: JsonDict) -> None:](https://github.com/element-hq/synapse/blob/0621e8eb0eaf20c88b2ebfc07d3a643340093839/synapse/api/filtering.py#L174) but not utilized on the endpoints—to further ensure that in the case of valid JSON, it is a valid filter. This could be uniformly done with Pydantic.

2024-02-19 23:52 UTC, clokep commented
Makes sense! I don't think there are other spots that JSON is passed as a query parameter, it is a rather odd choice.

2024-02-20 12:05 UTC, anoadragon453 requested changes
Overall looks great, thank you for putting this together! I have a smattering of wording changes, and a request for tests.

2024-02-20 12:36 UTC, TrevisGordan commented on changelog.d/16923.bugfix
> +Adds validation check to prevent 500 internal server error on invalid Json Filter request.
Thanks for the Insights! - I'll keep that in mind. 

2024-02-20 12:44 UTC, TrevisGordan commented on synapse/http/servlet.py
> +        message = f"Missing required integer query parameter {name}"
Good catch! 🔥

2024-02-20 16:21 UTC, TrevisGordan commented on synapse/http/servlet.py
Thanks for the prior feedback, and suggestions!

I have implemented the tests as discussed. I welcome any feedback you may have regarding your general project test practices. I made an effort to align with the existing test cases as closely as possible.

I aimed to address both positive and negative scenarios. Considering the potential outcomes, it might be actual beneficial to use `self.assertNotEqual(channel.code, HTTPStatus.BAD_REQUEST, channel.json_body)` rather than relying solely on `HTTPStatus.OK`, to account for unexpected responses, but I leave that up for discussion.

2024-02-20 16:36 UTC, anoadragon453 requested changes
LGTM otherwise!

2024-02-20 16:36 UTC, anoadragon453 commented on synapse/http/servlet.py
Thanks for adding tests! I would stick with `HTTPStatus.OK`, as you may receive `HTTPStatus.BAD_REQUEST` for any number of reasons. Other tests should test other failure modes.

2024-02-20 16:36 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +        _valid_filter_str = '{"types": ["m.room.message"]}'
Generally you should only precede a variable name with an underscore in Python if you'd like to label the output of a function, but not actually *use* it. Here we are using `_valid_filter_str`, so it should not have a leading underscore.

Could you remove it, along with `_invalid_filter_str` and from other tests please?

2024-02-20 17:27 UTC, anoadragon453 commented on synapse/http/servlet.py
> +        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.INVALID_PARAM)
Sorry, but I've just remembered that we have `M_NOT_JSON` as [a valid error code in the spec](https://spec.matrix.org/v1.9/client-server-api/#common-error-codes). Could you use that errcode instead please?

2024-02-20 21:21 UTC, TrevisGordan commented on synapse/http/servlet.py
> +        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.INVALID_PARAM)
No worries. ;)
I saw that and considered it, but the spec mentions only:
`The request body is not a JSON object`, `The request body is malformed`, or `Content must be a JSON object.` This hints at the request body, not the parameter, which could be rather misleading. So, I went with `INVALID_PARAM` as it directly points to the Param in question. Especially in cases where we hypothetically may have a JSON body and a JSON Param in a single request - even as this is not currently the case, I think.

I just now found that the sync endpoint also somehow uses a filter_id/filter, but it seems like it is unimplicitly checking if the given filter_id is actually a filter object, and recovering it(?) or we then return:
[raise SynapseError(400, "Invalid filter JSON", errcode=Codes.NOT_JSON)](https://github.com/element-hq/synapse/blob/0621e8eb0eaf20c88b2ebfc07d3a643340093839/synapse/rest/client/sync.py#L179-L180)

But this case is not described in the sync schema-spec. So, I would even rather change the error on the sync as well, for more uniform and user-friendly handling. What do you think? (Other than that, I can surely change it!)

2024-02-23 10:36 UTC, TrevisGordan commented on synapse/http/servlet.py
> +        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.INVALID_PARAM)
```suggestion
        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.M_NOT_JSON)
```

2024-04-16 15:16 UTC, anoadragon453 requested changes
Huge apologies for taking so long to get back to this - I've only now been getting back to reviewing Synapse PRs. I have only a couple small things below, but otherwise this looks good to go.

Thanks for your patience.

2024-04-16 15:16 UTC, anoadragon453 commented on synapse/http/servlet.py
> +        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.INVALID_PARAM)
The formal definition of `M_NOT_JSON` from the spec is:

> Request did not contain valid JSON.

which is generic enough to cover query parameters.

I see that we're using this for [GET /_matrix/client/v3/rooms/{roomId}/messages](https://spec.matrix.org/v1.10/client-server-api/#get_matrixclientv3roomsroomidmessages) currently. That endpoint doesn't have an errcode specified for the case of the `filter` query parameter being invalid JSON. So we technically have free reign here.

I would still argue for `M_NOT_JSON` however, as it's more specific to the problem than `M_INVALID_PARAM` is.

(Note that in your suggestion above, the variable is actually called `Codes.NOT_JSON`.) And also note that the changelog entry will need to be updated.

2024-04-16 15:16 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +        _valid_filter_str = '{"types": ["m.room.message"]}'
Thanks for citing the PEP! It's interesting to read where this convention came from.

In Synapse, we certainly do use leading underscores for internal function/method names and private class variables (`self._internal_var`). This is to signal to code external to classes that they shouldn't try to access this field (it is internal). 

However, we don't use this convention for local variable names - so at least for this codebase, I would remove the leading underscore.

2024-04-16 15:16 UTC, anoadragon453 commented on changelog.d/16923.bugfix
> +Adds validation check to prevent 500 internal server error on invalid Json Filter request.
Are you happy to accept my suggestion here? I prefer the suggested version of the changelog for the reasons in my initial comment.

2024-04-16 17:21 UTC, TrevisGordan commented on synapse/http/servlet.py
> +        raise SynapseError(HTTPStatus.BAD_REQUEST, message, errcode=Codes.INVALID_PARAM)
Alright, sure, - I can live with that. In combination with the error message pointing to the parameter, that's also fine. ;) (+ Thanks for the hint; ++ i modified the changelog file accordingly)

2024-04-16 17:27 UTC, TrevisGordan commented
@anoadragon453  Ah no worries! Thanks for coming back to it.
I made the requested changes. :)
I updated the new test cases accordingly for "NOT_JSON"

I re-ran the linters.
I re-ran the tests (passed)
I also ran systests (passed)

2024-04-17 12:52 UTC, anoadragon453 approved these changes
LGTM, thank you very much!

2024-04-18 11:32 UTC, TrevisGordan commented
✅ 🎉 - @anoadragon453 Please don't forget to merge before we lose sync to upstream. :)

2024-04-18 12:57 UTC, merged

2024-04-18 12:58 UTC, anoadragon453 commented
Oops, apparently forgot to press the button. Thanks for the poke!