Stabilize support for Retry-After header (MSC4014)
element-hq/synapse pull request #16947
Opened 2024-02-20 17:08 UTC by clokep

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Fixes #16944

2024-03-06 10:58 UTC, anoadragon453 requested changes
A couple more cleanups to do, but otherwise LGTM.

Thanks for doing this, and for adding a clarifying comment!

2024-03-06 10:58 UTC, anoadragon453 commented on synapse/api/errors.py
> -            if self.include_retry_after_header and retry_after_ms is not None
`self.include_retry_after_header` can now be deleted.

2024-03-06 10:58 UTC, anoadragon453 commented on tests/api/test_errors.py
> +        err = LimitExceededError(limiter_name="test", retry_after_ms=100)
Seems there are a few instances of `msc4041_enabled` still being set in the tests, yet the option no longer exists.

2024-03-06 17:01 UTC, clokep commented
This should be ready for another review, assuming CI passes.

2024-03-08 09:32 UTC, anoadragon453 approved these changes
LGTM. Thank you very much!

CI failures indicate a flaky sytest.

2024-03-08 09:33 UTC, merged