MSC4108 implementation
element-hq/synapse pull request #17056
Opened 2024-04-05 16:30 UTC by sandhose

- **Move push off main**
- **Fixup**
- **Fixup**
- **Newsfile**
- **Setup the basic Python -> Rust call for the rendezvous endpoint**
- **Primitives to transform Twisted request and response objects to and from Rust**
- **WIP rendezvous implementation**
- **Some more rendezvous implementation**

2024-04-10 15:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17056) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17056) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17056) it.</sub>

2024-04-11 14:29 UTC, hughns requested changes

2024-04-11 14:29 UTC, hughns commented on synapse/http/server.py
> +        b"/_matrix/client/unstable/org.matrix.msc4108/rendezvous"
This path needs to match https://github.com/element-hq/synapse/pull/17056/files#diff-60b44b832bdef37a1bd6f9174c4e59ad6539a88363ad7292c4a48e9e556da4a7R81

Maybe it should be a shared constant?

2024-04-12 12:32 UTC, hughns commented on synapse/http/server.py
> +        b"/_matrix/client/unstable/org.matrix.msc4108/rendezvous"
```suggestion
        b"/_synapse_/rendezvous"
```

2024-04-12 13:03 UTC, sandhose commented on synapse/http/server.py
> +        b"/_matrix/client/unstable/org.matrix.msc4108/rendezvous"
done!

2024-04-18 10:42 UTC, sandhose commented on synapse/http/server.py
> +        b"/_matrix/client/unstable/org.matrix.msc4108/rendezvous"
I fixed the path but it isn't using a constant

2024-04-18 14:26 UTC, hughns commented on synapse/rest/client/rendezvous.py
> +        self._handler.handle_post(request)
Ah, I forgot that you had put a note to do this in another PR.

2024-04-19 15:41 UTC, anoadragon453 requested changes
Just some small comments, nothing major. Thanks for adding tests, and love all the rust here!

2024-04-19 15:50 UTC, sandhose commented on rust/src/rendezvous/mod.rs
> +                "M_CONCURRENT_WRITE",
That error code is defined by the MSC though, should it be prefixed or something?

https://github.com/matrix-org/matrix-spec-proposals/blob/element-hq/oidc-qr-login/proposals/4108-oidc-qr-login.md#send-a-payload-to-the-rendezvous-session-put-rendezvous-session-url

2024-04-19 15:53 UTC, sandhose commented on rust/src/rendezvous/mod.rs
> +        let session = Session::new(body, content_type, now, Duration::from_secs(5 * 60));
@hughns this means the QR code would expire after 30s and a new one should be generated? Or is it expected that GETing on the endpoint keeps it alive until the user scans it?

2024-04-19 16:15 UTC, hughns commented on rust/src/rendezvous/mod.rs
> +        session.update(data, content_type, now);
The MSC should say that the `PUT` doesn't bump the expiry. I will check that this is the case. But this implementation looks correct in this regard.

2024-04-19 16:54 UTC, hughns commented on rust/src/rendezvous/mod.rs
> +        session.update(data, content_type, now);
I've corrected the MSC in https://github.com/matrix-org/matrix-spec-proposals/commit/4f9a4a42e6ba442989bee06a037eaedecc1cc846.

2024-04-22 14:13 UTC, hughns commented on rust/src/rendezvous/mod.rs
> +                "M_CONCURRENT_WRITE",
In https://github.com/element-hq/synapse/pull/17113 I have changed `errcode` to be `M_UNKNOWN` and added a `org.matrix.msc4108.errcode` value of `M_CONCURRENT_WRITE`.

2024-04-22 15:14 UTC, anoadragon453 commented on rust/src/rendezvous/mod.rs
> +                "M_CONCURRENT_WRITE",
I'd like to see a reference to `org.matrix.msc4108.errcode` in the MSC, fwiw.

2024-04-22 15:58 UTC, hughns commented on rust/src/rendezvous/mod.rs
> +                "M_CONCURRENT_WRITE",
> Sounds good, though I'd like to see a reference to `org.matrix.msc4108.errcode` in the MSC. Under ["Unstable Prefix"](https://github.com/matrix-org/matrix-spec-proposals/blob/element-hq/oidc-qr-login/proposals/4108-oidc-qr-login.md?rgh-link-date=2024-04-22T15%3A14%3A38Z#unstable-prefix).

Added in https://github.com/matrix-org/matrix-spec-proposals/commit/76f175b0110dbda4deb33c33c692a1a7202a42ba

2024-04-25 11:40 UTC, anoadragon453 approved these changes
This LGTM after https://github.com/element-hq/synapse/pull/17122, thanks!

Issues to track follow-up work:

- https://github.com/element-hq/synapse/issues/17124
- https://github.com/element-hq/synapse/issues/17123

2024-04-25 12:28 UTC, anoadragon453 commented
Tests were failing due to https://github.com/element-hq/synapse/pull/17125. This PR has now been updated with latest `develop`, and now all CI checks will run.

2024-04-25 12:50 UTC, merged