Add support for MSC3823 - Account Suspension
element-hq/synapse pull request #17051
Opened 2024-04-04 20:18 UTC by H-Shay

This PR adds preliminary support for [MSC3823](https://github.com/matrix-org/matrix-spec-proposals/pull/3823) - Account suspension.

The changes 
 - add a column `suspended` to the `users` table
 - adds functions to check/set whether a user's account is suspended
 - adds functionality to prevent suspended users from sending invites, joining rooms, or knocking on rooms
 
Note that this is not the full scope of the MSC - more functionality will be added in follow-up PRs. I am splitting up the implementation for ease of review.  

Should be reviewable commit-by-commit

2024-04-16 10:52 UTC, anoadragon453 requested changes
This lgtm on the whole! Note that we will eventually want an experimental feature config option for this functionality, but given that there's currently no way to set a user as suspended (outside of fiddling with the DB), I'm happy to merge this PR without one.

Just a couple small changes noted below.

2024-04-16 10:52 UTC, anoadragon453 commented on synapse/storage/databases/main/registration.py
> +                    COALESCE(suspended, FALSE) AS suspended
I don't think we need to use coalesce here, as the column is marked as `NOT NULL`.

Why it's used for the other columns I'm not sure (historically null-able perhaps?).

2024-04-16 10:52 UTC, anoadragon453 commented on synapse/storage/databases/main/registration.py
> +                True if the user's account is suspended, false if not.
I would just note here that `False` is also returned if the `user_id` cannot be found.

2024-04-16 10:52 UTC, anoadragon453 commented on changelog.d/17051.feature
> +Add preliminary support for MSC3823 - Account Suspension.
Oh, and it would be good to link the MSC.

```suggestion
Add preliminary support for [MSC3823](https://github.com/matrix-org/matrix-spec-proposals/pull/3823) - Account Suspension.
```

2024-05-01 16:25 UTC, H-Shay commented
@anoadragon453 - this is ready for another look whenever you get a chance :)

2024-05-01 16:45 UTC, anoadragon453 approved these changes
Looks good to me, thanks!

2024-05-01 16:45 UTC, merged