Helpers to transform Twisted requests to Rust http Requests/Responses
element-hq/synapse pull request #17081
Opened 2024-04-12 14:52 UTC by sandhose

Needed for #17056 

This adds functions to transform a Twisted request to the `http::Request`, and then to send back an `http::Response` through it.

It also imports the SynapseError exception so that we can throw that from Rust code directly

Example usage of this would be:

```rust
use crate::http::{http_request_from_twisted, http_response_to_twisted, HeaderMapPyExt};

fn handler(twisted_request: &PyAny) -> PyResult<()> {
  let request = http_request_from_twisted(twisted_request)?;

  let ua: headers::UserAgent = request.headers().typed_get_required()?;

  if whatever {
    return Err((crate::errors::SynapseError::new(
      StatusCode::UNAUTHORIZED,
      "Whatever".to_owned
      "M_UNAUTHORIZED",
      None,
      None,
    )));
  }

  let response = Response::new("hello".as_bytes());
  http_response_to_twisted(twisted_request, response)?;

  Ok(())
}
```

2024-04-17 15:51 UTC, anoadragon453 requested changes
lgtm overall! Just some small changes really.

2024-04-17 15:51 UTC, anoadragon453 commented on rust/src/http.rs
> +/// Returns an error if the Python object doens't properly implement ``IRequest``
```suggestion
/// Returns an error if the Python object doesn't properly implement ``IRequest``
```

2024-04-17 15:51 UTC, anoadragon453 commented on rust/src/http.rs
> +/// Returns an error if the Python object doens't properly implement ``IRequest``
```suggestion
/// Send an [`http::Response`] through a Twisted ``IResponse``
///
/// It uses the following members of ``IResponse``:
///
///  - ``responseHeaders``, which is expected to have a `addRawHeader(bytes, bytes)` method
///  - ``setResponseCode(int)`` method
///  - ``write(bytes)`` method
///  - ``finish()`` method
///
///  # Errors
///
/// Returns an error if the Python object doesn't properly implement ``IResponse``
```

I think?

2024-04-17 15:51 UTC, anoadragon453 commented on rust/src/http.rs
> +                "M_MISSING_HEADER",
`M_MISSING_HEADER` and `M_INVALID_HEADER` doesn't actually exist in the [Client-Server API spec](https://spec.matrix.org/v1.10/client-server-api/#common-error-codes).

Feel free to propose them in an MSC! But for now, you may need to use `M_UNKNOWN` I'm afraid.

2024-04-17 15:51 UTC, anoadragon453 commented on rust/src/errors.rs
> +                            .expect("header value is valid ASCII")
Looks like `http` wants what it calls *visible ASCII*:

- https://docs.rs/http/latest/src/http/header/value.rs.html#268-278
- `is_visible_ascii` definition: https://docs.rs/http/latest/src/http/header/value.rs.html#600-602

From reading https://stackoverflow.com/questions/47687379/what-characters-are-allowed-in-http-header-values, it looks like only those characters should make it past any self-respecting reverse proxy. So hopefully we don't encounter any other characters in the wild.

We can also find out and fix it later if any cases do come up.

2024-04-17 15:56 UTC, erikjohnston commented on rust/src/errors.rs
> +                            .expect("header value is valid ASCII")
Can we just return a `Result` here and then collect into `Result<HashMap<_, _>, _>`?

2024-04-17 16:02 UTC, sandhose commented on rust/src/http.rs
> +                "M_MISSING_HEADER",
Duh, I meant to make that `M_MISSING_PARAM` and `M_INVALID_PARAM`, as this is what we use in MSC4108

2024-04-17 16:04 UTC, sandhose commented on rust/src/http.rs
> +/// Returns an error if calling the ``read`` on the Python object failed
I thought I did that because clippy or rustdoc would complain if you used single backticks and there is a matching item, telling you you should make that a link. Checking again, it doesn't seem to be the case, I may have imagined it, but this is why I used double backticks to reference python stuff in the first place

2024-04-17 16:10 UTC, sandhose commented on rust/src/http.rs
> +/// Returns an error if the Python object doens't properly implement ``IRequest``
Not really, because the Twisted `IRequest` interface is both to read the incoming request and reply to the incoming request. A typical Twisted handler on the python side will often do like `respond_with_json(request, 200, {})`

2024-04-17 16:27 UTC, sandhose commented on rust/src/http.rs
> +/// Returns an error if the Python object doens't properly implement ``IRequest``
Fixed in e8f4865e58738e46c9b46fbf613812d9eb6115ce

2024-04-17 16:28 UTC, sandhose commented on rust/src/http.rs
> +                "M_MISSING_HEADER",
Fixed in 740b1fbf94fa845e7da085d7421d3d20b5c4b9a3

2024-04-17 16:28 UTC, sandhose commented on rust/src/http.rs
> +/// Returns an error if calling the ``read`` on the Python object failed
Fixed in f6d64b1f2b9ea3dfb8e88c29238459276e9691b7

2024-04-17 16:29 UTC, sandhose commented on rust/src/errors.rs
> +                            .expect("header value is valid ASCII")
Fixed in de282d7224cdbcffc4d843a7b566275e35eef3e1

I could have used proper combinators here but I did find the more imperative approach more readable

2024-04-18 10:03 UTC, anoadragon453 commented on rust/src/http.rs
> +/// Returns an error if the Python object doens't properly implement ``IRequest``
Ah, intuitive! :yum:

2024-04-18 10:20 UTC, merged