Add support for MSC4114
element-hq/synapse pull request #17104
Opened 2024-04-18 18:17 UTC by richvdh

Add membership metadata to each event returned to the client.

2024-04-26 12:02 UTC, anoadragon453 requested changes
Overall this LGTM! Just some tiny notes, and if you could fix up the conflict.

2024-04-26 12:02 UTC, anoadragon453 commented on tests/test_visibility.py
> +        # User joins and leaves room. Should be able to seem the join and leave,
```suggestion
        # User joins and leaves room. Should be able to see the join and leave,
```

2024-04-26 13:45 UTC, richvdh commented on synapse/events/utils.py
> +    which means it can then be updated without corrupting the in-memory cache.
Well. As it happens, we're updating a top-level key in the `unsigned` dict, so a shallow copy is enough.

 I mean doing a shallow copy isn't deliberate on my part, it's just what calling `make_event_from_dict(event.get_dict(), ...)` happens to do.

Generally this whole thing seems like a big mess, and I kinda hate it.
 * Why do both `event.get_dict` and `make_event_from_dict` copy `unsigned`, when they doesn't copy any of the other properties (like, say, `content`)? 
 * If they are going to copy it, why is it a shallow copy?
 * Why are `stream_ordering` and `outlier` part of `internal_metadata` in the in-memory model when they are separate in the database, so need magic handling?
 * Also, why is the value of `unsigned` not protected by `use_frozen_dicts` like the rest of the event, so that I nearly shot my own foot off here?

Nobody knows, but fixing these things aren't really today jobs. 

I'll add some more comments which might help here.

2024-04-26 13:50 UTC, richvdh commented on synapse/visibility.py
> +    """Whether the user was joined at the event"""
There is some precedent for this style in, for example, `synapse.util.caches.response_cache.ResponseCacheContext`, but  that was probably my fault too. I'll switch this one to the `Attributes` style.

2024-04-29 14:22 UTC, anoadragon453 approved these changes

2024-04-29 14:22 UTC, merged