SCIM provisioning API basic implementation
element-hq/synapse pull request #17144
Opened 2024-05-02 14:49 UTC by azmeuk

This is an implementation of MSC4098. It implements a subset of the SCIM provisioning protocol defined in [RFC7643](https://datatracker.ietf.org/doc/html/rfc7643) and [RFC7644](https://datatracker.ietf.org/doc/html/rfc7644).

It contains:

- A SCIM servlet implementing the minimal SCIM endpoints.
  - The data edition/retrieval part largely takes inspiration (and shameless copied) from `synapse/rest/admin/users.py`.
  - The SCIM payload validation and production is achieved with [scim2-models](https://scim2-models.readthedocs.io), a library based on pydantic which I maintain.
- Unit tests for those endpoints.
- Documentation on the state of the SCIM implementation, and examples of requests and response payloads.

The SCIM requires needs python 3.9+ (because of the use of [typing.Anotated](https://docs.python.org/3/library/typing.html#typing.Annotated) in scim2-models) and pydantic 2.7.0+

### SCIM implementation details

Only a subset of the SCIM endpoints are implemented:

What's implemented:
- The main [endpoints](https://datatracker.ietf.org/doc/html/rfc7644#section-3.2):
  - /Users (GET, POST)
  - /Users/<user_id> (GET, PUT, DELETE)
  - /ServiceProviderConfig (GET)
  - /Schemas (GET)
  - /Schemas/<schema_id> (GET)
  - /ResourceTypes (GET)
  - /ResourceTypes/<resource_type_id>
- [pagination](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.4)
- The user attributes:
   - userName
   - password
   - emails
   - phoneNumbers
   - displayName
   - photos (as a [MXC URI](https://spec.matrix.org/legacy/client_server/r0.6.0#matrix-content-mxc-uris))
   - active 

What is defined in the SCIM specs but not implemented here:
- A few [endpoints](https://datatracker.ietf.org/doc/html/rfc7644#section-3.2):
  - /Users (PATCH)
  - [/Me](https://datatracker.ietf.org/doc/html/rfc7644#section-3.11) (GET, POST, PUT, PATCH, DELETE)
  - /Groups (GET, POST, PUT, PATCH) (but this no relevant)
  - [/Bulk](https://datatracker.ietf.org/doc/html/rfc7644#section-3.7) (POST)
  - [/.search](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.3) (POST)
- [filtering](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.2)
- [sorting](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.3)
- [attributes selection](https://datatracker.ietf.org/doc/html/rfc7644#section-3.4.2.5)
- [ETags](https://datatracker.ietf.org/doc/html/rfc7644#section-3.14)

What do you think?

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-05-14 12:16 UTC, erikjohnston commented
(I've taken this out of the review queue as its in draft, let us know if you want feedback)

2024-05-27 10:27 UTC, azmeuk commented
Hi @erikjohnston
Thank you for your feedback offering. Indeed this is a draft, but I hope to take back the development soon.

There is one design question though. I see that there is a dependency to pydantic in synapse, and I recently published [pydantic-scim2](https://pydantic-scim2.readthedocs.io/en/latest/) that is a library that helps to parse and serialize SCIM2 payloads using pydantic.

Would it make sense to add a dependency towars pydantic-scim2 in synapse, or should I continue checking and building SCIM2 payloads manually?

2024-07-25 12:13 UTC, azmeuk commented
Hi @erikjohnston
I think the PR can be reviewed now. I edited the OP to detail what's in there.
I am available on #synapse-dev too if there are things to discuss.

2024-08-16 06:38 UTC, azmeuk commented
I fixed the typing issues, but I need to fix type annotations and add a `py.typed` file in scim2-models as well.

2024-08-19 19:56 UTC, azmeuk commented
mypy issues are fixed, however the `check_pydantic_models.py` raises a `TypeError`. I am not sure why. Is it due to my modifications or is it a bug in the script?

```python
Traceback (most recent call last):
  File "/home/eloi/dev/matrix/synapse/scripts-dev/check_pydantic_models.py", line 495, in <module>
    sys.exit(lint())
             ^^^^^^
  File "/home/eloi/dev/matrix/synapse/scripts-dev/check_pydantic_models.py", line 226, in lint
    failures = do_lint()
               ^^^^^^^^^
  File "/home/eloi/dev/matrix/synapse/scripts-dev/check_pydantic_models.py", line 251, in do_lint
    module_infos = list(
                   ^^^^^
  File "/usr/lib/python3.12/pkgutil.py", line 78, in walk_packages
    __import__(info.name)
  File "/home/eloi/dev/matrix/synapse/synapse/module_api/__init__.py", line 122, in <module>
    from synapse.rest.client.login import LoginResponse
  File "/home/eloi/dev/matrix/synapse/synapse/rest/__init__.py", line 25, in <module>
    from synapse.rest import admin, scim
  File "/home/eloi/dev/matrix/synapse/synapse/rest/scim.py", line 32, in <module>
    from scim2_models import (
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/scim2_models/__init__.py", line 1, in <module>
    from .base import BaseModel
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/scim2_models/base.py", line 327, in <module>
    class BaseModel(PydanticBaseModel):
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/main.py", line 221, in __new__
    inferred = ModelField.infer(
               ^^^^^^^^^^^^^^^^^
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/fields.py", line 504, in infer
    return cls(
           ^^^^
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/fields.py", line 434, in __init__
    self.prepare()
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/fields.py", line 544, in prepare
    self._set_default_and_type()
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/fields.py", line 568, in _set_default_and_type
    default_value = self.get_default()
                    ^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/fields.py", line 437, in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eloi/.cache/pypoetry/virtualenvs/matrix-synapse-jPdyJ-JW-py3.12/lib/python3.12/site-packages/pydantic/v1/utils.py", line 693, in smart_deepcopy
    return deepcopy(obj)  # slowest way when we actually might need a deepcopy
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'classmethod' object
```

2024-09-05 17:42 UTC, azmeuk commented
I opened #17667 to fix the `check_pydantic_models.py` issue.

2024-09-17 15:34 UTC, azmeuk commented
Finally, the CI is green! :tada:
@erikjohnston this is entirely for review now.

2024-10-14 10:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17144) it.</sub>

2024-11-11 13:08 UTC, reivilibre commented on synapse/rest/scim.py
> +            users = [await self.get_scim_user(item.name) for item in items]
This could wind up making a lot of individual database transactions. It's probably OK for a first pass but you might find performance problems arising from here.

Should there be a maximum limit on `req.count`?

2024-11-11 13:24 UTC, reivilibre commented on synapse/rest/scim.py
> +                ),
I don't think we support HTTP Basic auth anywhere

2024-11-11 13:25 UTC, reivilibre commented on synapse/rest/scim.py
> +                    documentation_uri="https://element-hq.github.io/synapse/latest/openid.html",
Our `Bearer` tokens are not really OAuth, or at least, not only OAuth. Maybe linking to the Matrix spec for documentation is more accurate?

2024-11-11 13:28 UTC, reivilibre commented on tests/rest/test_scim.py
> +            )
This is not really realistic, since in real-world use cases users cannot have https profile avatars

2024-11-11 13:35 UTC, reivilibre commented on tests/rest/test_scim.py
> +            "externalId": "bjensen@test",
the fact you don't get this ID back afterwards, feels pretty strange and might violate the SCIM spec...

 I wonder what the least painful option here is. It seems like it might be an optional field in the SCIM spec but I suspect it's useful to many IdPs...

2024-11-11 13:39 UTC, reivilibre commented on tests/rest/test_scim.py
> +        self.assertEqual(204, channel.code)
should test that the user is deactivated afterwards

2024-11-13 10:28 UTC, azmeuk commented
Thank you both for your reviews.

@reivilibre I will address your suggestions soon and ping you for a second round.

@MatMaul, would `/_synapse/admin/scim/v2` be fine, or should there be a mention that the feature is unstable?

2024-11-13 10:35 UTC, MatMaul commented
> @MatMaul, would `/_synapse/admin/scim/v2` be fine, or should there be a mention that the feature is unstable?

I think it's fine, the unstable prefix is for features that are not yet in the spec, but this doesn't really need a MSC.

You should probably remove mention of MSC4098 in the title of the PR, and strike through `This is an implementation of MSC4098` in the body, so we keep a ref perhaps.

2024-11-13 14:08 UTC, MatMaul commented on docs/usage/administration/admin_api/scim_api.md
> +The SCIM endpoint is `/_matrix/client/unstable/coop.yaal/scim`.
All endpoints in the doc need an update.

2024-11-13 14:08 UTC, MatMaul commented on synapse/config/experimental.py
> +
This seems not needed anymore. However we should probably disable the SCIM endpoint altogether if MSC3861 is enabled ?

2024-11-13 14:28 UTC, azmeuk commented on synapse/config/experimental.py
> +
Why isn't it needed anymore?

> However we should probably disable the SCIM endpoint altogether if [MSC3861](https://github.com/matrix-org/matrix-spec-proposals/pull/3861) is enabled ?

Do you suggest to not raise a ConfigError and just disable SCIM instead?

2024-11-13 14:33 UTC, azmeuk commented on docs/usage/administration/admin_api/scim_api.md
> +The SCIM endpoint is `/_matrix/client/unstable/coop.yaal/scim`.
You were too quick, I had not made the modification yet :)
This is fixed now.

2024-11-13 15:29 UTC, MatMaul commented on synapse/config/experimental.py
> +
> Why isn't it needed anymore?

If it's not a MSC impl no need to gate the feature as experimental I believe :) 

> Do you suggest to not raise a ConfigError and just disable the SCIM feature instead?

just disable directly, since we would not even enable explicitly SCIM anymore anyway.

2024-11-22 14:28 UTC, azmeuk commented
@reivilibre I think all your comments have been addressed now. Most of them have been fixed in the code and I responded to some with new questions.
The implementation have been tested against Keycloak with the [keycloak-scim](https://forge.libre.sh/libre.sh/keycloak-scim) extension.

I am sorry for the many commits, the PR looks like a mess. If it is easier for the review, I can close it and open a new one. Let me know.

2025-01-24 12:31 UTC, reivilibre requested changes
this is looking generally good, but a few comments (and some still open from last time).

The CI is also unhappy but hopefully that's nothing too difficult?

2025-01-24 12:31 UTC, reivilibre commented on docs/usage/administration/admin_api/scim_api.md
> +    msc4098:
if this is no longer tracking an MSC, let's rename this feature to just `scim`.

I understand what MatMaul is saying but I would still prefer it in an experimental feature that is disabled by default.
That makes it easier to remove later if for some reason we can't commit to supporting it anymore, plus with MAS around the corner it is quite likely to get dropped from Synapse again.
I'm not against people having a SCIM API as long as they are aware of this though.

2025-01-24 12:31 UTC, reivilibre commented on docs/usage/administration/admin_api/scim_api.md
> +
I don't think this was noted on the documentation?

2025-01-24 12:31 UTC, reivilibre commented on synapse/config/experimental.py
> +class MSC4098Config:
```suggestion
class ScimConfig:
```

2025-01-24 12:31 UTC, reivilibre commented on synapse/handlers/profile.py
> +            logger.info(
```suggestion
            logger.warning(
```

2025-01-24 12:31 UTC, reivilibre commented on synapse/util/templates.py
> +def mxc_to_http(
I suspect this is no longer functional, given authenticated media means you can't just hotlink to media like this anymore.

2025-06-19 15:02 UTC, azmeuk commented
@reivilibre 
After all those months I finally took time to solve the remaining issues. I have more availability now so it should not take as long if there other things to do.

I hink everything should be solved except:
- The `enable_authenticated_media` question, see the conversation.
- The `DELETE` http call is documented [here](https://github.com/element-hq/synapse/pull/17144/files#diff-476ab3f41d9a5cd864d145544ffd42f14fcfe0889de483c7b0e0e070405a6490R232). I don't know why this is not displayed by GH here.

2025-07-23 09:20 UTC, wrjlewis commented
Hey @azmeuk 

Thanks for the update. Unfortunately, we won't be able to continue work on this PR at this time for a couple of reasons:

1) We want to limit features like this in Synapse not least to reduce our maintenance burden, but mainly this category of auth work is now being directed to MAS instead, as the natural home for it.

2) Which begs the question 'what about if someone contributed this to MAS instead?'. For full transparency, in this case we see it as an enterprise-level feature and therefore again wouldn't wish to pursue it in open-souce.

Thanks very much for taking the time to develop this PR and get it to this stage - I just want to acknowledge this isn't an ideal situation to come to this conclusion at this stage and really appreciate the effort you've put in!

2025-07-23 13:26 UTC, ara4n commented
To clarify (speaking as element ceo/cto), there are three considerations here:

 * It's not clear that this should go in Synapse rather than MAS - given it's managing user identities, MAS is surely a better bet than Synapse (and would then benefit any homeserver which uses MAS).  I'm a bit confused on how we've been managing to review this for 16 months without spotting this; it feels like we might have been missing the bigger picture. 
 * That said, we barely have bandwidth at Element to maintain our own stuff right now, let alone major new features like this (especially if it's not stuff we're using in production ourselves)
 * we **don't** have any policy against accepting enterprisey PRs: instead, we take them case by case; the key question is whether we'd have the bandwidth to maintain it going forwards. If a FOSS PR conflicts with an existing proprietary product, then we'd figure out which direction we'd want to take - i.e. whether to adopt the contribution or not.

So, my recommendation here would be to maintain this out-of-tree, either in Synapse (given that's where the work has happened already), or as a third-party Synapse module, or even better to do it on MAS (although I can't guarantee that we'd have bandwidth to accept it there either. plus I guess MAS being in Rust might be an obstacle).

I can only apologise that we (I) didn't spot this back in May 2024 and warn that this might not be a feature we'd be able to merge.

2025-07-24 14:00 UTC, closed without merging

2025-07-24 15:03 UTC, azmeuk commented
Hi.
This is bad news but I understand your reasons.
@ara4n no hard feelings, @reivilibre warned me last year on #synapse-dev that it could end this way, even before I started the development.

I'll see how much work it would ask to maintain this out of synapse, but I fear this would double the maintenance burden.

I might tackle the implementation on MAS some day, but certainly not anytime soon. I would not benevolently contributing to a proprietary feature though, and on the other hand I understand that you would not be interested in paying for a feature you did not even ask in the first place. So for this to happen, this should probably be funded by someone else.