Optional whitespace support in Authorization (#1350)
element-hq/synapse pull request #17145
Opened 2024-05-02 15:28 UTC by Timshel

Fix #1350 by adding support for optional whitespace around `,`.
 
Additionally, 
- used `\s` which is more lax than the spec since `OWS` is defined as `*( SP / HTAB )`
 - Added the `X-Matrix` part to the regex ` ^X-Matrix\s+`  to make more clear what it's doing. Added it as insensitive to lower probability of issues, but since it was not checking the `X-Matrix` part before it could create issues. 
 - On the whitespace handling of this part replaced ` +` with `\s+` since the parsing appear to be more lax than the spec (which if I understand correctly mandate only one space, cf `1*SP`)

Will of course remove it if you believe it should not be included.

2024-05-02 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17145) it.</sub>

2024-05-02 15:29 UTC, Timshel commented
Concerning the CLA has no issue with signing it but would prefer to do it only if/when the PR is ready to be merged.

2024-05-07 17:35 UTC, anoadragon453 requested changes
As the spec [mentions RFC7235 explicitly](https://spec.matrix.org/v1.10/server-server-api/#request-authentication) for the format of the `Authorization` header's value, it seems that we should indeed attempt to follow it.

We need to be careful with being more lax than the spec, lest other homeserver implementations start to rely on Synapse's behaviour, and then fail when they encounter other homeservers that follow the spec to the letter.

> - Added the `X-Matrix` part to the regex ` ^X-Matrix\s+`  to make more clear what it's doing. Added it as insensitive to lower probability of issues, but since it was not checking the `X-Matrix` part before it could create issues.

Note that we already check that the value of `Authorization` starts with `X-Matrix` (case-sensitive) here:
    
https://github.com/element-hq/synapse/blob/23740eaa3da94fbe2e25180376961979fc4e8cd3/synapse/federation/transport/server/_base.py#L105

Thus the case-insensitivity here won't apply unless we also make that check case-insensitive. However, as the spec doesn't allow `X-Matrix` to be lowercase, I think we should keep the check case-sensitive.

> - On the whitespace handling of this part replaced ` +` with `\s+` since the parsing appear to be more lax than the spec (which if I understand correctly mandate only one space, cf `1*SP`)

[RFC5234](https://www.rfc-editor.org/rfc/rfc5234) defines `SP` as `%x20`, aka hexadecimal `20`, or simply ` `. Therefore `\s`, which matches any whitespace character, is not the same. Indeed, RFC7235 mandates `1*SP`.

I also think that the spec should be updated to mention in its summary of RFC7235 that spaces and tabs are allowed around commas. This would help prevent implementations from drifting apart. I don't currently [see a relevant issue](https://github.com/matrix-org/matrix-spec/issues?q=is%3Aissue+is%3Aopen+authorization+whitespace). I can open one, unless you'd like to.

2024-05-07 17:35 UTC, anoadragon453 commented on synapse/federation/transport/server/_base.py
> +            re.split(r"^X-Matrix\s+", header_str, maxsplit=1, flags=re.IGNORECASE)[1],
```suggestion
            re.split(r"^X-Matrix +", header_str, maxsplit=1)[1],
```

2024-05-07 17:35 UTC, anoadragon453 commented on synapse/federation/transport/server/_base.py
> +            r"\s*,\s*",
`\s` typically matches the following characters:

- Space (SP)
- Tab (HT)
- Carriage return (CR)
- Line feed (LF)
- Form feed (FF)
- Vertical tab (VT)

which is more than the SP and HT defined by RFC7235. Instead, we can write:

```suggestion
        space_or_tab = "[ \t]"
        params = re.split(
            rf"{space_or_tab}*,{space_or_tab}*",
```

2024-05-07 17:40 UTC, Timshel commented on synapse/federation/transport/server/_base.py
> +            r"\s*,\s*",
Yes was not sure if it was preferred to be lax or not. 
Will change it :).

2024-05-07 17:55 UTC, Timshel commented
Hey,
Rebased and forced pushed the change since there is not much code.

>  I also think that the spec should be updated to mention in its summary of RFC7235 that spaces and tabs are allowed around commas. This would help prevent implementations from drifting apart. I don't currently [see a relevant issue](https://github.com/matrix-org/matrix-spec/issues?q=is%3Aissue+is%3Aopen+authorization+whitespace). I can open one, unless you'd like to.

I'll let you tackle this one, maybe next time :).

2024-05-08 09:52 UTC, anoadragon453 approved these changes
The code looks good to me. Spec issue written up at https://github.com/matrix-org/matrix-spec/issues/1817.

2024-05-08 10:05 UTC, Timshel commented
Had the notif for the failed test will add the changelog later today.

2024-05-08 10:52 UTC, anoadragon453 commented
Initial reactions are positive. I've made a PR to the spec to add a note about the whitespace to the summary: https://github.com/matrix-org/matrix-spec/pull/1818

2024-05-08 11:56 UTC, clokep commented on synapse/federation/transport/server/_base.py
> +            re.split(r"^X-Matrix +", header_str, maxsplit=1)[1],
Shouldn't this still only be a single space after `X-Matrix`? The tests don't look very thorough...

2024-05-08 11:59 UTC, clokep commented on synapse/federation/transport/server/_base.py
> +            re.split(r"^X-Matrix +", header_str, maxsplit=1)[1],
Never mind -- I can't read ABNF syntax. 👍

2024-05-08 12:19 UTC, anoadragon453 commented on synapse/federation/transport/server/_base.py
> +            re.split(r"^X-Matrix +", header_str, maxsplit=1)[1],
I believe the tests cover the single/multiple space after `X-Matrix` case.

There could certainly be *more* tests, I agree. Perhaps for the situations described by [MSC3029](https://github.com/matrix-org/matrix-spec-proposals/pull/4029). But those should probably live in Complement instead.

2024-05-08 13:33 UTC, anoadragon453 approved these changes

2024-05-08 13:33 UTC, anoadragon453 commented on changelog.d/17145.bugfix
> +Add support for optional whitespace around Authorization param commas
```suggestion
Add support for optional whitespace around the Federation API's `Authorization` header's parameter commas.
```

2024-05-08 13:56 UTC, merged