Bring auto-accept invite logic into Synapse
element-hq/synapse pull request #17147
Opened 2024-05-03 00:11 UTC by devonh

This PR ports the logic from the [synapse_auto_accept_invite](https://github.com/matrix-org/synapse-auto-accept-invite) module into synapse. 

I went with the naive approach of injecting the "module" next to where third party modules are currently loaded. If there is a better/preferred way to handle this, I'm all ears. It wasn't obvious to me if there was a better location to add this logic that would cleanly apply to all incoming invite events.

2024-05-03 21:05 UTC, devonh commented on synapse/handlers/profile.py
> +            ):
I don't know if this logic holds up.
If the `media_length` is `None` should we also reject the avatar change due to being unable to verify it isn't above the max size?

2024-05-03 21:21 UTC, devonh commented on synapse/handlers/profile.py
> +            ):
Also - Unsure why these unrelated linter errors popped up. Should I be fixing them in this PR?

2024-05-07 16:30 UTC, anoadragon453 requested changes
This looks good on the whole! A few minor changes but nothing fundamental.

2024-05-07 16:30 UTC, anoadragon453 commented on tests/events/test_auto_accept_invites.py
> +        )
These rooms should be made invite-only, in order to properly test the accepting functionality.

2024-05-07 16:30 UTC, anoadragon453 commented on tests/events/test_auto_accept_invites.py
> +    def test_simple_accept_invite(self) -> None:
This test case is quite long. I think you may be able to shorten it by consolidating code into a function with a signature similar to:

```python
conduct_invite_test(direct_room: bool, remote_inviter: bool, expect_auto_join: bool) -> None:
```

and then making use of the `parameterized` module to set each of these succinctly.

You may need to do something a bit different for `test_invite_from_remote_user`, where the room creator is not the same as the inviter.

2024-05-07 16:30 UTC, anoadragon453 commented on tests/events/test_auto_accept_invites.py
> +                "auto_accept_invites": {"worker_to_run_on": "account_data1"}
Shouldn't this config need `enabled: True` as well?

2024-05-07 16:38 UTC, devonh commented on docs/usage/configuration/config_documentation.md
> +* `worker_to_run_on`: Which worker to run this module on. Defaults to None (running on the main process).
Will do. Initially I didn't have them, but the config option above this follows this pattern

2024-05-07 16:42 UTC, anoadragon453 commented
I think it would make sense to archive https://github.com/matrix-org/synapse-auto-accept-invite upon merging this PR, with a note in the README to inform folks that it has been moved in-tree?

2024-05-07 18:51 UTC, devonh commented on docs/usage/configuration/config_documentation.md
> +The two modules will compete to perform the same task and may result in undesired behaviour.
Worst case this should only result in the double join events as you mentioned.

2024-05-07 21:42 UTC, devonh commented
Relies on #17166

2024-05-07 22:53 UTC, devonh commented on synapse/events/auto_accept_invites.py
I like the general idea.

Specifically, would we create a separate pyproject.toml file for each module? (ie. in `/synapse/modules/my_module/`)

And how would we go about versioning these modules?
If versioning them, would we need to remember both to update the module version itself, as well as the overall synapse dependency version?

When installing them, would we just add them to the main pyproject.toml as a path dependency? Would this be enough to ensure they are installed in each of the various docker containers, deb package, local install, etc.?

Hopefully this makes sense to you. I ran into these things while trying this out. 
These will need to be sorted out if this is to be a viable long term path forward.

2024-05-08 09:56 UTC, erikjohnston commented on synapse/events/auto_accept_invites.py
I would heavily encourage that they're not separate projects, as you lose a bunch of benefits of it being in tree (e.g. being able to use private APIs etc).

Having

2024-05-08 12:47 UTC, anoadragon453 requested changes
Some very minor requested changes now, plus a small q:

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/events/auto_accept_invites.py
Indeed, that is one of the downsides. While this code doesn't actually need any private APIs, it is inevitably handy.

I can actually add another downside. While we wouldn't end up adding to Synapse's config if we made this a module... it would beg the question of how we'd actually document the config of this module. We wouldn't be able to put it in https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html, unless we added a new section for each in-tree module... and then you've ended up making the user-visible config larger anyhow.

That leads me to think that the only benefit of keeping the modules separate would be if we ever wanted to move them out-of-tree again in future. But I think the times we'll actually do that are minimal. And if we really need to do so, then untangling it from deep within Synapse isn't _impossible_, just slightly more fiddly.

The initial reason for me suggesting that we keep this code separate is that internal code using the module API felt *weird*. But after reflection I don't think it's really an issue. It doesn't block us from modifying the API since the code is internal and can change. I also don't believe we have any assumptions in the code that all consumers of the API are external.

So all in all, I'm OK with leaving this code how it is and where it is.

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/events/auto_accept_invites.py
> +ACCOUNT_DATA_DIRECT_MESSAGE_LIST = "m.direct"
Since we're in-tree now, this can be replaced with `AccountDataTypes.DIRECT`.

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/events/auto_accept_invites.py
> +            event.type == "m.room.member"
This can be replaced with `EventTypes.Member`.

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/events/auto_accept_invites.py
> +            and event.membership == "invite"
This can be replaced with `Membership.INVITE`.

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
Should this not go in https://github.com/element-hq/synapse/pull/17166 instead? How come it was moved back to this PR?

2024-05-08 12:47 UTC, anoadragon453 commented on synapse/events/auto_accept_invites.py
>                  retries += 1
nit: this code could also just be taken out of the `try/except`.

2024-05-08 15:00 UTC, devonh commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
haha because when I put it in that PR, the linter complained about an unnecessary ignore....
So rather than fight a circle of nonsense, I feel like it's easier just to keep it here :)

2024-05-08 15:17 UTC, erikjohnston commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
I'm a bit cautious about introducing more `ignore` for types without trying to spend some time in understanding what has happened.  By the looks of it the type inference has failed somehow, so am wondering if we've managed to introduce a loop in the typing maybe?

2024-05-08 16:22 UTC, devonh commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
I'm pretty sure this parcitular lint is related to this issue: https://github.com/matrix-org/synapse/issues/11165
Which seems like quite the can of worms.

2024-05-09 23:35 UTC, devonh commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
For further reference, this is the only instance of using `self._media_repo.store` outside of the media_repo source.
That probably has something to do with the linter error only showing up here.

Since this code is completely unrelated to the changes in this PR, I suggest we allow the addition of the `ignore` here until the larger issue of #11165 is brought to a resolution. Adding an `ignore` keeps things in effectively the same state as before since mypy should have been treating this as an error, but it was silently ignoring it. At least with the `ignore` added, now the issue is explicit and visible.

2024-05-15 00:07 UTC, devonh commented on synapse/handlers/sso.py
> +                    media = await self._media_repo.store.get_local_media(media_id)  # type: ignore[has-type]
The type is generic & is specified:
https://github.com/element-hq/synapse/blob/68dca8076fd992d3dc59c38287ab6183a073874d/synapse/app/homeserver.py#L84
https://github.com/element-hq/synapse/blob/68dca8076fd992d3dc59c38287ab6183a073874d/synapse/app/generic_worker.py#L166
https://github.com/element-hq/synapse/blob/68dca8076fd992d3dc59c38287ab6183a073874d/synapse/app/admin_cmd.py#L113

All of which also have an explicit type ignore on them.
I can't seem to come up with any annotation that would make mypy happy - maybe someone else knows a way, but this seems like a much deeper issue around DataStore typing.

2024-05-17 18:23 UTC, MatMaul commented
What is the rationale for moving a feature that is easily concealed in a module, and seems to work fine that way, into synapse?

Is it mainly because of the deployment burden, with docker for example?

2024-05-17 19:26 UTC, devonh commented
> What is the rationale for moving a feature that is easily concealed in a module, and seems to work fine that way, into synapse?
> 
> Is it mainly because of the deployment burden, with docker for example?

That is definitely part of the reason. 
The overall rationale is to bring something that provides generally useful functionality into synapse proper.

This allows us to:
- make deployment easier (as you mentioned)
- make maintenance & testing easier

It's a very fine line as to what should be in a module vs. in synapse itself.
We made the decision that this functionality has become generally useful enough that it should now be moved directly within synapse.

2024-05-20 11:08 UTC, anoadragon453 approved these changes
This LGTM, thanks!

2024-05-20 11:08 UTC, anoadragon453 commented on changelog.d/17147.feature
> +Bring auto-accept invite logic into Synapse.
I think it'd be good to link to the documentation so sysadmins know how to try out the new functionality. Something like the following?

```suggestion
Add the ability to auto-accept invites on the behalf of users. See the [`auto_accept_invites`](https://element-hq.github.io/synapse/v1.108/usage/configuration/config_documentation.html#registrations_require_3pid) config option for details.
```

2024-05-21 20:09 UTC, merged