Update admin_faq.md
element-hq/synapse pull request #17171
Opened 2024-05-08 22:09 UTC by ll-SKY-ll

debian 12 uses libjemalloc2

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-05-08 22:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17171) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17171) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17171) it.</sub>

2024-05-09 09:45 UTC, anoadragon453 requested changes
[Indeed it does](https://packages.debian.org/bookworm/amd64/libjemalloc2/filelist), thank you!

Before we can merge this commit, can you sign off on your changes such that we can include this in the repository? The button in [this comment above](https://github.com/element-hq/synapse/pull/17171#issuecomment-2101585287) will let you do so.

As part of our contribution process, we also require a [changelog entry](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). In the case of this PR, this would take the form of a file at `changelog.d/17171.doc` with text that describes the change you made. Something like:

```
Update the Admin FAQ with the current libjemalloc version for latest Debian stable.
```

Thank you!

2024-05-09 10:19 UTC, ll-SKY-ll commented
> [Indeed it does](https://packages.debian.org/bookworm/amd64/libjemalloc2/filelist), thank you!
> 
> Before we can merge this commit, can you sign off on your changes such that we can include this in the repository? The button in [this comment above](https://github.com/element-hq/synapse/pull/17171#issuecomment-2101585287) will let you do so.
> 
> As part of our contribution process, we also require a [changelog entry](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). In the case of this PR, this would take the form of a file at `changelog.d/17171.doc` with text that describes the change you made. Something like:
> 
> ```
> Update the Admin FAQ with the current libjemalloc version for latest Debian stable.
> ```
> 
> Thank you (and nice PR number btw)!

hi, sorry its my first time doing anything on github :) I just happen to optimize my server and stumbled across these errors in the docs so i wanted to update them :) 

I included the update of the workers.md where the name of a stream was different in the text as compared to the headline (where it was correct) leading to a invalid homeserver.yaml for me when i tried to started synapse with the wrong stream name.

I also updated the changelog file again to also include a description of this change :) i hope everything is right now.

2024-05-09 10:48 UTC, anoadragon453 approved these changes
Just a small adjustment to the changelog to make it fit the guidelines, otherwise looks good to me! Thanks for making the other fix as well.

2024-05-09 10:48 UTC, anoadragon453 commented on changelog.d/17171.doc
> +Update name of the "push_rules" stream in docs/workers.md
```suggestion
Update the Admin FAQ with the current libjemalloc version for latest Debian stable. Additionally update the name of the "push_rules" stream in the Workers documentation.
```

2024-05-09 10:50 UTC, merged