Support MSC3916 by adding a federation `/download` endpoint
element-hq/synapse pull request #17172
Opened 2024-05-08 22:38 UTC by H-Shay

[MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) outlines the addition of a new federation endpoint to serve media downloads to other servers. This PR implements that endpoint and the new `multipart/form-data` response format that it returns. Future PRs will implement the rest of MSC3916, including altering the new client-server `/download` endpoint to use the new federation endpoint for remote download requests. 

Should be reviewable commit-by-commit

2024-05-08 22:44 UTC, H-Shay commented on synapse/federation/transport/server/_base.py
> +                                func.__self__.__class__.__name__  # type: ignore
I wasn't sure if it made more sense to special case, as I have done here, or start passing in the request to all the other endpoints (which won't use it) - thoughts appreciated.

2024-05-08 22:47 UTC, H-Shay commented on synapse/media/media_storage.py
> +            )
Note that until [MSC3911](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/proposal/linking_media_to_events/proposals/3911-linking-media-to-events.md) is implemented, we will always just send an empty JSON body, as is indicated here

2024-05-08 22:48 UTC, H-Shay commented
Does this require more tests? If so, what should be tested?

2024-05-09 00:55 UTC, H-Shay commented
complement run failing with `CreateDirtyDeployment failed: CreateDirtyServer: Failed to deploy image complement-synapse : Error response from daemon: Conflict. The container name "/complement_fed_dirty_hs1" is already in use by container "08dc1e60340dfb37e078f29731cb4d102e1149a6afb2f5f62fc41564fd9caeac". You have to remove (or rename) that container to be able to reuse that name.` - pretty sure that's not this PR? Normally I would just hit the re-run button but I no longer have that power...

2024-05-09 14:37 UTC, anoadragon453 commented
> complement run failing with `CreateDirtyDeployment failed: CreateDirtyServer: Failed to deploy image complement-synapse : Error response from daemon: Conflict. The container name "/complement_fed_dirty_hs1" is already in use by container "08dc1e60340dfb37e078f29731cb4d102e1149a6afb2f5f62fc41564fd9caeac". You have to remove (or rename) that container to be able to reuse that name.` - pretty sure that's not this PR? Normally I would just hit the re-run button but I no longer have that power...

I think that error is a red herring. In the Synapse logs, I'm [seeing](https://github.com/element-hq/synapse/actions/runs/9009615790/job/24774465807?pr=17172#step:7:12914) the following exception:

```
  Error during startup:
  Traceback (most recent call last):
  pusher1 | 2024-05-09 12:22:43,513 - synapse.replication.tcp.redis - 292 - INFO - sentinel - Connecting to redis server localhost:6379
    File "/usr/local/lib/python3.11/site-packages/synapse/app/_base.py", line 258, in wrapper
      await cb(*args, **kwargs)
    File "/usr/local/lib/python3.11/site-packages/synapse/app/_base.py", line 594, in start
      hs.start_listening()
    File "/usr/local/lib/python3.11/site-packages/synapse/app/generic_worker.py", line 247, in start_listening
      self._listen_http(listener)
    File "/usr/local/lib/python3.11/site-packages/synapse/app/generic_worker.py", line 187, in _listen_http
      resources[FEDERATION_PREFIX] = TransportLayerServer(self)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/synapse/federation/transport/server/__init__.py", line 75, in __init__
      self.register_servlets()
    File "/usr/local/lib/python3.11/site-packages/synapse/federation/transport/server/__init__.py", line 78, in register_servlets
      register_servlets(
    File "/usr/local/lib/python3.11/site-packages/synapse/federation/transport/server/__init__.py", line 318, in register_servlets
      servletclass(
    File "/usr/local/lib/python3.11/site-packages/synapse/federation/transport/server/federation.py", line 812, in __init__
      self.media_repo = self.hs.get_media_repository()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/synapse/server.py", line 220, in _get
      dep = builder(self)
            ^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/synapse/server.py", line 686, in get_media_repository
      return MediaRepository(self)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/synapse/media/media_repository.py", line 92, in __init__
      self.max_upload_size = hs.config.media.max_upload_size
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'ContentRepositoryConfig' object has no attribute 'max_upload_size'
```

The error about conflicting containers is certainly unhelpful though...

2024-05-09 17:31 UTC, H-Shay commented
Weird! If it's an attribute error why did only one of the three complement tests fail? Don't they use the same image? I'm gonna dig deeper but I'm surprised...

2024-05-13 13:53 UTC, anoadragon453 commented on synapse/media/storage_provider.py
> +    async def fetch(
Is this changing an external API? https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#media_storage_providers

2024-05-13 21:37 UTC, H-Shay commented on synapse/media/storage_provider.py
> +    async def fetch(
This is somewhat unclear to me - I couldn't tell from the config documentation what defines a `media_storage_provider` - looking at the code that parses the config it uses the [`load_module`](https://github.com/element-hq/synapse/blob/038b9ec59a5d2080372aa4b7684e7b6580a79bd8/synapse/util/module_loader.py#L33) function which loads a Synapse module, and there is a Synapse module `FileStorageProvderBackend` that exists in Synapse. Nothing in the docs/module docs mentioned anything about third-party storage providers so I figured it was not an external thing, but I could be wrong? Any insight is appreciated

2024-05-13 21:39 UTC, H-Shay commented on synapse/federation/transport/server/federation.py
> +    a multipart/form-data response consisting of a JSON object and the requested media
Per the discussion here it was changed to `multipart/form-data`: https://github.com/matrix-org/matrix-spec-proposals/pull/3916#discussion_r1320678847

2024-05-13 21:39 UTC, H-Shay commented on synapse/media/media_storage.py
> +        consumer is passed to the callback.
It's just the last byte.

2024-05-13 21:48 UTC, H-Shay commented on synapse/media/media_storage.py
> +        return deferred
I wondered that as well, the original implementation in the Twisted `FileSender.beginFileTransfer` is:
```
self.deferred = deferred = defer.Deferred()
self.consumer.registerProducer(self, False)
return deferred
```
which explicitly assigns `self.deferred` to a var and returns the var. I couldn't use the code above exactly because mypy needed a type annotation on `self.deferred` so I added the annotation and kept the variable assignment - mostly my reasoning to follow the form of the twisted code was keeping chesterton's fence in mind - I don't know why they did it that way in the first place so I was reluctant to change it.

2024-05-13 22:01 UTC, H-Shay commented on synapse/media/media_storage.py
> +    def resumeProducing(self) -> None:
I've added some comments and spaces, let me know if it's better (sorry I think I had spent too much time staring at Twisted code).

2024-05-13 22:02 UTC, H-Shay commented on synapse/media/media_storage.py
> +            self.consumer.write(CRLF + b"--" + self.boundary + b"" + CRLF)
I think you are correct that they are unnecessary, I suspect they are a remnant of an earlier iteration - I've removed them.

2024-05-14 11:19 UTC, anoadragon453 requested changes
Nearly there! Just a few small things now.

2024-05-14 11:19 UTC, anoadragon453 commented on synapse/media/storage_provider.py
> +    async def fetch(
Hrm, indeed the docs don't provide much insight here.

https://github.com/matrix-org/synapse-s3-storage-provider/ is an external storage provider that is widely used (including on matrix.org), and does implement this method: https://github.com/matrix-org/synapse-s3-storage-provider/blob/2c46a764f700e6439afa11c00db827ddf21a9e89/s3_storage_provider.py#L136-L148. This change would cause a `TypeError` in that library.

What we've done in the past for the Module API in this situation is to either:

1. Define a new function with the new arguments, i.e. `fetch_with_media_info`.
2. Check the parameter count of the module's implementation of the function, and add arguments accordingly. [Module API example](https://github.com/element-hq/synapse/blob/e161103b46e9e85b95575ad12b34eb7ec570e0a4/synapse/module_api/callbacks/spamchecker_callbacks.py#L266-L294), [another example](https://github.com/element-hq/synapse/blob/b7af076ab524c018992a05b031cd8e3533ab59d4/synapse/handlers/oidc.py#L428-L436). Note that you don't need to define an `async_wrapper` - that was backwards-compatibility from the time before we had `async` functions everywhere.

2 is probably cleaner from an external perspective.

We'll should also add a note to the changelog signalling to media storage provider module authors that they can take advantage of the enhanced metadata.

2024-05-14 11:19 UTC, anoadragon453 commented on synapse/media/storage_provider.py
> +    async def fetch(
I've created an issue to document this at https://github.com/element-hq/synapse/issues/17193

2024-05-14 11:19 UTC, anoadragon453 commented on tests/federation/test_federation_media.py
> +    def test_file_download(self) -> None:
Can you add some newlines to this code please? /me blames :tornado:

2024-05-14 19:47 UTC, H-Shay commented on synapse/media/storage_provider.py
> +    async def fetch(
Ah that complicates things - the `federation` parameter that I have added does change the form of the response from `fetch`, which is responsible for streaming the file to the consumer. In the code I've added, if the `federation` parameter is `True`, fetch will stream the multipart response, rather than just the file as it did previously. So I don't think?? that we can just drop the parameter if the provider doesn't support it, otherwise the response could be incorrect. I guess in that case adding a new function would be the best way forward, although AFAICT that means that third-party storage modules will be incompatible with MSC3916 until they implement the new function supporting a multipart response.

2024-05-14 19:52 UTC, H-Shay commented on synapse/media/storage_provider.py
> +    async def fetch(
How have things like this been handled in the past, as it seems like we need to change the behavior of an external entity, since there are external storage providers and the storage provider is responsible for streaming the response?

2024-05-14 20:39 UTC, H-Shay commented on synapse/media/_base.py
> +            return
So the code for this was adapted from [`respond_with_responder`](https://github.com/element-hq/synapse/blob/68dca8076fd992d3dc59c38287ab6183a073874d/synapse/media/_base.py#L263) which also contains the disconnect code - I figured it was there for a reason and didn't remove it.

2024-05-14 22:45 UTC, H-Shay commented
It seems very unlikely to me that the sytest failure is a result of the last round of changes as I only added a test, newlines, and a comment...

2024-05-14 22:47 UTC, H-Shay commented on synapse/media/storage_provider.py
> +    async def fetch(
the more I think about this the more I am concerned that this is a significant problem

2024-05-14 22:57 UTC, H-Shay commented on synapse/federation/transport/server/_base.py
> +                                func.__self__.__class__.__name__  # type: ignore
I've opened https://github.com/element-hq/synapse/issues/17196, let me know if that makes sense

2024-05-15 16:25 UTC, anoadragon453 reviewed
> It seems very unlikely to me that the sytest failure is a result of the last round of changes as I only added a test, newlines, and a comment...

Looks like a flake. I've re-ran the tests.

2024-05-17 09:52 UTC, erikjohnston commented on synapse/media/_base.py
> +            b"Content-Type", b"multipart/form-data; boundary=%s" % responder.boundary
This should `multipart/mixed` I think?

2024-05-17 10:08 UTC, anoadragon453 commented on synapse/media/_base.py
> +            b"Content-Type", b"multipart/form-data; boundary=%s" % responder.boundary
I had the same question :) https://github.com/element-hq/synapse/pull/17172#discussion_r1596609583

It's in the process of being changed. @H-Shay it would reduce reviewer confusion to get that bit updated in the MSC.

2024-05-17 17:29 UTC, turt2live commented on synapse/media/_base.py
> +            b"Content-Type", b"multipart/form-data; boundary=%s" % responder.boundary
sorry, looks like the MSC thread isn't clear - it should be `multipart/mixed` for now.

2024-06-05 19:28 UTC, H-Shay commented on synapse/media/_base.py
> +            b"Content-Type", b"multipart/form-data; boundary=%s" % responder.boundary
sorted now, thanks for clarifying :)

2024-06-05 19:30 UTC, H-Shay commented on synapse/media/storage_provider.py
> +    async def fetch(
Per the discussion elsewhere I have gated exposing the new federation `/download` endpoint on whether the StorageProvider supports the new `fetch` behavior

2024-06-05 20:15 UTC, H-Shay commented
Sytest failure on multi-postgres seem unrelated? I can't kick it but I suspect a re-run would solve them..

2024-06-05 22:26 UTC, H-Shay commented
Updated to reflect that new version of MSC removes `server_name` from the endpoint.

2024-06-06 10:47 UTC, anoadragon453 requested changes
This looks pretty solid to me! A couple tiny notes, and then I think this is good to go.

2024-06-06 10:47 UTC, anoadragon453 commented on synapse/federation/transport/server/__init__.py
> +                        load_download_endpoint = False
nit: there could be a `break` here to avoid checking further storage provider implementations when one is already incompatible.

2024-06-06 10:47 UTC, anoadragon453 commented on synapse/federation/transport/server/__init__.py
> +                            "provider is not compatible with this endpoint."
it would be nice to mention the classname of the storage provider which isn't compatible, so the sysadmin knows which repo to make an issue on :)

2024-06-06 10:47 UTC, anoadragon453 commented on synapse/federation/transport/server/__init__.py
> +                            "Federation `/download` enpoint will not be enabled as your storage "
```suggestion
                            "Federation media `/download` endpoint will not be enabled as your storage "
```

2024-06-07 12:54 UTC, anoadragon453 approved these changes

2024-06-07 12:54 UTC, merged