Fix hierarchy returning 403 when room is accessible through federation
element-hq/synapse pull request #17194
Opened 2024-05-14 16:59 UTC by kfiven

### Pull Request Checklist

Fixes #17143

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-05-22 10:06 UTC, erikjohnston reviewed
Hi, thanks for this. Could you add a unit test and/or a complement test please?

2024-07-31 06:48 UTC, kfiven commented
Hi, added one, could you re-run the workflow?

2024-08-05 15:00 UTC, williamkray commented
@erikjohnston i am also interested in seeing this merged, as it's now impacting users with the latest cinny rollout which depends on the /hierarchy call to work properly.

2024-08-07 14:08 UTC, anoadragon453 requested changes
Thanks for the fix and for adding a test!

A small request below, otherwise this LGTM.

2024-08-07 14:08 UTC, anoadragon453 commented on synapse/handlers/room_summary.py
> +                )
I don't think this logic is needed as the room details will be fetched over federation and user access will be checked below.

2024-08-08 02:24 UTC, kfiven commented on synapse/handlers/room_summary.py
> +                )
This condition raise error if room is not accessible through federation, if we remove this condition below code won't error and instead return an empty array as rooms result

2024-08-14 09:59 UTC, anoadragon453 commented on synapse/handlers/room_summary.py
> +                )
Ah I see, indeed you're correct. We could move this logic into the below code to avoid another call to `self._summarize_remote_room_hierarchy`, but calls to that method are [cached](https://github.com/element-hq/synapse/blob/anoa/media_threadpool_metrics/synapse/federation/federation_client.py#L1636-L1638) anyways, so it's not an issue.

2024-08-27 13:53 UTC, kfiven commented on synapse/handlers/room_summary.py
> +            if not root_room_entry or not await self._is_remote_room_accessible(
@anoadragon453 I have changed it to return 500 when root_room_entry is none.

2024-08-28 13:04 UTC, anoadragon453 approved these changes
Looks good to me, thanks for sticking with it!

I'm going to apply the outstanding suggestions and then merge.

2024-08-28 13:24 UTC, anoadragon453 commented
It appears that `tests.handlers.test_room_summary.SpaceSummaryTestCase.test_visibility` is now failing after https://github.com/element-hq/synapse/pull/17194/commits/2cb414d4821cbaf5cd58bc2c3ba46d606028573d.

This is because of this line expecting a `403`:

https://github.com/kfiven/synapse/blob/70e92ff970bdcddbeb9bf844d516da64edbe0631/tests/handlers/test_room_summary.py#L330-L336

I think we should instead receive a `404` in this case, given that 404 is [defined for `GET /_matrix/federation/v1/hierarchy/{roomId}`](https://spec.matrix.org/v1.11/server-server-api/#get_matrixfederationv1hierarchyroomid).

But fixing that feels out of scope for this PR. So, let's just revert https://github.com/element-hq/synapse/pull/17194/commits/2cb414d4821cbaf5cd58bc2c3ba46d606028573d for now and save returning a 404 instead for a separate PR.

2024-08-28 14:45 UTC, merged