Add support for MSC3823 - Account Suspension Part 2
element-hq/synapse pull request #17255
Opened 2024-05-31 18:41 UTC by H-Shay

This PR builds on #17051 to add support for [MSC3823](https://github.com/matrix-org/matrix-spec-proposals/pull/3823) - Account suspension. 

This PR:
- prevents suspended users from sending messages, changing profile data, and redacting messages other than their own
- adds an admin API endpoint to set/unset suspended status for a user
- adds an experimental config option to enable account suspension

2024-06-05 13:08 UTC, reivilibre requested changes
This is all reasonable, sorry it stuck around in the queue

2024-06-05 13:08 UTC, reivilibre commented on synapse/rest/admin/users.py
> +    PATTERNS = admin_patterns("/suspend/(?P<target_user_id>[^/]*)$")
would you mind adding a docstring that just shows an example request and lists the fields in the request body and in the response body?

Either way this is useful when skimming the code, but other than that I would normally say this should go in the docs, but I guess we don't normally document experimental features

edit: if you have a `PutBody` thing as described later, then showing a list of the fields isn't important anymore because it's self-documenting

2024-06-05 13:08 UTC, reivilibre commented on synapse/rest/admin/users.py
> +        await self.store.set_user_suspended_status(target_user_id, suspend)
I know the migration for this never fully happened, but I can't resist thinking it'd be nice to use the Pydantic models here.

One concern I see here is that under SQLite, someone could pass in a non-bool value here and we would just insert that.

If you look around the codebase for examples of `PutBody` you should see examples of how to do this — note you want to use `StrictBool` for `bool`.

Also note that the imports for Pydantic are a bit awkward currently; look around for examples but you need to support two versions e.g. 

```python
if TYPE_CHECKING or HAS_PYDANTIC_V2:
    from pydantic.v1 import StrictBool, StrictStr, constr
else:
    from pydantic import StrictBool, StrictStr, constr
```

If this takes too long / is too painful then sure just add a type check for whether `suspend` is a bool or not.

2024-06-05 22:17 UTC, H-Shay commented on synapse/handlers/message.py
> +        if event_dict["type"] == EventTypes.Message:
Per the [MSC](https://github.com/Yoric/matrix-doc/blob/yoric/errcode-suspended/proposals/3823-code-for-account-suspension.md) there is a fairly long list of what is permitted vs a shorter list of what is not permitted, which is why I focused on what is not permitted.

2024-06-05 22:30 UTC, H-Shay commented on synapse/handlers/message.py
> +            if requester_suspended:
I don't know much about puppeted accounts - Can a user access an account that is being puppeted?

2024-06-06 17:52 UTC, H-Shay commented on synapse/rest/client/profile.py
> +            )
If I understand correctly changing the profile entails using a join event? If so these were already prohibited in the previous [PR](https://github.com/element-hq/synapse/pull/17051).

2024-06-07 15:16 UTC, reivilibre commented on synapse/handlers/message.py
> +            if requester_suspended:
'Puppeted' here only means that a server admin logged in to the user using the Admin API. https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html?highlight=login%20as%20user#login-as-a-user

Whilst it's the puppeted user that is being made to send the events and stuff, it's a trusted admin who is actually pulling the strings. So it seems logical that there'd be no need to apply any suspensions there?

2024-06-07 15:16 UTC, reivilibre commented on synapse/rest/admin/users.py
> +        await self.store.set_user_suspended_status(target_user_id, suspend)
That's perfect, thanks

2024-06-07 15:17 UTC, reivilibre commented on synapse/rest/client/profile.py
> +            )
ah OK great then!

2024-06-07 15:18 UTC, reivilibre commented on synapse/handlers/message.py
> +        if event_dict["type"] == EventTypes.Message:
sure. Worst case, we can always make this stricter later

2024-06-07 15:21 UTC, reivilibre commented on synapse/handlers/message.py
> +            if requester_suspended:
I think Requester.`authenticated_entity` is what you want to read to see if a user is being puppeted or not. There should be quite a bit of example code around if it's not clear from the documentation on that

2024-06-07 15:21 UTC, reivilibre requested changes
The puppeting thing is a nice-to-have, but it also feels sufficiently nice to have that it's probably worth doing whilst we're in the zone for this, but if it's somehow hard then I'm fine to merge as-is.

2024-06-12 15:23 UTC, H-Shay commented on synapse/handlers/message.py
> +            if requester_suspended:
Right I checked in with the team during our sync today and posed the question about puppeting - the consensus is we'd like to merge it as is, and possibly follow up with that change in the future depending on the feedback from the original work.

2024-06-21 18:36 UTC, reivilibre commented on synapse/handlers/message.py
> +            if requester_suspended:
Sure, that can probably wait until later, it shouldn't break anyone since you have to choose to use the experimental feature first.

2024-06-21 18:36 UTC, reivilibre approved these changes

2024-06-21 19:01 UTC, reivilibre approved these changes

2024-06-21 21:31 UTC, H-Shay commented
I've fixed the merge conflict, can you hit merge on this? I am no longer empowered...

2024-06-24 13:21 UTC, merged

2024-12-07 12:57 UTC, aine-etke commented
Hello,

I'm working on https://github.com/etkecc/synapse-admin/pull/195 to support that feature in Synapse Admin, and currently (at the moment of writing using the `develop` Synapse docker tag) the following things are unclear:
* will the `suspended` be supported as one of the [List Accounts](https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts) params and response keys?
* will the `suspended` be supported as one of the [Query User Account](https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html#query-user-account) response keys?
* will the `suspended` be supported as one of the [Create or Modify Account](https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account) body params?

Would you mind clarifying that, please?

Thank you in advance!

2024-12-09 10:26 UTC, anoadragon453 commented
Hi @aine-etke!

So far we haven't added the ability to query a user's suspended status to any Admin APIs, and I'm not aware of any plans to. I'd recommend [creating a new feature request issue](https://github.com/element-hq/synapse/issues/new?assignees=&labels=&projects=&template=FEATURE_REQUEST.md) asking for this functionality, and cc'ing `@element-hq/trust-safety` for their plans; as they were the original drivers of this work.

As this PR has been merged for ~6mo, it's unlikely to get many more responses :slightly_smiling_face:

2024-12-09 12:49 UTC, aine-etke commented
Thank you, @anoadragon453, created https://github.com/element-hq/synapse/issues/18016, but unfortunately, I can't tag the mentioned team. Would you mind adding a comment with cc to that new issue, if you have permissions, please?

2024-12-09 17:23 UTC, H-Shay commented
Note that some support for querying the suspended status landed here: https://github.com/element-hq/synapse/pull/17952. Support for the others is forthcoming but I can't give a timeline currently - it is on our radar, though.