Filter added to Admin-API GET /rooms
element-hq/synapse pull request #17276
Opened 2024-06-06 14:22 UTC by afechler

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-06-07 12:57 UTC, dklimpel commented on synapse/rest/admin/rooms.py
> +            print(e)
It is not clear to me what the exception is supposed to do here and where the output should be. Wouldn't a `SynapseError` and a log output make more sense?

2024-06-07 12:57 UTC, dklimpel commented on docs/admin_api/rooms.md
> +* `filter_empty_rooms` - Flag to filter empty and non-empty rooms. A room is empty if joined_members is zero.
As a user, it is not really clear to me what is meant here. The documentation in the code is more meaningful.
Precisely because the bools have three states, since `None` is apparently not equal to `false` or `true`.

2024-06-10 11:19 UTC, anoadragon453 requested changes
Overall this looks useful, thank you!

I agree with @dklimpel's review and have a couple more comments to add.

2024-06-10 11:19 UTC, anoadragon453 commented on synapse/storage/databases/main/room.py
> +              INNER JOIN rooms USING (room_id)
We can `EXPLAIN ANALYZE` the query on a sizeable Matrix deployment, such as matrix.org.

Running the following query:

```sql
EXPLAIN ANALYZE SELECT count(*) FROM (
    SELECT room_id FROM room_stats_state state
    INNER JOIN room_stats_current curr USING (room_id)
    INNER JOIN rooms USING (room_id)
    WHERE LOWER(state.name) LIKE '%hello%'
        OR LOWER(state.canonical_alias) LIKE '%hello%'
        OR state.room_id = '!xyz:domain.com'
) AS get_room_ids;
```

which gives us:

```


                                                                                    QUERY PLAN                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=248961.11..248961.12 rows=1 width=8) (actual time=708.339..714.750 rows=1 loops=1)
   ->  Gather  (cost=248960.90..248961.11 rows=2 width=8) (actual time=708.028..714.726 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=247960.90..247960.91 rows=1 width=8) (actual time=687.989..687.991 rows=1 loops=3)
               ->  Nested Loop  (cost=1.12..247930.10 rows=12320 width=0) (actual time=8.294..687.832 rows=658 loops=3)
                     Join Filter: (state.room_id = curr.room_id)
                     ->  Nested Loop  (cost=0.56..240275.86 rows=12320 width=62) (actual time=8.262..682.422 rows=658 loops=3)
                           ->  Parallel Seq Scan on room_stats_state state  (cost=0.00..212549.39 rows=12320 width=31) (actual time=8.210..676.798 rows=658 loops=3)
                                 Filter: ((lower(name) ~~ '%hello%'::text) OR (lower(canonical_alias) ~~ '%hello%'::text) OR (room_id = '!xyz:domain.com'::text))
                                 Rows Removed by Filter: 3097391
                           ->  Index Only Scan using rooms_pkey on rooms  (cost=0.56..2.25 rows=1 width=31) (actual time=0.008..0.008 rows=1 loops=1975)
                                 Index Cond: (room_id = state.room_id)
                                 Heap Fetches: 212
                     ->  Index Only Scan using room_stats_current_pkey on room_stats_current curr  (cost=0.56..0.61 rows=1 width=31) (actual time=0.007..0.007 rows=1 loops=1975)
                           Index Cond: (room_id = rooms.room_id)
                           Heap Fetches: 1144
 Planning Time: 0.830 ms
 JIT:
   Functions: 38
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 2.227 ms, Inlining 0.000 ms, Optimization 0.961 ms, Emission 22.621 ms, Total 25.808 ms
 Execution Time: 715.623 ms
(23 rows)
```

(Note that I only analyzed after ensuring that a bare `EXPLAIN` would not be too costly.)

This is indeed fairly slow, and takes up a connection for nearly a whole second. As these filters are only using data from `room_stats_state_current`, do we really need the second `INNER JOIN rooms USING (room_id)`?

2024-06-10 15:25 UTC, afechler commented on synapse/rest/admin/rooms.py
> +            print(e)
My fault. I had only used the code fragment during development. I remove the exception handling.

2024-06-10 15:46 UTC, afechler commented on docs/admin_api/rooms.md
> +* `filter_empty_rooms` - Flag to filter empty and non-empty rooms. A room is empty if joined_members is zero.
I have adjusted the parameter names and descriptions.

2024-06-10 16:11 UTC, afechler commented on synapse/storage/databases/main/room.py
> +              INNER JOIN rooms USING (room_id)
I based the implementation on existing code (e.g. get_users_paginate_txn) The second join is used to determine the number of public or non-public rooms in the case of filtering. Perhaps it is also possible to determine the state of the flag via the events, but I would assume that this is not faster.

2024-06-10 16:27 UTC, afechler commented on synapse/storage/databases/main/room.py
> +        filter_ = []
I see, but filter is also a build-in function and that's why i orientated myself on pep 8 (...single_trailing_underscore_: used by convention to avoid conflicts with Python keyword...)

2024-06-10 16:31 UTC, afechler commented on changelog.d/17276.feature
> +Filter for public and empty rooms added to Admin-API [List Room API](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#list-room-api).
I have adjusted the link.

2024-06-17 13:34 UTC, anoadragon453 commented on synapse/storage/databases/main/room.py
> +        filter_ = []
Oh, TIL! We strive to remain compliant with PEP 8, so that's alright then (and I should clearly re-read it).

2024-06-19 10:45 UTC, anoadragon453 approved these changes
Thanks for the changes. This now LGTM!

2024-06-19 10:45 UTC, merged