Add report room API (MSC4151)
element-hq/synapse pull request #17270
Opened 2024-06-05 16:52 UTC by turt2live

https://github.com/matrix-org/matrix-spec-proposals/pull/4151

This is intended to be enabled by default for immediate use. When FCP is complete, the unstable endpoint will be dropped and stable endpoint supported instead - no backwards compatibility is expected for the unstable endpoint.

2024-06-05 17:36 UTC, turt2live commented
Tested manually too:

```
$ curl -s -X POST -H "Authorization: Bearer ${token}" --data-binary '{"reason":"I am not a fan"}' 'https://t2l.io/_matrix/client/unstable/org.matrix.msc4151/rooms/!OGEhHVWSdvArJzumhm:matrix.org/report'
{}
```

```
t2lsynapse_c=# select * from room_reports;
 id |  received_ts  |            room_id             |    user_id     |     reason     |           content
----+---------------+--------------------------------+----------------+----------------+-----------------------------
  2 | 1717608891741 | !OGEhHVWSdvArJzumhm:matrix.org | @travis:t2l.io | I am not a fan | {"reason":"I am not a fan"}
(1 row)
```

2024-06-10 17:09 UTC, turt2live commented
fyi: this needs to be deployed to matrix.org ~this week, before Friday.

2024-06-10 17:24 UTC, reivilibre requested changes
Looks sane overall

2024-06-10 17:24 UTC, reivilibre commented on synapse/rest/client/reporting.py
> +
if you can, prefer to use a `PostBody` for parsing the JSON body. Good example for doing this is [`4b4180b` (#17255)](https://github.com/element-hq/synapse/pull/17255/commits/4b4180bba5cb069b1c87d2bc3dd95dcca3510e27) — but use `StrictStr` so that no funny type coercion goes on.

That alleviates you from checking its type and its presence yourself

2024-06-10 17:29 UTC, turt2live commented on synapse/rest/client/reporting.py
> +    ReportRoomRestServlet(hs).register(http_server)
I was hoping to avoid this given the MSC is (currently) 3 checkboxes away from FCP, so the unstable flag might disappear within a single release cycle.

We also believe on T&S that this API *should* be enabled by default.

2024-06-11 17:26 UTC, turt2live commented on synapse/rest/client/reporting.py
> +            content=body,
From brief discussions elsewhere, it sounds like we can drop `content` from the schema. We don't use its partner field on `event_reports`, so can drop it starting with new APIs. 

When we replace reporting in Matrix, we can fix `event_reports`.

2024-06-11 19:04 UTC, turt2live commented on synapse/rest/client/reporting.py
> +
I have no idea what I'm doing here and copy/pasted a bunch of code. Hopefully it's all correct - let me know 😅

2024-06-11 19:04 UTC, turt2live commented on synapse/rest/client/reporting.py
> +    ReportRoomRestServlet(hs).register(http_server)
(flag added, hopefully temporarily)

2024-06-12 09:33 UTC, sandhose approved these changes

2024-06-12 09:33 UTC, sandhose commented on tests/rest/client/test_reporting.py
> +        self.admin_user_tok = self.login("admin", "pass")
This doesn't seem to be used

```suggestion
```

2024-06-12 09:48 UTC, sandhose commented on synapse/rest/client/reporting.py
> +        "/org.matrix.msc4151/rooms/(?P<room_id>[^/]*)/report$",
This doesn't match the unstable prefix (`/_matrix/client/unstable/org.matrix.msc4151/report/:roomId`) in the MSC, but I'll assume this is a problem with the MSC, not the implementation

2024-06-12 10:01 UTC, sandhose commented on synapse/rest/client/reporting.py
> +        "/org.matrix.msc4151/rooms/(?P<room_id>[^/]*)/report$",
Left a comment on the MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/4151#discussion_r1636171857

2024-06-12 10:27 UTC, merged