Support MSC4140: Delayed events (Futures)
element-hq/synapse pull request #17326
Opened 2024-06-18 21:20 UTC by AndrewFerr

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-08-05 13:56 UTC, anoadragon453 requested changes
@AndrewFerr would it be possible to break this PR up into a few more logical commits? Currently it's roughly 1 commit with >1000 lines changed, which appears daunting to review :slightly_smiling_face:

2024-08-05 13:56 UTC, anoadragon453 commented on changelog.d/17326.feature
> +Add initial implementation of delayed events as proposed by [MSC4140](https://github.com/matrix-org/matrix-spec-proposals/pull/4140).
```suggestion
Add experimental implementation of delayed events as proposed by [MSC4140](https://github.com/matrix-org/matrix-spec-proposals/pull/4140).
```

2024-08-07 03:30 UTC, AndrewFerr commented
Ironically, the reason I had squashed the commits was to try make it easier to review :upside_down_face: 

I've now split them up to isolate what should be the most relevant components of the PR.

2024-08-14 17:43 UTC, anoadragon453 requested changes
Reviewed up until https://github.com/element-hq/synapse/commit/54725883c602850f674ec482ab28155b380fab9c, hopefully this gets you started. I'm afraid I'm away for the next few days, so requesting review from the rest of the team.

2024-08-15 02:55 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    delay_id TEXT NOT NULL,
This was done to have a column that is a "pure" primary key.  Currently, `delay_id`s are non-unique across users (hence the `UNIQUE (delay_id, user_localpart)` constraint) to allow for a greater range of possible `delay_id`s per user, and to scope `delay_id` lookups to the calling user (so that even if one were to be stolen/guessed by another user, they would get a 404 when trying to use it).  This wouldn't be possible the `delay_id` alone were to be the primary key.

And it's not so much that `delay_rowid` matches `rowid` in SQLite, it's that it _is_ the `rowid`: all SQLite tables implicitly have an integer key to uniquely identify rows, and giving a table a `INTEGER PRIMARY KEY` column makes it a named alias of that key.  Best of all, as long as `INSERT`s don't mention that column (or set it to `NULL`), it gets set to an auto-generated value that's guaranteed to be unique (which is even better than an auto-incrementing column, which has to be managed for overflows).  Put together, this lets `delay_rowid` be a DB-managed primary key.

For more info, see https://www.sqlite.org/lang_createtable.html#rowid. I will add that link in the comment.

2024-08-15 02:55 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql.postgres
> +ALTER TABLE delayed_events ALTER COLUMN delay_rowid ADD GENERATED ALWAYS AS IDENTITY;
Sure. It's similar to SQLite's `rowid`, but has to be opted into.

2024-08-15 03:13 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        Params:
Ahh, this was bugging me!  Happy to learn that there's a style guide for this.

2024-08-15 03:15 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        self.room_member_handler = hs.get_room_member_handler()
Other handlers had seemingly-private attributes that weren't `_`-prefixed, so I wasn't sure what to do here.  These are definitely not meant to be used anywhere else, so I will go ahead and rename these.

2024-08-15 03:19 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                May only refer to a delayed event that has no parent itself.
No it isn't; I'll add a comment.

2024-08-15 03:21 UTC, AndrewFerr commented on synapse/rest/client/room.py
> +        parent_id = parse_string(request, "org.matrix.msc4140.parent_delay_id")
Sure.  I included them to avoid having to bump the DB schema again if they were to be included later, and to work with clients that support them; but if getting the parent behaviour reviewed will slow down this PR, I'll strip them out.

2024-08-15 03:23 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        parent_id: Optional[str],
Yes, delays & parent relations are compatible with each other.

2024-08-15 03:24 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        # TODO: Validate that the event is valid before scheduling it
They do get validated at send time, but this comment refers to checking that the event content itself isn't malformed, lest someone schedules an event that is doomed to fail no matter what.  This is handled in 32cbacf4c8.

2024-08-15 03:31 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    raise e
This is for handling the unlikely case of generating a `delay_id` that matches an already-existing one & getting a collision.  The intent is to regenerate the ID until a non-colliding one is made (though it should be incredibly rare for a collision to ever happen).  If there's a better pattern for handling this, I'm all ears.

2024-08-15 03:32 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    crc = base62_encode(crc32(base.encode("ascii")), minwidth=6)
I don't think it's strictly needed, but other ID-like values we have use a CRC so I figured I'd use it here too.  The delay ID just needs to be an arbitrary, opaque string, so maybe it shouldn't bother with using a CRC.

2024-08-15 03:35 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                membership = content.get("membership", None)
Turns out this is done in a few places (which I must have copied from :facepalm: ).  I'll probably make a small, separate PR for updating all of them.

2024-08-15 03:36 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            SynapseError if the delayed event failed to be added.
Sure, but many other `Raises:` sections don't put a colon after the exception types they mention.  Maybe they should all be updated.

2024-08-15 03:36 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            NotFoundError if there is no matching delayed event.
Ditto

2024-08-15 12:40 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    delay_id TEXT NOT NULL,
fafaa03214

2024-08-15 12:40 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql.postgres
> +ALTER TABLE delayed_events ALTER COLUMN delay_rowid ADD GENERATED ALWAYS AS IDENTITY;
fafaa03214

2024-08-15 12:40 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        self.room_member_handler = hs.get_room_member_handler()
3afa3cf8f2

2024-08-15 12:41 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        Params:
b3d4d6cb41

2024-08-15 12:41 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                May only refer to a delayed event that has no parent itself.
48d81262b5

2024-08-15 14:40 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    ),
Good idea -- `not self._use_returning` also means that SQLite3 is in use, which supports `last_insert_rowid`.

2024-08-15 14:48 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    ),
Actually, no -- I had considered using it before, but found that it returns not the last rowID of a target table, but the last one among _all_ tables.  That means if some other table outside of this transaction had a row added to it immediately after the `delayed_events` table's row was inserted, the new rowID of that other table would be returned here instead.

2024-08-15 14:58 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            table="delayed_event_children JOIN delayed_events ON child_rowid = delay_rowid",
Yes, the method's implementation indeed allows for selecting from joined tables.  If this is a code smell, I don't mind changing it, but there are some handy checks in the `simple_select_`*s that make them desirable over working with `execute`.

2024-08-15 15:54 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        """NOTE: Should not be called with a delay_id that isn't in the DB, or with a negative delay."""
Checking that it's in the DB requires an async call, but I want to keep this method synchronous.  It's no longer that bad for the delay to be missing from the DB, so I'll just remove this comment.

Asserting for a positive delay is easy & a good idea, so it shall be done.

2024-08-15 17:29 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                membership = content.get("membership", None)
Interesting...using `, None)` makes mypy deduce `membership` as an `Any` instead of an `Optional[Any]`, so it actually worsens typechecking!

2024-08-15 19:01 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                WHERE {" AND ".join("%s = ?" % k for k in keyvalues)}
It's tricky to use it here since the items to match on aren't known right away / require a DB lookup.

Plus, IMO generating a long `IN (?,?,...?)` clause may be less efficient than using a CTE, which lets the DB engine handle the complexity of deciding what to match on.

Also, this uses the same construction of the "WHERE...AND" clause used by `DatabasePool` methods (albeit using an f-string instead of `%`-formatting), so this should be as resistant to SQL injections as they are.

2024-08-15 19:12 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            event_id = "$" + random_string(43)
bee52bd95f

2024-08-15 19:14 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            SynapseError if the delayed event failed to be added.
c4e80adcbe, just for the ones in this PR

2024-08-15 19:14 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                membership = content.get("membership", None)
56abbb95d7 just for this one

2024-08-15 19:15 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        """NOTE: Should not be called with a delay_id that isn't in the DB, or with a negative delay."""
08f54ca54c

2024-08-15 19:20 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                        additional_fields={"db_error": str(e)},
62527082e6 moves the full error string to a debug message (to help debug what the DB error is when/if they happen).

2024-08-15 19:20 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                # TODO: Verify contents?
The contents are now verified both on event scheduling time & send time, so this TODO is no longer needed: b1f74a81c3

2024-08-15 19:21 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    crc = base62_encode(crc32(base.encode("ascii")), minwidth=6)
221e0af65f

2024-08-15 19:30 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        # TODO: Always use RETURNING once the minimum supported Sqlite version is 3.35.0
https://github.com/element-hq/synapse/issues/17577

2024-08-15 19:32 UTC, AndrewFerr commented
I've gone through all of @anoadragon453's comments so far, so anyone else can feel free to pick this up :slightly_smiling_face:

2024-08-19 15:14 UTC, andybalaam commented on synapse/handlers/delayed_events.py
> +# Originally licensed under the Apache License, Version 2.0:
Is this needed for new files?

2024-08-19 17:10 UTC, AndrewFerr commented on synapse/rest/client/room.py
> +        parent_id = parse_string(request, "org.matrix.msc4140.parent_delay_id")
[`21311fb`](https://github.com/element-hq/synapse/pull/17326/commits/21311fbcb30a4b76876faa71465db05003f4d2ea)

2024-08-20 10:34 UTC, sandhose requested changes, later dismissed

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    #    syf_<random string>
```suggestion
    #    syd_<random string>
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +                assert txn.rowcount == 1
```suggestion
                self.db_pool.simple_update_one_txn(
                    txn,
                    table="delayed_events",
                    keyvalues={"delay_rowid": row[0]},
                    updatevalues={"running_since": current_ts},
                )
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +        return await self.db_pool.runInteraction("restart", restart_txn)
The interaction name should be more descriptive, as I believe it bubbles up in metrics and traces

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +            )
I'm slightly scared that this removes them from the delay table, only living in-process. If the process crashes in the meantime, they would get lost

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +            )
Feels like this should be checked at the REST API level?

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +            )
Feels like this should be checked at the REST API level?

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +                await self._send_event(user_localpart, *args)
This also means the even could get lost here

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +        )
This feels a bit clunky, but I understand why it's like that :(
We should *at least* keep the `device_id` in the requester as well, because we use that to scope transaction IDs and handle local echo

Can you add a comment here about why we're creating a requester on the fly here?

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +                return await self.db_pool.runInteraction("add", add_txn)
Same here, this should use a more descriptive interaction name

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def restart(
```suggestion
    async def restart_delayed_event(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def add(
```suggestion
    async def add_delayed_event(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def get_all_for_user(
```suggestion
    async def get_all_delayed_events_for_user(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def process_all_delays(self, current_ts: Timestamp) -> Tuple[
```suggestion
    async def process_all_delayed_events(self, current_ts: Timestamp) -> Tuple[
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def pop_event(
```suggestion
    async def pop_delayed_event(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def remove(
```suggestion
    async def remove_delayed_event(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/databases/main/delayed_events.py
> +    async def remove_state_events(
```suggestion
    async def remove_delayed_state_events(
```

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +    def _schedule(
I don't like the idea of having all the delayed events as in-process timeouts like that. I would rather have a reconciliation loop, where it fetches the next deadline, and wakes up at that time to process any pending event. This would greatly simplify the logic here

2024-08-20 10:34 UTC, sandhose commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    content bytea NOT NULL,
One way to avoid loosing event could be to:

 - add a column like `processed_ts`, or `picked_up_at` (I'm not good at naming things) where we record when the event is picked up by a worker
 - record the delay ID in the event internal metadata
 - when an event gets properly persisted, delete it from the delayed events
 - if we find events that have a `processed_ts` too old (5 min or so), consider that they were not persisted, clear that column and they would get processed again

2024-08-20 10:34 UTC, sandhose commented on synapse/handlers/delayed_events.py
> +        await self._initialized_from_db
If I get that correctly, that means that we'd block until all the events in the queue are persisted?
So if your server is away for a while, and all the sudden you have thousands of delayed events to process, any `add`/`update` call would block until they get processed, instead of getting queued

2024-08-20 16:58 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    raise e
90cc8b5

2024-08-20 16:58 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            table="delayed_event_children JOIN delayed_events ON child_rowid = delay_rowid",
This is gone now that parent IDs are removed by 21311fb.

2024-08-20 16:59 UTC, AndrewFerr commented on synapse/config/experimental.py
> +            self.msc4140_max_delay = 10 * 365 * 24 * 60 * 60 * 1000  # 10 years
Skipping the check is solely for making it more clear that the default value will never throw a `ValueError`.

00217f3152 reraises the `ValueError`; if it's still preferred to drop the `KeyError`, I'll do it.

2024-08-20 16:59 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                WHERE {" AND ".join("%s = ?" % k for k in keyvalues)}
This clause is gone now that parent IDs are removed by 21311fbcb3.

2024-08-20 17:02 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    ),
Oh, that's perfect then!

2024-08-20 17:03 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +# Originally licensed under the Apache License, Version 2.0:
I'm not sure, but given that other recently-added files have it, I assume they do.

2024-08-20 17:04 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    raise e
Removed by 90cc8b5a22

2024-08-20 17:04 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                )
Removed by 90cc8b5a22

2024-08-20 17:04 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    delay_rowid INTEGER PRIMARY KEY,
The main benefit of the single-column rowid key was to make joins on other delayed-event tables easier, but those are gone now, so this can be done: 5672d0d973

2024-08-20 17:04 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    #    syf_<random string>
Oops, thanks! 347811891a

2024-08-20 17:04 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                assert txn.rowcount == 1
e0e6802f1d

2024-08-20 17:05 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        return await self.db_pool.runInteraction("restart", restart_txn)
85cb72f9f6

2024-08-20 17:05 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            )
This runs only once on startup, at which point there will be no in-process timers yet.

2024-08-20 17:05 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            )
8a65c77336

2024-08-20 17:05 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            )
47b6e69

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
This excludes a `device_id` because the device that scheduled the delayed event isn't really involved in the eventual sending of that event, or so I thought.

Should the DB save (along with the event content to send) the device ID that requested the delayed event?

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                return await self.db_pool.runInteraction("add", add_txn)
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def restart(
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def add(
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def get_all_for_user(
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def pop_event(
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def remove(
85cb72f9f6

2024-08-20 17:06 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def remove_state_events(
85cb72f9f6

2024-08-20 17:07 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        await self._initialized_from_db
This should wait only on delayed events that were loaded from the DB on startup, i.e. delayed events that were scheduled (and not yet sent) prior to a server restart.

Since `initialized_from_db` is the `Deferred` returned by the async work done on startup, AIUI `await`ing it doesn't repeat any work, and instead just checks that the startup work is done before continuing.

The waits that are relevant to newly-added delayed events are the ones from `_get_delay_context` and `_get_state_context`, which should be scoped to `delay_id` and `state_key` respectively. (But now that I look at it, `_get_state_context` should also be scoped to rooms).

2024-08-21 12:17 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                    ),
This query is gone now, but if something like this is needed again, I'll remember to use `last_insert_rowid` for it.

2024-08-21 12:24 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    delay_rowid INTEGER PRIMARY KEY,
Also 05accda65b

2024-08-21 12:56 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    running_since BIGINT NOT NULL,
Turns out it's possible to index an expression like `running_since + delay`, but having the send time as a column is more convenient, so I've done it: 57b7229

Next is using it to fetch the nearest deadline.

2024-08-21 19:39 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
Something else to consider is that the device (and its access token) which requested a delayed event may be destroyed / logged out by the time the event actually gets sent.

If the device ID / access token really is needed for this, how about adding a DB column to store the requester of the delayed event?  I had tried that before (thanks to requesters being serializable) but got rid of it due to thinking devices were irrelevant for delayed event sending.

2024-08-23 16:27 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    content bytea NOT NULL,
Thanks for thinking so much about lost events, it's been a huge help!

Another situation that arises is the risk of double-sending an event: if the server crashes after a delayed event is persisted but before it's removed from the DB table of pending delayed events, a server restart would have to know whether an entry of the delayed event table is one that actually got persisted & doesn't need to be sent again.

I discussed this with the VoIP team, and a strategy we arrived at was to search through the timeline up to a delayed event's `send_ts` for events possibly sent during a server outage, and if there's one that has that event's delay ID in its metadata (either in the `"unsigned"` object or in some Synapse-internal struct/table), then it means the delayed event was sent & doesn't need to be sent again.  This avoids needing the `processed_ts` column, because we know that only events in the past would have been processed, and we already have the timestamp of them via `send_ts`.

Though what would be ideal is if event persistence could include a step for deleting delayed events from the DB, as long as the work done for event persistence is atomic / done in a transaction.  Then there'd be a guarantee that the delayed event table would never get out-of-sync with the set of persisted events.

2024-08-28 09:33 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +# TODO: Try to support workers
Workers should be better supported now, though other comments address open questions.

2024-08-28 09:34 UTC, AndrewFerr commented on synapse/config/experimental.py
> +            self.msc4140_max_delay = 10 * 365 * 24 * 60 * 60 * 1000  # 10 years
I refactored this to use similar code style as other duration configs: 3ce7305

2024-08-28 09:36 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    running_since BIGINT NOT NULL,
be094e6

2024-08-28 09:36 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            )
be094e6 avoids removing from the delay table until the event has persisted.

2024-08-28 09:37 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                await self._send_event(user_localpart, *args)
be094e6

2024-08-28 09:37 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
235c432 adds the device ID and the comment.

2024-08-28 09:37 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +    def _schedule(
be094e6

2024-08-28 09:39 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    content bytea NOT NULL,
be094e6, but still missing is a scan of the timeline to avoid double-sending events that persisted but weren't removed from the delay table.  That is hopefully a rare enough case to not be a showstopper, though.

2024-08-28 09:41 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        await self._initialized_from_db
The startup task now blocks only on the job of marking timed out events as being processed, but the actual sending of the events is done in the background.

2024-08-28 09:44 UTC, AndrewFerr commented on synapse/config/server.py
> +
This config no longer in the `experimental` section, but is now disabled by default.  The reasoning is to reduce config churn once delayed events become stable, while still making it something server admins must explicitly opt into using.

2024-08-28 09:53 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
The aim is to cancel all delayed state events whenever a conflicting state event (i.e. one with the same room ID + event type + state key) is received.

The problem is that the only callback I could find for reacting to received events is the third party callbacks, and those are called as a background task during event persistence: https://github.com/element-hq/synapse/blob/f4032d3e718c806a193fb5167d9958052cd47add/synapse/handlers/message.py#L1935

Is there anything that runs a foreground callback when an event is received?  And how do workers get notified of newly received events?

2024-08-28 10:18 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            # events being processed by a worker vs ones that got lost after a server crash.
What `unprocess_delayed_events` is trying to solve is the case of the server crashing between the time it marked delayed events as `is_processed` but before having been able to send & persist the event.  That would leave behind `in_processed` rows the next time the server starts, but with nothing running to handle sending the events.  So, the quick fix is to try sending them again, by unmarking them as processed and treating them like any other timed-out delayed event.

The problem is that, when using workers, `is_processed` rows being present on startup could also mean that another worker is in the middle of sending delayed events.

Maybe the right approach is to allow only one worker / the main process to handle sending delayed events?  Currently, the timer for sending delayed events can get set for multiple workers, but the way `is_processed` is set & used for filtering rows should prevent multiple workers from trying to send/edit the same event at once.  But it doesn't help with this startup interference issue.

2024-08-28 10:25 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            # already sent. To do so, must store delay_ids in sent events to retrieve them later.
To recap https://github.com/element-hq/synapse/pull/17326#discussion_r1729227576 & https://github.com/element-hq/synapse/pull/17326#discussion_r1734343222, the solution I had in mind for this was to:
- put the delay ID of each sent delayed event in its `"unsigned"` section
- on startup, for each `is_processed` row still in the delayed events table, scan its destination room until its `send_ts`, searching for any event with its delay ID in the `"unsigned"` section.  If found, skip sending the delayed event; otherwise, do send it.

2024-09-04 12:59 UTC, ara4n commented on synapse/handlers/delayed_events.py
> +# Originally licensed under the Apache License, Version 2.0:
we should only have the "originally licensed" for files which /were/ originally licensed as apache (i.e. not this one)

2024-09-04 13:22 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +# Originally licensed under the Apache License, Version 2.0:
Thanks. Removed them with 798c79e773

2024-09-05 20:53 UTC, anoadragon453 requested changes
Apologies for the long wait time on this PR. It's quite a hefty one, with new concepts, and I kept getting pulled away before I could fully wrap my brain around it.

A fair number of comments below, but nothing requiring any major architecting. I would like to see some more testing done, either through unit tests or complement, to help prove the handling of sending the next delayed event.

It would also be helpful to include docstrings for private methods, even if they're small, as it helps when skimming the code while getting a grasp on it for the first time.

(Note: a few comments below may be outdated as they were made on commits. Instead of clicking through all the commits and closing them, I'm just going to do so after submitting this review.)

2024-09-05 20:53 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +                return False, None
nit

```suggestion
            
            return False, None
```

2024-09-06 13:33 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
> Module API callback functions should only be registered by [Synapse modules](https://element-hq.github.io/synapse/latest/modules/index.html),

Ah, I was wondering about that. I found it used by the [InviteAutoAccepter](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/events/auto_accept_invites.py#L57) so I thought using it for internal callbacks was acceptable, but it makes more sense that it's meant for external modules.

> In this case, likely what you want is to add a replication callback for the event notifier (see [example](https://github.com/element-hq/synapse/blob/ca69d0f57165ecb10204ee433992b20af71cbe91/synapse/handlers/presence.py#L868-L869)).

Ideally, I need a callback that is told about newly-received events (namely state events), but the replication callback isn't given any arguments. Is there a callback for received events?  If not, should I create one?  It would be analogous to [the callback for joins](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/notifier.py#L297).

2024-09-06 13:33 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
> Module API callback functions should only be registered by [Synapse modules](https://element-hq.github.io/synapse/latest/modules/index.html),

Ah, I was wondering about that. I found it used by the [InviteAutoAccepter](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/events/auto_accept_invites.py#L57) so I thought using it for internal callbacks was acceptable, but it makes more sense that it's meant for external modules.

> In this case, likely what you want is to add a replication callback for the event notifier (see [example](https://github.com/element-hq/synapse/blob/ca69d0f57165ecb10204ee433992b20af71cbe91/synapse/handlers/presence.py#L868-L869)).

Ideally, I need a callback that is told about newly-received events (namely state events), but the replication callback isn't given any arguments. Is there a callback for received events?  If not, should I create one?  It would be analogous to [the callback for joins](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/notifier.py#L297).

2024-09-06 14:41 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +    SEND = "send"
Looks like `Enum` fields are already effectively `Final`.  If I try to overwrite one of these without hinting it as `Final`, mypy raises an error of "Cannot assign to final attribute".

2024-09-06 14:54 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        ],
This excludes the `DelayID` and `UserLocalpart` fields.  I'd like for this to be a named type that `DelayedEventDetails` could extend from / include, but couldn't think of a clean way to do it.  Maybe defining both of them as `attr` classes is the answer.

2024-09-06 14:57 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                    sent_state.add(state_info)
It's used a few lines up, to avoid sending multiple timed-out delayed events for the same state.

2024-09-06 15:03 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        # TODO: Consider storing the requester in the DB at add time and deserialize it here
That's good to know, thanks!

Are there any other properties that should be sent to `create_requester` here?  If not, I'll just remove the comment and consider this sufficient.

2024-09-06 15:04 UTC, AndrewFerr commented on synapse/rest/client/delayed_events.py
> +        # TODO: Support Pagination stream API ("from" query parameter)
In a follow-up, and agreed.

2024-09-06 16:08 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        changed = await self.db_pool.runInteraction(
Yes, exactly

2024-09-06 17:35 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            return old_next_send_ts is None or send_ts < old_next_send_ts
Yes it does, but the only purpose of the return value is to know whether or not to reschedule the check for timed-out delayed events.  Whether the added event is the next to be sent or not doesn't matter, since the timeout check scans for _all_ timed-out events, meaning any events with the exact same timeout time will all get sent.

2024-09-06 18:21 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            new_next_send_ts = self._get_next_delayed_event_send_ts_txn(txn)
Yes it can; I'll refactor the DB lookups to achieve this.

2024-09-06 18:26 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        Returns: Whether the matching delayed event would have been the next to be sent,
It's not; in fact, since restarting a delayed event can only delay it further, a restarted event can never become the next one to be sent.

The return value is concerned only with whether the next-soonest timeout time among all delayed events has changed by virtue of the target event being restarted.  With that said, the current wording doesn't reflect that, so I'll update it.

2024-09-06 18:31 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            and if so, what the next soonest send time is, if any.
It currently is, but it need not be.  If the returned `bool` is False, the returned `Timestamp` has no meaning and should be ignored (and I should make it `None` to be explicit about that).

The reason is that the `Timestamp` is meaningful only when the next-soonest timeout time has changed, because that time is used to reschedule the timeout callback; if the time didn't change, there's no need to reschedule anything.

2024-09-06 20:13 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +            new_next_send_ts = self._get_next_delayed_event_send_ts_txn(txn)
Er, what I should have said was "not quite", because the current DB lookups aren't enough to deduce this.  Changing what's queried can get the required information with fewer total requests to the DB.

2024-09-09 11:33 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +        )
> Ah, I was wondering about that. I found it used by the [InviteAutoAccepter](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/events/auto_accept_invites.py#L57) so I thought using it for internal callbacks was acceptable, but it makes more sense that it's meant for external modules.

Yes, this was an external module that was inlined into the codebase. There was [a back and forth](https://github.com/element-hq/synapse/pull/17147#discussion_r1592629098) about using external module APIs internally, though ultimately we ended up leaving it how it was.

> Ideally, I need a callback that is told about newly-received events (namely state events), but the replication callback isn't given any arguments. Is there a callback for received events?  If not, should I create one?  It would be analogous to [the callback for joins](https://github.com/element-hq/synapse/blob/e5d07bb0830eea056ea85863bca3d5b093d43a88/synapse/notifier.py#L297).

Ah, right, sorry. The way this works is not that events are sent over replication, but rather workers are merely poked that new events exist, and are then expected on their own to go and pull them out of the database. This cuts down on the size of the replication traffic, but does mean you need to do extra work.

Synapse has the concept of [streams](https://element-hq.github.io/synapse/latest/development/synapse_architecture/streams.html). Each event in the `events` table has a "stream ID" (`stream_ordering` column). Workers have a stream ID they keep track of, and upon being told that there are new events, will query the database for "all events with X attributes that have a stream ID > Y" to get at new events.

If you're just after state event changes, you can make use of the `current_state_deltas_stream`. It only track state events, rather than all event types.

The presence example might not be best as it always just [starts from the latest event on startup](https://github.com/element-hq/synapse/blob/ca69d0f57165ecb10204ee433992b20af71cbe91/synapse/handlers/presence.py#L871-L873). A better mechanism to reference is the [`UserDirectoryHandler`](https://github.com/element-hq/synapse/blob/anoa/configure_workers_updates/build/lib.linux-x86_64-cpython-312/synapse/handlers/user_directory.py#L71). It stores its currently read up to stream token in the [`user_directory_stream_pos` table](https://github.com/element-hq/synapse/blob/anoa/configure_workers_updates/build/lib.linux-x86_64-cpython-312/synapse/handlers/user_directory.py#L209-L211), which is queried on startup. [`notify_new_event`](https://github.com/element-hq/synapse/blob/anoa/configure_workers_updates/build/lib.linux-x86_64-cpython-312/synapse/handlers/user_directory.py#L171-L186) is then called whenever a new event is created, and then the `current_state_deltas_stream` is read to see whether users have left/joined any rooms. The user directory is then updated accordingly.

It's possible to have multiple workers reading here, but it's easiest to start with just one.

2024-09-09 11:41 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +                    sent_state.add(state_info)
Ah! Thanks, not sure how I missed that :yum:

2024-09-09 11:47 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +        # TODO: Consider storing the requester in the DB at add time and deserialize it here
What you're passing now is sufficient I think.

2024-09-09 11:50 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +        changed = await self.db_pool.runInteraction(
In that case, I think the docstring's definition for the second item in the returned tuple is a little confusing. Rather than "whether the added delayed event is the next to be sent", perhaps it should be "whether the next event to be sent is now this event instead".

2024-09-09 11:52 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +            and if so, what the next soonest send time is, if any.
That makes sense, thanks. I agree that making it `None` would be a clearer signal to callers to not use it.

2024-09-09 13:09 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        # TODO: Store and return "transaction_id"
Presumably, but I doubt its usefulness & return it just to satisfy the current version of the MSC.  I propose against returning it [here](https://github.com/matrix-org/matrix-spec-proposals/pull/4140/files#r1747605229).

2024-09-09 13:50 UTC, AndrewFerr commented on docs/usage/configuration/config_documentation.md
> +Defaults to no duration, which disallows sending delayed events.
a3fbdd348d

2024-09-09 13:50 UTC, AndrewFerr commented on docs/usage/configuration/config_documentation.md
> +The maximum allowed duration by which sent events can be delayed, as per MSC4140.
a3fbdd348d

2024-09-09 13:50 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        # TODO: Consider storing the requester in the DB at add time and deserialize it here
1dbbb749bc

2024-09-09 13:50 UTC, AndrewFerr commented on synapse/rest/client/delayed_events.py
> +"""This module contains REST servlets to do with delayed events: /delayed_events/<paths>"""
ef7284ff3d

2024-09-09 13:51 UTC, AndrewFerr commented on tests/rest/client/test_rooms.py
> +        """Test sending a delayed event with invalid content."""
Yes, good catch.  Fixed in 0ab82f50b5

2024-09-09 13:51 UTC, AndrewFerr commented on tests/rest/client/test_rooms.py
> +class RoomDelayedEventTestCase(RoomBase):
Good idea.  This is done in 0ab82f50b5

2024-09-09 13:51 UTC, AndrewFerr commented on tests/rest/client/test_rooms.py
> +        """Test sending a delayed event with invalid content."""
0ab82f50b5

2024-09-09 13:51 UTC, AndrewFerr commented on tests/rest/client/test_rooms.py
> +        """Test sending a delayed event with invalid content."""
0ab82f50b5

2024-09-09 13:53 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                raise NotFoundError("Delayed event not found")
90259228ee (though it's not just for the requesting user, but any user)

2024-09-09 13:53 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        Returns: Whether the matching delayed event would have been the next to be sent,
Refactored and redocumented in 3e9f76f32d

2024-09-09 13:53 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +                return False, None
c3ad95d

2024-09-09 16:26 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +        # TODO: Store and return "transaction_id"
Right. We'll keep it for now while it matches the MSC then, but open to changing it down the line.

2024-09-09 20:54 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/88/01_add_delayed_events.sql
> +) SELECT COALESCE(MAX(stream_ordering), 0) from events;
This was based on [04_add_room_forgetter.sql](https://github.com/element-hq/synapse/blob/develop/synapse/storage/schema/main/delta/76/04_add_room_forgetter.sql).

2024-09-09 20:54 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
`notify_new_event` & company was based on similar code from [`UserDirectoryHandler`](https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/user_directory.py#L171), [`PresenceHandler`](https://github.com/element-hq/synapse/blob/develop/synapse/handlers/presence.py#L1478), [`RoomForgetterHandler`](https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/room_member.py#L2163), and [`StatsHandler`](https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/stats.py#L78).

2024-09-09 20:54 UTC, AndrewFerr commented on synapse/module_api/callbacks/third_party_event_rules_callbacks.py
> -            return
I reverted this since it was needed only for my third-party callback, which is gone now.

2024-09-09 20:54 UTC, AndrewFerr commented on tests/rest/client/test_rooms.py
I reverted these since they had changed only because of my third-party callback, which is gone now.

2024-09-09 20:56 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +        )
This was crucial info, thanks for such a helpful writeup!  [`d36c89f`](https://github.com/element-hq/synapse/pull/17326/commits/d36c89f10e2d87c497fbd54533c0d7e421024cfa) handles this.

2024-09-09 20:58 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            # events being processed by a worker vs ones that got lost after a server crash.
Restricting delayed event sending to a single worker should definitely simplify things, but I still have to look into how to handle send-on-timeout vs send-on-demand.  With the way things are, multiple workers may already be safe, but maybe not...

2024-09-09 21:00 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +    async def process_timeout_delayed_events(
This function is used not only on the startup handling (which I'd like to remove, FTR) but also on _any_ timeout.  The idea is to check for all timed-out events instead of just one, in case there was some delay between the timeout time & when it actually runs; and also to be more resilient against failures (so if one delayed event failed to send, the next timeout will send the next event + all prior ones).

2024-09-10 14:23 UTC, anoadragon453 requested changes
A few small changes here, but overall things are really shaping up.

Tests-wise, it'd be nice to see some testing of:

- A new state event cancelling a pending delayed state event.
- Whether pending delayed events get sent correctly on startup.

2024-09-10 14:23 UTC, anoadragon453 commented on synapse/storage/schema/main/delta/88/01_add_delayed_events.sql
> +INSERT INTO delayed_events_stream_pos (
```suggestion
-- Start processing events from the point this migration was run, rather
-- than the beginning of time.
INSERT INTO delayed_events_stream_pos (
```

2024-09-10 14:23 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +    def notify_new_event(self) -> None:
It may be important to note here with a comment that this isn't the mechanism that actually sends delayed events. This only checks for state events that may cancel a pending delayed state event.

2024-09-10 14:23 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +            # events being processed by a worker vs ones that got lost after a server crash.
How is this looking now after discussing how to use the background worker? Can we simplify the mechanism at all?

2024-09-10 14:48 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                logger.warning(
This was copied from a few other places:
- https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/user_directory.py#L221
- https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/room_member.py#L2186
- https://github.com/element-hq/synapse/blob/e1ed959a68f8039130be821c27e82e75b5d59e5f/synapse/handlers/stats.py#L101

So maybe let's keep it the same for the sake of consistency, and update all of them in another PR if appropriate.  (On that note, there's quite a lot of boilerplate for following the state event stream, so it'd be nice to commonize it somehow...)

2024-09-10 14:55 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +                    # The next event to be sent is the only one to be sent at that time
Yep, that sounds good as well!

2024-09-10 14:55 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
> +                    )
Ah, right of course. Carry on then!

2024-09-10 14:56 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +        that target the same state as any received state events.
Oh, yes. Sorry, I wasn't saying the comment was wrong - just that it felt a bit repetitive.

2024-09-10 16:00 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +            # events being processed by a worker vs ones that got lost after a server crash.
Alas, being able to have `/send` and `/state` on multiple event creator workers is currently a big part of Synapse's horizontal scalability capabilities.

Having multiple workers adding events to delayed state tables, and only a single worker pulling them out/cancelling them could work?

2024-09-11 06:33 UTC, AndrewFerr commented
See https://github.com/matrix-org/complement/pull/734 for Complement tests.  So far, the only test is for new state events cancelling pending delayed events; more tests are to come.

2024-09-11 15:19 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        # TODO: Store and return "transaction_id"
Returning transaction IDs has been removed from the MSC, so dd3c746eb5 removes this TODO.

2024-09-11 15:27 UTC, AndrewFerr commented
https://github.com/matrix-org/complement/pull/734 now has a test for sending timed-out / restoring still-pending delayed events on server restart.

2024-09-11 18:34 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +]
a60fa7f91b

2024-09-11 18:34 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        ],
a60fa7f91b

2024-09-11 18:37 UTC, AndrewFerr commented on synapse/rest/client/delayed_events.py
> +# TODO: Needs unit testing
e41b5a1d74 adds a unit test module for the delayed event servlets.

For Complement tests, see https://github.com/matrix-org/complement/pull/734

2024-09-13 05:26 UTC, AndrewFerr commented on synapse/storage/schema/main/delta/87/01_add_delayed_events.sql
> +    content bytea NOT NULL,
I'm going to leave the double-sending fix to another PR.

2024-09-13 05:27 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            # already sent. To do so, must store delay_ids in sent events to retrieve them later.
I'm going to leave this to another PR.

2024-09-13 05:33 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
> +        changed = await self.db_pool.runInteraction(
1d750601, though I dropped the concept of checking for a changed next-send-time (at least for now) in a6cf11c0.

2024-09-13 05:33 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +            # events being processed by a worker vs ones that got lost after a server crash.
092793a287 restricts as much as possible to a single worker.

2024-09-13 05:35 UTC, AndrewFerr commented on synapse/rest/client/delayed_events.py
> +# TODO: Needs unit testing
fb048335bb adds some more tests.

I'm unsure of a way to make Synapse unit tests stop/restart its homeserver, so currently only the Complement tests cover the case of delayed events that timed out while the server was down.

2024-09-13 14:24 UTC, AndrewFerr commented
Despite the failures in Sytest, it passes when I run it locally.

2024-09-16 17:27 UTC, anoadragon453 reviewed
Thanks for all the time you've spent (and patiently waited) on this. This now looks good to me, and the added tests help.

I see you have a matching Complement branch here: https://github.com/matrix-org/complement/pull/734. I assume you would like to hold off on merging this PR until those tests pass?

Finally, once this is merged and done, if you have some time to document how the whole mechanism works (however detailed or briefly) in https://element-hq.github.io/synapse/latest/development/internal_documentation/index.html, that would help future development efforts.

2024-09-16 18:24 UTC, AndrewFerr commented
> I see you have a matching Complement branch here: [matrix-org/complement#734](https://github.com/matrix-org/complement/pull/734). I assume you would like to hold off on merging this PR until those tests pass?

Yes, as long as it's permissible to merge Complement tests before any implementations are merged.



> Finally, once this is merged and done, if you have some time to document how the whole mechanism works (however detailed or briefly) in https://element-hq.github.io/synapse/latest/development/internal_documentation/index.html, that would help future development efforts.

Noted!

2024-09-17 09:16 UTC, anoadragon453 commented
Typically we'll merge them at the same time. However, yes, technically the Complement tests can be merged beforehand, as they won't be enabled on `develop` until this PR is merged.

2024-09-17 09:17 UTC, anoadragon453 commented
(Complement CI is expected to fail until https://github.com/matrix-org/complement/pull/734 is merged.)

2024-09-18 15:06 UTC, anoadragon453 commented
https://github.com/matrix-org/complement/pull/734 has been merged. I've re-run the failed Complement jobs: https://github.com/element-hq/synapse/actions/runs/10891540744?pr=17326

2024-09-18 15:07 UTC, anoadragon453 approved these changes
LGTM, assuming the Complement tests are happy.

2024-09-18 15:33 UTC, AndrewFerr commented
> assuming the Complement tests are happy

They aren't :upside_down_face:  Looking into it now.  The failures reproduce locally, so I should have a fix ready very soon.

2024-09-18 16:02 UTC, anoadragon453 commented
@AndrewFerr looks like there's complement failures on the delayed event tests: https://github.com/element-hq/synapse/actions/runs/10891540744/job/30325234632?pr=17326

2024-09-18 16:16 UTC, AndrewFerr commented
Looks like the Complement failures are false-positives when running in Postgres.  I'm updating the Complement tests to account for that.

2024-09-18 18:04 UTC, AndrewFerr commented
The Postgres tests should be fixed by https://github.com/matrix-org/complement/pull/737.  They pass when I run them locally, in either monolith or worker mode.

2024-09-18 19:55 UTC, AndrewFerr commented
Alright, I added an extra commit to satisfy what the Complement test was failing on, and now we don't have to worry about merging https://github.com/matrix-org/complement/pull/737 first.

The test expects `GET /delayed_events` to return events in the order they'll be sent, but no such order was guaranteed when using Postgres.  [`dfde3c2`](https://github.com/element-hq/synapse/pull/17326/commits/dfde3c22db2490b8aa6b75813368d006ba32bf0c) applies the ordering the test expects.

Strictly speaking, the test doesn't have to cover ordering on `GET /delayed_events` because the MSC doesn't (yet) define an ordering, so I wrote https://github.com/matrix-org/complement/pull/737/commits/279d1b3724cef49ed8f8357900ef7ddb59bce73c to remove that part of the test.

The other test failure was simply due to leftover data after the first test failed, so I wrote https://github.com/matrix-org/complement/pull/737/commits/6f86880ab2ae6f394146d3b2c15721b2eef15745 to make tests do some teardown to prevent unrelated failures later on.

Note that all tests will continue to pass with https://github.com/matrix-org/complement/pull/737, so it can still be merged safely, but now it is optional to do so :slightly_smiling_face:

2024-09-23 12:33 UTC, merged

2025-12-17 19:33 UTC, MadLittleMods commented on synapse/handlers/delayed_events.py
> +                )
Why don't we also call this for `_send_event`?

What's special about `_send_events` case but not `_send_event`?

2025-12-17 19:46 UTC, MadLittleMods commented on synapse/handlers/delayed_events.py
> +            for room_id, event_type, state_key in sent_state:
We accumulate `sent_state` within the loop but then also iterate over `sent_state` within the same loop during each iteration (covering the same ground).

Overall, this setup seems wrong. We should probably be calling `delete_processed_delayed_state_events` as part of `self._send_event(...)`