Clarify `url_preview_url_blacklist` is a usability feature
element-hq/synapse pull request #17356
Opened 2024-06-24 11:31 UTC by davidegirardi

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-06-24 11:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17356) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17356) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17356) it.</sub>

2024-06-24 13:09 UTC, reivilibre requested changes

2024-06-24 13:09 UTC, reivilibre commented on docs/usage/configuration/config_documentation.md
> +that will never want synapse to try to spider.
I think this last sentence isn't as clear as it could be

```suggestion
that you do not want Synapse to preview.
```

I've removed the word spider as I think is not the right term, since Synapse doesn't follow any further links etc.

I think you are trying to say that you would use this feature because you don't want to preview some URLs because they are *ugly*, not because they are malicious/etc

2024-06-24 13:17 UTC, davidegirardi commented on docs/usage/configuration/config_documentation.md
> +that will never want synapse to try to spider.
Those words were already there: https://github.com/element-hq/synapse/pull/17356/files?short_path=1865c1e#diff-1865c1e8307bb29e7f82bbaae74af9e1e09936211f514e8a8006cfd0c2bdea9d

Anyhow, let's improve them no matter what.

2024-06-28 13:39 UTC, reivilibre commented on docs/usage/configuration/config_documentation.md
> +that will never want synapse to try to spider.
well oops, sorry but yes let's fix it whilst we're here :)

2024-06-28 13:39 UTC, reivilibre approved these changes

2024-06-28 13:39 UTC, merged