Support MSC3916 by adding  `_matrix/client/v1/media/download` endpoint
element-hq/synapse pull request #17365
Opened 2024-06-27 03:58 UTC by H-Shay

[MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) adds a new endpoint `_matrix/client/v1/media/download`, which adds authentication and fetches remote media over the `_matrix/federation/v1/media/download` endpoint (also added in MSC3916). 

This PR implements that endpoint. Should be reviewable commit-by-commit. Updated complement tests for this are at https://github.com/matrix-org/complement/pull/727, not sure if that needs to be merged before they are run?

2024-06-28 13:47 UTC, anoadragon453 requested changes
Looking great overall. A few questions and requests below.

2024-06-28 13:47 UTC, anoadragon453 commented on synapse/media/media_repository.py
> +        if not use_federation_endpoint:
nit: It'd be cleaner to restructure this `if` statement to be inside the `try/except`, as the `except` conditions for both functions are the same.

2024-06-28 13:47 UTC, anoadragon453 commented on synapse/media/media_repository.py
> +        endpoint
I think this could be split into two sentences.

2024-06-28 13:47 UTC, anoadragon453 commented on synapse/media/media_repository.py
> +        logger.info("Stored remote media in file %r", fname)
This might be a bit noisy, especially if we're opening up a new room for the first time and downloading 100 avatars.

2024-06-28 13:47 UTC, anoadragon453 commented on tests/rest/client/test_media.py
> +    # test basic download
Are these TODO's?

2024-06-28 13:47 UTC, anoadragon453 commented on changelog.d/17365.feature
> +Support [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) by adding _matrix/client/v1/media/download endpoint
Note that you don't need to include the ` (#17365)` manually, as it is included by `towncrier` automatically when the changelog is generated.

2024-06-28 13:47 UTC, anoadragon453 commented on pyproject.toml
> +python-multipart = "^0.0.9"
I don't think this belongs under Optional Dependencies.

Also we typically use `>=` for dependencies as our dependencies are locked via Poetry. On each upgrade, we'll have CI check that the dependency won't break.

`^` here will lock us to `v0.0.x`, which will eventually become stale and need manual updating.

2024-06-28 18:41 UTC, H-Shay commented on synapse/federation/transport/client.py
> +        path = f"/_matrix/federation/v1/media/download/{media_id}"
Great question - I looked at the MSC and found this: 
> a. New clients & servers with older servers: The [M_UNRECOGNIZED](https://spec.matrix.org/v1.10/client-server-api/#common-error-codes) error behaviour should be followed to indicate that the server does not support the new endpoints, particularly when partnered with a 404 HTTP status code. Clients and servers should use the unauthenticated endpoints in this case.

My initial reading of this is that if this function returns a 404 `M_UNRECOGNIZED`, the request should err with a 502 bad gateway(?) and a log/error message indicating that the client should retry over the unauthenticated endpoints. 

An alternative, if a 404 `M_UNRECOGNIZED` is returned in this function is to fall back to the unauthenticated endpoint here - I'm not sure if that is the correct approach, however. Let me know which makes the most sense for you.

2024-06-28 18:43 UTC, H-Shay commented on synapse/rest/client/media.py
> +    )
yes, forthcoming

2024-06-28 18:43 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            hs,
yes, I have done so

2024-06-28 18:50 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            raise SynapseError(HTTPStatus.TOO_MANY_REQUESTS, msg, Codes.LIMIT_EXCEEDED)
Per the comments/code (unless I am misreading!) the ratelimiter does not update the action count if the action is denied - let me know if I should add a comment here to that effect...

2024-06-28 19:08 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +        boundary = content_type.split("boundary=")[1]
This should very definitely be a multipart/mixed response - many things beyond this will break if not. I've added a try/catch block to catch that error and raise a bad gateway error if so.

2024-06-28 20:27 UTC, H-Shay commented on changelog.d/17365.feature
> +Support [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/rav/authentication-for-media/proposals/3916-authentication-for-media.md) by adding _matrix/client/v1/media/download endpoint
Good to know! I find those so helpful I wanted to make sure I was adding them - I've fixed now.

2024-06-28 20:39 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            SynapseError: If the requested file exceeds ratelimits
Added!

2024-06-28 20:44 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            # add a byte of headroom to max size as function errs at >=
You are right, I have removed the comment and the `+ 1` and changed the relevant tests to reflect this.

2024-06-28 20:45 UTC, H-Shay commented on tests/rest/client/test_media.py
> +    # test basic download
old notes to myself, are integration tests now :)

2024-06-28 21:31 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            # add a byte of headroom to max size as function errs at >=
It actually was referring to what happens in the `_MultipartParserProtocol`'s `dataRecieved` function: https://github.com/H-Shay/hq_synapse/blob/5fcc81ade3e9afdab89c0da0aa77bf44304fd8de/synapse/http/client.py#L1109

So the check in `read_multipart_response` checks that the response length provided by the remote server is not greater than the max length, and in the `dataRecieved` function it checks that the actual data coming in over the wire doesn't exceed that (insurance against faulty/malicious response length data). Erring at >= is modeled after what happens in `_ReadBodyWithMaxSizeProtocol`: https://github.com/element-hq/synapse/blob/b11f5c984b28b5ff6f5909db34a4e6b96d3e4880/synapse/http/client.py#L1037, which was the model for protocol I added.

2024-06-28 21:46 UTC, H-Shay commented on synapse/media/media_repository.py
> +        logger.info("Stored remote media in file %r", fname)
I've changed it to debug, hopefully that helps?

2024-06-28 23:43 UTC, turt2live commented on synapse/federation/transport/client.py
> +        path = f"/_matrix/federation/v1/media/download/{media_id}"
The 'changed in v1.11' block on https://spec.matrix.org/v1.11/server-server-api/#content-repository describes a fallback behaviour, fwiw.

2024-06-29 00:18 UTC, H-Shay commented on synapse/federation/transport/client.py
> +        path = f"/_matrix/federation/v1/media/download/{media_id}"
So it looks like from that comment the behavior should be to fall back to the `_matrix/media` endpoint and make sure that `allow_remote` is false - I'll add that.

2024-06-29 03:54 UTC, H-Shay commented
complement failure looks like a flake but I can't kick it to check

2024-07-01 15:11 UTC, anoadragon453 commented on synapse/http/matrixfederationclient.py
> +            raise SynapseError(HTTPStatus.TOO_MANY_REQUESTS, msg, Codes.LIMIT_EXCEEDED)
Oh! Indeed, you're right. I hadn't looked at the implementation of `can_do_action`. And this behaviour is described by the description of `n_actions`, whereas I was looking at `update`.

While we're here, could you update `can_do_action`s docstring's `update` argument to be the following?

```py
            update: Whether to count this check as performing the action. If the action
                cannot be performed, the user's action count is not incremented at all.
```

2024-07-01 15:21 UTC, anoadragon453 requested changes
The failed CI job looked like a flake to me as well. Have kicked it.

A few small items now, but otherwise LGTM! Thanks for making the changes!

2024-07-01 15:21 UTC, anoadragon453 commented on tests/rest/client/test_media.py
> +# @parameterized_class(("test_image",), input_values)
Was this intentionally left commented?

2024-07-01 15:21 UTC, anoadragon453 commented on tests/rest/client/test_media.py
> +    # test_image: ClassVar[TestImage]
likewise

2024-07-01 15:21 UTC, anoadragon453 commented on synapse/http/matrixfederationclient.py
> +            # add a byte of headroom to max size as function errs at >=
Aha, I see. Could you just add a pointer to that function to make this comment clearer?

```suggestion
            # add a byte of headroom to max size as
            # `_MultipartParserProtocol.dataReceived` errs at >=
```

2024-07-01 23:52 UTC, H-Shay commented on tests/rest/client/test_media.py
> +# @parameterized_class(("test_image",), input_values)
no just a brain-dead leftover from debugging - same as below, i've fixed

2024-07-02 09:56 UTC, anoadragon453 approved these changes
Thanks for sticking with this. I've added on a documentation change. This now LGTM!

2024-07-02 13:06 UTC, anoadragon453 commented
The CI failure is fixed by https://github.com/element-hq/synapse/pull/17389, and will be merged to `develop` when today's RC goes out.

2024-07-02 13:07 UTC, merged

2024-08-05 18:14 UTC, Xiretza reviewed
Basic blunder of assuming HTTP headers are case-sensitive.

2024-08-05 18:14 UTC, Xiretza commented on synapse/http/matrixfederationclient.py
> +            raw_content_type = headers.get(b"Content-Type")
HTTP headers are case-insensitive. Because they were for some reason previously loaded into a `dict`, rather than using `getRawHeaders()`, this breaks.

2024-08-05 18:14 UTC, Xiretza commented on synapse/media/media_repository.py
> +            if b"Content-Type" in headers:
Presumably same here.

2024-08-05 18:14 UTC, Xiretza commented on synapse/http/client.py
> +                if data[start:end] == b"Location":
Same here.

2024-08-05 20:04 UTC, turt2live commented
@Xiretza an issue with more context would be appreciated. Old PRs are not a good place to report issues.

2024-08-05 20:13 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            raw_content_type = headers.get(b"Content-Type")
I think twisted does the right thing here, as prior to #12117 `getAllRawHeaders()` did capitalize the headers before returning, and post #12117 the headers are capitalized as they are read/stored. However, I think you are correct the the `_MultipartParserProtocol` should take capitalization into account when attempting to match header fields.

2024-08-05 20:14 UTC, H-Shay commented on synapse/http/matrixfederationclient.py
> +            raw_content_type = headers.get(b"Content-Type")
I'll fix in a forthcoming PR.

2024-08-08 18:47 UTC, Xiretza commented on synapse/http/matrixfederationclient.py
> +            raw_content_type = headers.get(b"Content-Type")
I've opened an issue so this doesn't fall through the cracks: #17544