Limit size of presence EDUs
element-hq/synapse pull request #17371
Opened 2024-06-28 10:45 UTC by erikjohnston

Otherwise they are unbounded.

2024-06-28 14:47 UTC, richvdh commented
Should we have something in the spec about this, so that federating servers can safely apply a request size limit without breaking things?

2024-06-28 15:41 UTC, erikjohnston commented
> Should we have something in the spec about this, so that federating servers can safely apply a request size limit without breaking things?

Yes, we should mandate a limit on the request size

2024-07-01 09:24 UTC, anoadragon453 requested changes
LGTM thanks. Could you add a quick unit test to test the limiting behaviour?

2024-07-01 09:24 UTC, anoadragon453 commented on synapse/federation/sender/per_destination_queue.py
> +            while self.queue._pending_presence and len(presence_to_add) < 50:
Could you extract this into a global somewhere?

2024-07-01 09:24 UTC, anoadragon453 commented on changelog.d/17371.misc
> +Limit size of presence EDUs.
```suggestion
Limit size of presence EDUs to 50 entries.
```

2024-07-01 11:47 UTC, anoadragon453 approved these changes
Looks great, thank you!

2024-07-01 11:48 UTC, merged

2024-09-14 15:29 UTC, ansiwen commented
This didn't fix the issue for us and others, see https://github.com/element-hq/synapse/issues/17035#issuecomment-2307156054 and https://github.com/element-hq/synapse/issues/17035#issuecomment-2351029837. I could mitigate the issue by going down with the limit to 25, but I think we need a real size limit, either per event or at least per EDU.