MSC3861: load the issuer and account management URLs from OIDC discovery
element-hq/synapse pull request #17407
Opened 2024-07-08 10:03 UTC by sandhose

This will help mitigating any discrepancies between the issuer configured and the one returned by the OIDC provider.

This also removes the need for configuring the `account_management_url` explicitely, as it will now be loaded from the OIDC discovery, as per MSC2965.

Because we may now fetch stuff for the .well-known/matrix/client endpoint, this also transforms the client well-known resource to be asynchronous.

2024-07-08 10:13 UTC, sandhose commented on synapse/rest/well_known.py
> -        return json_encoder.encode(r).encode("utf-8")
Changes here don't change the response when the WK can be built:

Before:

```
curl -i localhost:8008/.well-known/matrix/client
HTTP/1.1 200 OK
Server: Synapse/1.110.0
Date: Mon, 08 Jul 2024 10:10:19 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date, If-Match, If-None-Match
Access-Control-Expose-Headers: ETag, Location, X-Max-Bytes
Content-Type: application/json
Content-Length: 178

{"m.homeserver":{"base_url":"https://oidc.sandhose.fr/"},"org.matrix.msc2965.authentication":{"issuer":"https://oidc.sandhose.fr/","account":"https://oidc.sandhose.fr/account/"}}
```

After:

```
curl -i localhost:8008/.well-known/matrix/client
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Server: Synapse/1.110.0
Date: Mon, 08 Jul 2024 10:10:57 GMT
Content-Type: application/json
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date, If-Match, If-None-Match
Access-Control-Expose-Headers: ETag, Location, X-Max-Bytes

{"m.homeserver":{"base_url":"https://oidc.sandhose.fr/"},"org.matrix.msc2965.authentication":{"issuer":"https://oidc.sandhose.fr/","account":"https://oidc.sandhose.fr/account/"}}
```


It does although change the response when the public_baseurl isn't set:

Before:

```
curl -i localhost:8008/.well-known/matrix/client
HTTP/1.1 404 Not Found
Server: Synapse/1.110.0
Date: Mon, 08 Jul 2024 10:13:35 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date, If-Match, If-None-Match
Access-Control-Expose-Headers: ETag, Location, X-Max-Bytes
Content-Type: text/plain
Content-Length: 25

.well-known not available
```

After:

```
curl -i localhost:8008/.well-known/matrix/client
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Server: Synapse/1.110.0
Date: Mon, 08 Jul 2024 10:13:10 GMT
Content-Type: application/json
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Authorization, Date, If-Match, If-None-Match
Access-Control-Expose-Headers: ETag, Location, X-Max-Bytes

{"errcode":"M_NOT_FOUND","error":".well-known not available"}
```

Which is IMO perfectly acceptable

2024-07-11 11:01 UTC, reivilibre requested changes
seems sensible other than a couple of concerns

2024-07-11 11:01 UTC, reivilibre commented on synapse/rest/well_known.py
> +            account_management_url = await auth.account_management_url()
does this make 2 discovery/metadata requests one after the other? (maybe I did read wrong, or maybe we do need the caching :-p)

2024-07-11 14:28 UTC, sandhose commented on synapse/api/auth/msc3861_delegated.py
> +            metadata = await self._load_metadata()
Good catch! This should have been `self._issuer_metadata.get()`, which is a `RetryOnExceptionCachedCall` wrapper around `_load_metadata`

2024-07-11 14:28 UTC, sandhose commented on synapse/api/auth/msc3861_delegated.py
> +            metadata = await self._load_metadata()
Same

2024-07-11 14:28 UTC, sandhose commented on synapse/rest/well_known.py
> +            account_management_url = await auth.account_management_url()
The cache should dedupe the call

2024-07-11 14:28 UTC, sandhose commented on synapse/api/auth/msc3861_delegated.py
> +        """
I guess the problem is that the issuer in the config is used for discovery, and might be slightly different than the one you should actually advertise. Client will fail if the issuer advertised by `/auth_issuer` is not exactly the same as the one in `{issuer}/.well-known/openid-configuration`. We've had problems in the past of mismatches because of trailing slashes being in one place but not at the other one

So IMO, it can be confusing, but I think that pragmatically this is the right precedence

2024-07-15 12:54 UTC, reivilibre commented on synapse/api/auth/msc3861_delegated.py
> +        """
Hmm, even still, it still feels wrong to me. Suppose the homeserver fails to fetch the discovery at some point, you're still going to hand out the wrong issuer value to clients then, it will just be extra confusing that this was caused by the discovery failing.

2024-07-15 12:56 UTC, reivilibre approved these changes
cache changes OK

still not sold about the precedence but if you really think it's best, then I'm not going to insist

2024-07-15 12:57 UTC, sandhose commented on synapse/api/auth/msc3861_delegated.py
> +        """
That's a really good point. Should we log a warning if there is a mismatch, but still work? Because the discovery has to work just *once* in Synapse's lifetime, then everything is cached, so hopefully that sort of outage would be very temporary

2024-07-15 13:46 UTC, reivilibre commented on synapse/api/auth/msc3861_delegated.py
> +        """
Can we refuse to start up instead? I think this would be justified for what is a configuration error. The problem with warnings is that virtually nobody reads them.

I think by 'once in Synapse's lifetime' you mean once every process lifetime?

2024-08-30 08:29 UTC, sandhose commented on synapse/api/auth/msc3861_delegated.py
> +        """
I think you're right. I preferred to not catch the error if it fails loading. The impact of this, is that `/.well-known/matrix/client` and `/_matrix/client/*/auth_issuer` will 501 in case Synapse was never able to contact MAS, instead of potentially showing wrong informations. I think this is better

2024-08-30 13:01 UTC, sandhose commented
@reivilibre I merged develop back, tweaked stuff after the merging of #17509, and made it so that it 500 when it can't load the issuer metadata, instead of potentially wrongly falling back

2024-08-30 13:04 UTC, reivilibre approved these changes

2024-08-30 14:04 UTC, merged