Prepare for authenticated media
element-hq/synapse pull request #17433
Opened 2024-07-11 04:23 UTC by H-Shay

As part of the rollout of [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3916-authentication-for-media.md) this PR adds support for designating authenticated media and ensuring that authenticated media is not served over unauthenticated endpoints.

Should be reviewable commit-by-commit.

2024-07-11 04:32 UTC, H-Shay commented on synapse/config/repository.py
> +            "enforce_authenticated_media", False
Two questions:
1. Should this be one config option? Something like `enable_authenticated_media`?
2. Should this option be documented in the config manual, since we going to switch it on default and strongly encourage it's use?

2024-07-11 04:33 UTC, H-Shay commented
@erikjohnston - hoping you'll be able to take a look and let me know if this is in alignment with what we discussed

2024-07-11 13:05 UTC, reivilibre commented on synapse/config/repository.py
> +            "enforce_authenticated_media", False
I think documenting any config option (except experimental ones) is worth doing, even if you discourage changing it and outline the plans for the default value of the option. May also be worth saying when the option is expected to be removed (which I imagine we will do?)

2024-07-16 10:19 UTC, erikjohnston commented
@H-Shay This looks good to me, but would like someone else on the team to review the approach/code just in case.

2024-07-16 10:21 UTC, erikjohnston commented on synapse/config/repository.py
> +            "enforce_authenticated_media", False
> 1. Should this be one config option? Something like `enable_authenticated_media`?

I'm in two minds a bit here. Having two gives us more flexibility, but not actually sure of the use case. The only thing that comes to mind is if we change the defaults at different times, but then I think we wouldn't want to do that at all.

2024-07-16 11:17 UTC, reivilibre requested changes
nothing major, just tidbits

2024-07-16 11:17 UTC, reivilibre commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +ALTER TABLE local_media_repository ADD COLUMN authenticated BOOLEAN;
should we have a `DEFAULT` value here, and make it `NOT NULL`?

It would be nice to add a comment describing the semantics of the value here, even briefly. If it's a nullable column, that should be described too, which is why I'm tempted to suggest making this NOT NULL.

2024-07-16 11:17 UTC, reivilibre commented on synapse/media/media_repository.py
> +                    raise NotFoundError()
maybe collapse into `if not media_info or media_info.authenticated`, unless having these two separate is really important for readability, then maybe `elif`?

2024-07-16 11:17 UTC, reivilibre commented on synapse/media/thumbnailer.py
> +                raise NotFoundError
this might be missing `()`..? maybe? (and below)

2024-07-16 11:18 UTC, reivilibre commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +--
also, the bool columns in this file need to be declared as bool columns in the portdb script I think :S, if that's still a thing

2024-07-16 20:47 UTC, H-Shay commented on synapse/config/repository.py
> +            "enforce_authenticated_media", False
I also went back and forth about making it one config option, and I *think* in the end it makes slightly more sense to make it one, essentially for the reasons you listed - I couldn't really think of a case where the two would be set independently of each other. I am going to switch it to one - this will also make documentation clearer. If anyone comes up with a reason to switch it back let me know...

2024-07-16 22:11 UTC, H-Shay commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +ALTER TABLE local_media_repository ADD COLUMN authenticated BOOLEAN;
I guess the default could be `False`, although the code essentially assumes any media item for which this column isn't `True` is unauthenticated so I think the null works (but is probably unclear, as you are pointing out)- setting the default might make that clearer. Essentially all existing media in the table should be either null or False once the column is added, but I can make that clearer.

2024-07-16 22:35 UTC, H-Shay commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +--
good catch, forgot about that!

2024-07-17 09:59 UTC, erikjohnston commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +ALTER TABLE local_media_repository ADD COLUMN authenticated BOOLEAN;
Note that setting a `DEFAULT` means that the table needs to get rewritten to insert the new values, which takes a while. Leaving it as NULLABLE is somewhat annoying but by far the easiest.

2024-07-17 10:18 UTC, sandhose commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +ALTER TABLE local_media_repository ADD COLUMN authenticated BOOLEAN;
This isn't the case anymore since Postgres 11: https://www.dbi-services.com/blog/postgresql-11-instant-add-column-with-a-non-null-default-value/

2024-07-17 10:46 UTC, reivilibre approved these changes
I'm happy with this, just some fiddling with the documentation

2024-07-17 10:46 UTC, reivilibre commented on docs/usage/configuration/config_documentation.md
> +enable_authenticated_media
```suggestion
enable_authenticated_media: true
```

2024-07-17 11:19 UTC, erikjohnston commented on synapse/storage/schema/main/delta/86/01_authenticate_media.sql
> +ALTER TABLE local_media_repository ADD COLUMN authenticated BOOLEAN;
:exploding_head:

2024-07-17 18:01 UTC, H-Shay commented on docs/usage/configuration/config_documentation.md
> +---
I'd like to get @turt2live's opinion on this - perhaps it would make sense to link to the blog post announcing the freeze? I think for now though we can merge this (I'd like to get it into the next rc so people can test against it on beta.matrix.org) and figure out how to handle the upgrade notes, etc soon.

2024-07-17 18:03 UTC, H-Shay commented
Doc changes are done, @reivilibre can you hit the merge button if you are satisfied with the result?

2024-07-22 09:33 UTC, merged

2024-07-23 17:51 UTC, turt2live commented on docs/usage/configuration/config_documentation.md
> +---
Server operators are generally going to be increasingly incentivized to ensure this option is actually set to `true` rather than `false`, regardless of client breakage. When we change the default to `true` we should definitely call out matrix.org's plan as reference, but I wouldn't include language about setting it to `false`.

2024-07-24 15:56 UTC, turt2live commented on docs/usage/configuration/config_documentation.md
> +---
From brief discussion in backend internal: we should provide users with instructions on how to set it to `false`, but we can have the changelog read as eventually removing the option (making the feature inevitable)