WIP/PoC of storing whether we have sent rooms down to clients
element-hq/synapse pull request #17447
Opened 2024-07-15 13:22 UTC by erikjohnston

This is just a suggestion for what the API might look like for storing which rooms we have/have not sent down a sliding sync connection. This is not hooked up at all.

The basic idea is that we introduce a new token for a sliding sync connection, which stores the mapping of room to room "status" (i.e. have we sent the room down?). This token allows us to handle duplicate requests properly. In future it can be used to store more "per-connection" information safely.

In future this should be migrated into the DB, so its important that we try to reduce the number of syncs where we need to update the per-connection information. In this PoC this only happens when we: a) send down a set of room for the first time, or b) we have previously sent down a room and there are updates but we are not sending the room down the sync (due to not falling in a list range)

2024-07-16 08:38 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    # `(user_id, conn_id)` -> `token` -> `room_id` -> `HaveSentRoom`
Yeah, was wondering if we could do something here. My main concern/confusion was what happens if the stream ordering doesn't increase between syncs? Do we ever need to send down rooms in that case? Maybe for pagination? And then I decided it was easier to introduce a new token than try and figure it out :shrug:

2024-07-16 08:45 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +        previously_state = HaveSentRoom.previously(last_room_token)
I had *huge* problems with the naming

2024-07-16 16:18 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    # `(user_id, conn_id)` -> `token` -> `room_id` -> `HaveSentRoom`
The concerns make sense while trying to initially work through the problem and just not wanting to worry about possible edge cases that pile on complexity :+1: 

I guess using minimum `stream_ordering` suffers from the requests being resent problem. If you make a request with `m50~2.55`, we have things stored at `50` for the `prev_room_token`, but say the `next_room_token` is still `m50~2.66` (minimum `stream_ordering` didn't advance), we will overwrite the same `50` position. So if someone retries their `m50~2.55` request, they will miss anything between `m50~2.55` and `m50~2.66`.

I'm glad to think through this and rule it out with a reason/scenario though.

2024-07-17 15:31 UTC, erikjohnston commented
@MadLittleMods Sorry for force pushing, but a bunch of things changed and I felt it was probably easier for people to review from scratch. This can be reviewed commit-by-commit. It depends on #17452.

There's a couple of TODOs, but I think they can wait for a separate PR.

2024-07-17 17:00 UTC, MadLittleMods commented on synapse/types/rest/client/__init__.py
> +            any one time.
> If this is missing, only 1 sliding sync connection can be made to the server at any one time.

I feel like this is more, only 1 sliding sync connection allowed per `conn_id`

It doesn't matter if it's empty for `foo`, you can't have multiple of either.

2024-07-17 18:04 UTC, MadLittleMods requested changes
This is exciting to see!

2024-07-17 18:04 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        """
It would be good to add a test with a room for each live, previous, never scenario (label each kind of room) during an incremental sync.

2024-07-18 11:04 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +            self._connections[(user_id, conn_id)] = sync_statuses
Yeah, and it reduces the size of the `_connections` dict by not having "empty" entries.

2024-07-18 12:53 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +            if i == from_token.connection_token
```suggestion
            connection_token: room_statuses
            for connection_token, room_statuses in sync_statuses.items()
            if connection_token == from_token.connection_token
```

2024-07-18 13:06 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +            assert to_bound is not None
I've ended up swapping the names, and then adding a note when we call `paginate_room_events` that we're using the bounds swapped. I think this is probably clearer?

2024-07-18 13:15 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +            conn_id=sync_config.connection_id(),
Thinking about it, I think the easiest way to avoid confusion is to just pass in `sync_config` and then the store itself can decide how to generate a unique per-connection key.

2024-07-18 14:02 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        """
I've added some unit tests for `get_room_sync_data`, as we can't test this through API calls until we fix the TODO.

2024-07-18 16:35 UTC, MadLittleMods commented on CHANGES.md
> +
The diff has gone wonky since the `develop` merge vs the base branch

2024-07-19 12:27 UTC, erikjohnston commented on CHANGES.md
> +
Oops

2024-07-19 16:11 UTC, MadLittleMods commented on synapse/types/rest/client/__init__.py
> +            any one time.
The new comment suffers from the same problem:

https://github.com/element-hq/synapse/blob/01f1dca71092391a8a9e8398002c0fcf9d434d17/synapse/types/rest/client/__init__.py#L123-L124

```
conn_id: An optional string to identify this connection to the server.
     Only one sliding sync connection is allowed per given conn_id (empty or not).
```


If we want to improve on the context:

```
conn_id: An optional string to identify this connection to the server.
    Each unique `conn_id` allows for one concurrent sliding sync connection (empty or not).
    Multiple concurrent connections are possible with different `conn_id` values.
```

2024-07-19 16:15 UTC, MadLittleMods commented on synapse/types/handlers/__init__.py
> +        # (if conn ID is empty then the client can't have multiple sync loops)
This comment moved in https://github.com/element-hq/synapse/pull/17447/commits/14eb781905fb52a8caf4e579125d1843085d4508 to
https://github.com/element-hq/synapse/blob/01f1dca71092391a8a9e8398002c0fcf9d434d17/synapse/handlers/sliding_sync.py#L2127-L2129

2024-07-19 16:24 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            conn_id=sync_config.connection_id(),
The `_get_connection_key(...)` pattern looks nice :+1:

2024-07-19 16:26 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            # Initial sync without a `from_token` starts a `0`
My own typo from the [suggestion](https://github.com/element-hq/synapse/pull/17447#discussion_r1681421844):

```suggestion
            # Initial sync without a `from_token` starts at `0`
```

2024-07-19 16:45 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                # reversed.
This comment reads a bit ambiguous to me. We do want to get the "latest events first" in terms of filling up the `limit`. When I read this, I also get confused about it trying to describe the order of events we want. Especially, since we actually want the events in ascending order in the end so we `timeline_events.reverse()` below (oldest to newest events).

I think it's more that we're paginating backwards that needs to be called out:

```suggestion
                # The bounds are reversed so we can paginate backwards
                # (from newer to older events) starting at to_bound.
                # This ensures we fill the `limit` with the newest events first,
```

2024-07-19 17:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        """
The reason I haven't added tests specifically for the `get_room_sync_data(...)` function is because whatever test scenarios we add here just need to be duplicated again in the integration tests `tests/rest/client/test_sync.py` (`SlidingSyncTestCase`).

Why can't we add tests there until the TODO is fixed?

I see that we can't test any `previously` scenarios directly via the API but we can still `record_rooms(...)` manually with a `FIXME` to do it for real.

2024-07-23 10:38 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +                # reversed.
yeah makes sense

2024-07-24 17:19 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +            },
We might as well start using the `do_sync(...)` helper to start making these sync request bodies match

2024-07-24 17:19 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        """
^ Still think we should remove the `get_room_sync_data(...)` tests.

It looks like a few tests have been added to `tests/rest/client/test_sync.py` that cover `NEVER` and `LIVE` around `required_state`. We can add a `PREVIOUS` test by faking it with a manual `record_rooms(...)` call with a `TODO` note to do it for real with a gappy incremental sync once we start filling in `unsent_room_ids` (ideally with the correct code just commented out) .

We should also add some timeline tests there.

2024-07-24 17:20 UTC, MadLittleMods commented on synapse/types/handlers/__init__.py
> +        # (if conn ID is empty then the client can't have multiple sync loops)
^ Still relevant

2024-07-24 17:46 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    Note: This is NOT safe to run in a worker setup.
Since there is no choice whether to use `SlidingSyncConnectionStore`, we're basically saying that if you have sliding sync enabled, you shouldn't be using workers. Any suggestion for people using workers? How do we plan to run this on `matrix.org`?

I'm assuming this is unsafe because although we partition requests to workers by `room_id`, if more/less workers get added, rooms will re-distribute given the `mod` calculation I assume we're doing against the `room_id`. And then we might have a really old `PREVIOUSLY` `room_status.last_token` that isn't accurate when a request comes in again.

It's fine if we have `NEVER` stored because that's just the same as an empty store. And `LIVE` is fine because we'll use the `from_token` as normal.

2024-07-24 17:46 UTC, MadLittleMods commented on synapse/types/rest/client/__init__.py
> +            any one time.
^ Still relevant

2024-07-24 19:41 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                initial = False
I feel like we should be careful with how far back we allow this to go. If I store `PREVIOUSLY` for a room and never see it again until a year later, that is going to be too many updates and we should have just done `initial = True` for them

2024-07-25 16:50 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    Note: This is NOT safe to run in a worker setup.
My assumption is we'll probably want to store this stuff in the DB (or maybe redis), which should be fine as we shouldn't write to it most of the time.

Right now on matrix.org we only have the one worker set up to handle sliding sync traffic, so this isn't a problem for now.

The reason it isn't safe is that you might get a collision of different connection positions on different workers, e.g. for the same connection a connection position of 5 might have totally different states on worker A and worker B

2024-07-25 16:51 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +                initial = False
Yup, that's true. We should add a limit to the current delta stream and set `initial = True` if there are too many.

2024-07-25 17:24 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        """
Ok, I've removed the `get_sync_data` tests and have added tests for `PREVIOUSLY` state in the integration tests with a `FIXME`.

2024-07-25 17:25 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +                initial = False
I might leave that to a separate PR?

2024-07-25 18:15 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                initial = False
Sure, let's just leave a `TODO`

2024-07-25 18:17 UTC, MadLittleMods commented on synapse/types/handlers/__init__.py
> +        # (if conn ID is empty then the client can't have multiple sync loops)
Updated :white_check_mark:

2024-07-25 18:17 UTC, MadLittleMods commented on synapse/types/rest/client/__init__.py
> +            any one time.
Updated :white_check_mark:

2024-07-25 18:38 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    Note: This is NOT safe to run in a worker setup.
Ahh, thanks for clarifying the actual reason!

2024-07-25 18:52 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        _, initial_from_token = self.do_sync(sync_body, tok=user1_tok)
Feels like we might want to assert these assumptions:

```py
self.assertListEqual(
    list(response_body["lists"]["foo-list"]["ops"]),
    [
        {
            "op": "SYNC",
            "range": [0, 0],
            "room_ids": [room_id1],
        }
    ],
    response_body["lists"]["foo-list"],
)
```

2024-07-25 19:01 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +            room_subscriptions={},
Since these fields aren't used in `record_rooms(...)` and they aren't matching our requests anyways, we might as well get rid of them to tighten things up

```suggestion
```

2024-07-25 19:02 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +            extensions=None,
Since these fields aren't used in `record_rooms(...)` and they aren't matching our requests anyways, we might as well get rid of them to tighten things up

```suggestion
```

2024-07-25 19:11 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_previously(self, limited: bool) -> None:
Seems like we should have `timeline` tests for `LIVE`/`NEVER`. I suppose we already have `LIVE` tests given that in our existing tests we're doing an initial sync to get a `from_token`.

2024-07-25 19:13 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_previously(self, limited: bool) -> None:
Seems like we need a test for `required_state in the `PREVIOUSLY` case

2024-07-25 19:13 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        we've already seen.
```suggestion
        we've already seen (LIVE).
```

2024-07-26 09:18 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +            extensions=None,
Ooo, I just assumed they were required fields.

2024-07-29 17:53 UTC, MadLittleMods requested changes

2024-07-29 17:53 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    Note: This is NOT safe to run in a worker setup.
```suggestion
    Note: This is NOT safe to run in a worker setup because connection positions will
    point to different sets of rooms on different workers. e.g. for the same connection,
    a connection position of 5 might have totally different states on worker A and
    worker B.
```

2024-07-29 17:53 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    consider the room *not* sent when we get the request again.
(to separate it from the paragraph above about this not being safe for workers)

```suggestion
     One complication that we need to deal with here is needing to handle requests being
    resent, i.e. if we sent down a room in a response that the client received, we must
    consider the room *not* sent when we get the request again.
```

2024-07-29 17:53 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            connection_token = from_token.connection_position
We should update all of these `connection_token` references to `connection_position` now

2024-07-29 17:53 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        Test getting room data where we have not previously sent down the room
```suggestion
        Test getting room data where we have NEVER sent down the room before
```

2024-07-29 17:53 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_never(self) -> None:
`test_incremental_sync_full_state_never` overlaps with `test_incremental_sync_full_state_new_room`

It also looks like we're mixing `timeline` and `required_state` testing which would be more clear if it was separated. The setup isn't the same.

2024-07-29 17:53 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_never(self) -> None:
The test names are still not clear to me:

```
    test_incremental_sync_full_state_never ...                             [OK]
    test_incremental_sync_full_state_new_room ...                          [OK]
    test_incremental_sync_full_state_previously_0 ...                      [OK]
    test_incremental_sync_full_state_previously_1 ...                      [OK]
    test_incremental_sync_full_state_previously_state ...                  [OK]
    test_incremental_sync_incremental_state ...                            [OK]
```

`test_incremental_sync_full_state_never` -> `test_incremental_sync_room_never_sent` would be better.


We could better match the existing tests:

`test_rooms_required_state_...` -> `test_rooms_required_state_never_sent_incremental_sync`
`test_rooms_timeline_...` -> `test_rooms_timeline_previously_sent_incremental_sync`

2024-07-29 19:02 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_never(self) -> None:
Hopefully that naming makes sense, they all now start with either `test_rooms_timeline_incremental_sync_` or `test_rooms_required_state_incremental_sync_`

2024-07-29 19:03 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_never(self) -> None:
Yeah, I've deleted `test_incremental_sync_full_state_new_room` and instead have two NEVER tests, one for timeline and one for required state.

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        # We now send down some state in room1 (depending on the test param).
```suggestion
        # We now send down some state in room1
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        self.assertEqual(response_body["rooms"][room_id1]["initial"], True)
I don't think we need those `timeline` checks in the `required_state` test,

```suggestion
        self.assertEqual(response_body["rooms"][room_id1]["initial"], True)
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        Test getting room data where we have NEVER sent down the room before
```suggestion
        Test getting `required_state` where we have NEVER sent down the room before
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        )
```suggestion
        )
        self.assertEqual(response_body["rooms"][room_id1]["initial"], False)
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        )
```suggestion
        )
        self.assertEqual(response_body["rooms"][room_id1]["initial"], False)
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        self._assertRequiredStateIncludes(
```suggestion
        self.assertEqual(response_body["rooms"][room_id1]["initial"], False)
        self._assertRequiredStateIncludes(
```

2024-07-29 20:08 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        """
Continued in https://github.com/element-hq/synapse/pull/17447#discussion_r1695641117

2024-07-29 20:10 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +    def test_incremental_sync_full_state_never(self) -> None:
Thanks for updating the tests! The naming before was making my head spin

Updated names for reference:
```
test_rooms_required_state_incremental_sync_LIVE
test_rooms_timeline_incremental_sync_PREVIOUSLY
test_rooms_required_state_incremental_sync_PREVIOUSLY
test_rooms_required_state_incremental_sync_NEVER
test_rooms_timeline_incremental_sync_NEVER
```

2024-07-29 20:10 UTC, MadLittleMods approved these changes
Looks good after some minor test changes :+1:

2024-07-29 21:45 UTC, merged

2024-08-20 09:12 UTC, kosmos commented
@erikjohnston I see that there have been a lot of commits lately to implement sliding sync functionality in Synapse. Could you please tell me if this means that in the near future Synapse will support everything needed for Element X without the additional installation of matrix-org/sliding-sync and matrix-org/matrix-authentication-service? If so, do you have any time expectations for when this will be ready?

The question is due to the great complexity of implementing matrix-org/matrix-authentication-service. I would like to know if Synapse will support everything necessary for Element X and oidc_providers soon, it will greatly simplify the implementation of Element X.

2024-08-20 09:46 UTC, erikjohnston commented
Hi @kosmos, this PR isn't really the right place to discuss this, but briefly: we're hoping to have native synapse support for sliding sync soon that would work with EX. However, you'd still need MAS to use SSO with EX