Use a new token format for sliding sync
element-hq/synapse pull request #17452
Opened 2024-07-17 11:16 UTC by erikjohnston

This is in preparation for adding per-connection state.

2024-07-17 16:36 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
Instead of making an initial request to get a token, I think we should just generate one how we were doing before with a `0` `connection_token`. This way when we start to actually diff what the user has already seen, we don't mess with these tests.

I think we should just have another set of tests that stresses the diffing functionality. `test_connection_tracking_xxx_etc`

2024-07-17 16:45 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
Adding an `Attributes` docstring would be helpful to describe what `connection_token` is used for how it works (incremented because ...)

2024-07-17 16:46 UTC, MadLittleMods requested changes
.

2024-07-17 16:56 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
`connection_token` is pretty easily confused to me with `connection_id`. Especially now that I'm reviewing https://github.com/element-hq/synapse/pull/17447

`connection_token` is not bad for what it does but it's so close to the other thing.

Better names?

`connection_position`?

2024-07-18 10:59 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
I disagree, I think its more useful to test what we want the APIs to actually do? Yes, we need to change one or two tests when we add the connection tracking, but my view is that those tests are *wrong* as they are checking for things that the API should not be returning. We're essentially testing behaviour that can never be encountered through real world usage, and so what benefit do those tests/assertions have?

2024-07-18 11:00 UTC, erikjohnston commented on synapse/types/__init__.py
> +    connection_token: int
Good point. Thinking about it, maybe these `_token` prefixes are redundant and we should just call them `stream` and `connection`. Usages would then become e.g. `from_token.connection`.

2024-07-18 15:07 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
I want to treat the diff'ing as an extra thing (since it is)

And it's as if there is no cache built up.

2024-07-18 15:10 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
Your variation also makes sense on its own but feel like it still suffers from the hard to differentiate problem (nuance).

2024-07-19 09:10 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
Hmm, right. I think that would be better expressed as what happens when the server-side cache gets cleared? We can add a `.clear()` to the store to simulate that?

2024-07-19 09:10 UTC, erikjohnston commented on synapse/types/__init__.py
> +    connection_token: int
I can't think of a better name for any of these things though

2024-07-19 15:47 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
:shrug: That or just a comment like this:

```py
def test_xxx(...) -> None:
    """
    ...
    Make sure we're doing the right thing during an incremental sync without any cache.
    """

    # Doing an incremental sync with a fresh token from `0` just simulates a request when
    # there is no cache built up.
    from_token = SlidingSyncStreamToken(self.event_sources.get_current_token(), 0)
```

2024-07-19 15:59 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
Any of these seem at-least slightly better to me: `connection_position`, `connection_cursor`, `connection_progress_token`, `connection_offset`, `sync_position` 

---

There is also a weird side-effect of removing the `_token` prefixes:

`from_token.stream.room_key.stream`

Keeping it as `stream_token` isn't bad: `from_token.stream_token.room_key.stream`

2024-07-22 16:28 UTC, erikjohnston commented on synapse/types/__init__.py
> +    connection_token: int
I don't really see how adding any of those suffixes really help? I don't see how `from_token.connection` is any less clear than, say, `from_token.connection_cursor`? It's clear its the `connection` part of the token

For the `from_token.stream.room_key.stream` thing, yeah, not sure what else to name it other than `stream` or `stream_token`. I guess ideally we'd subclass the `StreamToken`, but that is a bit fiddly to get the (de)serialization right

2024-07-23 02:10 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
To me, it makes it seem like `connection` is a fully-realized object vs `connection_id` is just an ID to reference it. Similar to `event` vs `event_id`. But it's even worse because `from_token.connection` is totally different than the `conn_id`/`connection_id`.

It's not that I can't figure it out but it's just a mess 😵

The extra suffix makes it more obvious to me that we're talking about different things.

Up to you :fast_forward:

2024-07-23 02:14 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
I'd prefer to keep the base set of tests with less compounding behaviors.

Then we can add separate tests with the cache that minimally test the cache/diff behaviors. Essentially, just a test for `timeline` diff and one for `required_state` diff.

2024-07-23 15:54 UTC, erikjohnston commented on synapse/types/__init__.py
> +    connection_token: int
Oh, I suppose there's a conflict between `from_token.connection` meaning either a) an ID of the connection, or b) the "connection" part of the token. Nyarghghghgh. I'm leaning back to just using `connection_token` and `stream_token`? Token is pretty much the standard term we use generally.

2024-07-23 16:12 UTC, MadLittleMods commented on synapse/types/__init__.py
> +    connection_token: int
Yes, exactly! That's what I was trying to convey in the first message

With the additional layer that token vs ID seem kinda interchangeable to me which is why I suggested another suffix for this one.

2024-07-23 17:04 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
None of the tests required changing, so I don't really see why compounding behaviours is a problem here.

In general, I much prefer integration style tests to be as close to real world API usage as possible, as a) you're more likely to catch bugs users will actually hit, and b) it reduces the how much the tests depend on how the code currently works. This PR is a prime example of this, where we want to change the format of the token without any behavioural changes, and yet we need to change (and therefore understand) a bunch of tests where *what* they're testing hasn't changed.

If we change to instansiate `SlidingSyncStreamToken` directly then when we come to move the per-connection state into the DB we'll likely have to change all these tests again. This is because we'll likely simply reset the connection if we don't recognise the connection token. At which point we'll have had to change all these tests twice, while the behaviour those tests are checking hasn't changed.

For the PR that adds the in-memory cache we should absolutely add tests to ensure things work when it gets reset.

2024-07-23 17:04 UTC, erikjohnston commented on synapse/types/__init__.py
> +    connection_token: int
Ok, I've changed to `stream_token` and `connection_position`

2024-07-23 18:45 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
:+1: on touching less internals

The thing I'm looking out for is treating the connection tracking/diffing as a separate layer to everything else. I think it simplifies the understanding necessary and we can guarantee some functionality regardless of how it changes in the future.

For reference, `test_rooms_required_state_incremental_sync` did have to change

---

> This PR is a prime example of this, where we want to change the format of the token without any behavioural changes, and yet we need to change (and therefore understand) a bunch of tests where what they're testing hasn't changed.

On this note, in terms of making the initial Sliding Sync request to grab the `from_token`, should we match the request parameters to the incremental sync after? (currently, there are mismatches)

Currently, only the `ranges` option can affect future requests. But as an example (that I don't think we will implement but an example) of how `timeline_limit`/`required_state` options could affect requests in the future, the connection tracking could be even better and track on a per-event level which would affect the `timeline`/`required_state` in the response.

I think my preference would be to obtain the `from_token` with the most simple request to avoid any of that:

```py
channel = self.make_request(
    "POST",
    self.sync_endpoint,
    {},
    access_token=user1_tok,
)
self.assertEqual(channel.code, 200, channel.json_body)
from_token = channel.json_body["pos"]
```

The only downside to this is the "real-world"-ness of it which is a valuable aspect but can be addressed in another test if we want to check those interactions.

Matching request parameters also works for me but I worry about the connection tracking/diffing lurking in the background again.

2024-07-23 19:33 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
Quick thought: we probably do want to match, and that might be easiest if we had a helper function, something like:

```python
sync_request_body = {
    "lists": [ ... ],
}

body = self.do_sync(sync_request_body, tok=user1_tok)
from_token = body["pos"]

body = self.do_sync(sync_request_body, since=from_token, tok=user1_tok)
```

Maybe? Or just have a `from_token = self.do_sync_and_get_token(sync_request_body, tok=user1_tok)`

2024-07-23 20:06 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
@erikjohnston Looks alright :+1: I think we need access to the response `body` for assertions but could do `response, from_token = ...` as a nice shortcut for fetching the next token.

2024-07-23 20:38 UTC, erikjohnston commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
Have updated the PR with a `do_sync`. I have only changed the calls we added to get the `from_token`, as otherwise this would touch all the tests.

2024-07-23 20:47 UTC, MadLittleMods commented on synapse/types/__init__.py
> +                connection_position=connection_token,
```suggestion
            connection_position_str, stream_token_str = string.split("/", 1)
            connection_position = int(connection_position_str)
            stream_token = await StreamToken.from_string(store, stream_token_str)

            return SlidingSyncStreamToken(
                stream_token=stream_token,
                connection_position=connection_position,
```

2024-07-23 20:52 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +            sync_path += f"&pos={since}"
Does that work? (no `?` first)

`"/_matrix/client/unstable/org.matrix.simplified_msc3575/sync" + f"&pos={since}"`

2024-07-23 21:01 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +
Aside: Could move `def default_config(self)` here

2024-07-23 21:03 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
:+1: We can do the rest in a follow-up PR

2024-07-23 21:05 UTC, MadLittleMods commented on synapse/types/__init__.py
> +            per-connection state stored by Synapse.
```suggestion
        stream_token: Token representing the position of all the standard
            streams.
        connection_position: Token used by sliding sync to track updates to any
            per-connection state stored by Synapse.
```

2024-07-23 21:06 UTC, MadLittleMods approved these changes

2024-07-24 10:47 UTC, merged

2024-07-25 00:15 UTC, MadLittleMods commented on tests/rest/client/test_sync.py
> +        from_token = channel.json_body["pos"]
Updated the rest of the tests to use `do_sync(...)` in https://github.com/element-hq/synapse/pull/17482 :fast_forward: