Update config_documentation - Change example of msisdn in allowed_local_3pids
element-hq/synapse pull request #17476
Opened 2024-07-24 02:42 UTC by Bitzo

change the example configuration of msisdn in `allowed_local_3pids`, which is a bit misleading that regex pattern has leading '+'

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-07-24 02:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17476) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17476) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17476) it.</sub>

2024-07-24 11:14 UTC, anoadragon453 requested changes
Thanks for the correction! Looks like `+` shouldn't be included in msisdn's at all, so the example configuration was in fact invalid.

I think it'd be worth linking to https://spec.matrix.org/latest/appendices/#3pid-types in the documentation, so that sysadmins know what type of values to expect. Could you add that to the description of the `allowed_local_3pids` option please?

This looks good to me otherwise.

2024-07-25 01:21 UTC, Bitzo commented
> Thanks for the correction! Looks like `+` shouldn't be included in msisdn's at all, so the example configuration was in fact invalid.
> 
> I think it'd be worth linking to https://spec.matrix.org/latest/appendices/#3pid-types in the documentation, so that sysadmins know what type of values to expect. Could you add that to the description of the `allowed_local_3pids` option please?
> 
> This looks good to me otherwise.

OK, I have added that.

2024-07-25 10:58 UTC, anoadragon453 approved these changes
Looks good to me, thank you!

2024-07-25 10:58 UTC, anoadragon453 commented on changelog.d/17476.doc
> +Change the example configuration of msisdn in allowed_local_3pids, which is a bit misleading that regex pattern has leading '+'.
```suggestion
Update the [`allowed_local_3pids`](https://element-hq.github.io/synapse/v1.112/usage/configuration/config_documentation.html#allowed_local_3pids) config option's msisdn address to a working example.
```

2024-07-25 10:58 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
> +You can get more information about 3PID and the expected types of `medium` [here](https://spec.matrix.org/latest/appendices/#3pid-types).
```suggestion
More information about 3PIDs, allowed `medium` types and their `address` syntax can be found [in the Matrix spec](https://spec.matrix.org/latest/appendices/#3pid-types).
```

2024-07-25 10:58 UTC, anoadragon453 commented on docs/usage/configuration/config_documentation.md
>  3PIDs with accounts on this server, as specified by the `medium` and `pattern` sub-options.
```suggestion
3PIDs with accounts on this server, as specified by the `medium` and `pattern` sub-options.
`pattern` is a [Perl-like regular expression](https://docs.python.org/3/library/re.html#module-re).
```

2024-07-25 11:07 UTC, merged