Partially implement MSC4133 to support custom profile fields.
element-hq/synapse pull request #17488
Opened 2024-07-25 20:22 UTC by clokep

(Partial) implementation of [MSC4133](https://github.com/matrix-org/matrix-spec-proposals/pull/4133) to support custom profile fields. It is behind an experimental flag and is missing the `DELETE` verb, but this was already getting to be a big PR. Includes tests.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-07-31 11:16 UTC, anoadragon453 requested changes
A few comments, but this is definitely on the right track. Thanks for implementing this!

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +        if len(field_name) > MAX_CUSTOM_FIELD_LEN:
In Python, `len(str)` for utf-8 encoded strings will count the number of unicode codepoints, not bytes. The MSC specifies that field names should be 255 bytes in length.

You can check the byte length by instead first converting to a byte array:

```suggestion
        if len(field_name.encode("utf-8")) > MAX_CUSTOM_FIELD_LEN:
```

likewise below.

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +                "Updating avatar URL while account is suspended is not allowed.",
```suggestion
                "Updating profile information while account is suspended is not allowed.",
```

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
I think this endpoint may currently accept an empty string as a field name?

i.e. if the request path was `/_matrix/client/unstable/uk.tcpip.msc4133/profile/@bob:example.com/`

Writing a unit test for this could be useful.

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/storage/databases/main/profile.py
> +            field_name: The custom profile filed name.
```suggestion
            field_name: The custom profile field name.
```

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/storage/databases/main/profile.py
> +    async def get_profile_field(
It may be worth putting a cache on this method? In case a user posts in a large room and lots of people go to view their profile.

2024-07-31 11:16 UTC, anoadragon453 commented on synapse/storage/schema/main/delta/86/01_custom_profile_fields.sql
> +-- Copyright (C) 2024 New Vector, Ltd
This one would be copyright you!

2024-07-31 11:16 UTC, anoadragon453 commented on tests/rest/client/test_profile.py
> +        """Attempts to set a stupid custom_field should get a 400"""
```suggestion
        """Attempts to set a custom_field name or value that is too
        long should get a 400
        """
```

2024-07-31 11:23 UTC, clokep commented on synapse/handlers/profile.py
> +            # TODO This should be an unstable query.
Ah-ha, you're right! It probably needs a couple of tests added though.

2024-07-31 11:25 UTC, clokep commented on synapse/rest/client/profile.py
> +        if len(field_name) > MAX_CUSTOM_FIELD_LEN:
I think this check doesn't fully match the MSC since that talks about the fully encoded profile JSON dict.

2024-07-31 11:25 UTC, clokep commented on synapse/storage/schema/main/delta/86/01_custom_profile_fields.sql
> +-- Copyright (C) 2024 New Vector, Ltd
```suggestion
-- Copyright (C) 2024 Patrick Cloke
```

2024-07-31 11:27 UTC, clokep commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
Right, I guess that's invalid since it could be confused with returning the whole profile. The MSC should clarify this too.

2024-07-31 11:27 UTC, clokep commented on synapse/storage/databases/main/profile.py
> +    async def get_profile_field(
Would it make more sense to cache `get_profile_fields`?

2024-07-31 15:25 UTC, tcpipuk commented on synapse/handlers/profile.py
> +            # TODO This should be an unstable query.
The expectation is for the endpoint to be identical, please let me know if the MSC needs a tweak to help improve this compatibility! 🙂

2024-07-31 15:32 UTC, tcpipuk commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
I'll do that now, thanks for identifying it 👍

2024-07-31 15:36 UTC, tcpipuk commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
Is this a suitable clarification? https://github.com/matrix-org/matrix-spec-proposals/pull/4133/commits/8ebe1b108888e5a3850123c9a9e808b498224cd9

2024-07-31 17:15 UTC, anoadragon453 commented on synapse/storage/databases/main/profile.py
> +    async def get_profile_field(
Sorry, yes it would.

2024-07-31 17:18 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
Yes, though it's quite strongly worded with all those asterisks :yum: But yeah, the meaning is there.

Though if I were being pedantic, I would say "at least one byte", instead of one character.

2024-07-31 17:30 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +        if len(field_name) > MAX_CUSTOM_FIELD_LEN:
We just [had a long discussion](https://github.com/matrix-org/matrix-spec-proposals/pull/4133#discussion_r1698225294) on size limits, and concluded that 64KiB be the limit for profiles when communicating to other homeservers over federation. Homeservers can then choose to enforce that limit on the client side or not. Currently there's no defined method of negotiation, so unfortunately clients will have to try and handle `M_TOO_LARGE` responses for now.

The 255 byte limit for field names remains, but the full profile limit is missing.

For Synapse, I suggest we keep to a 64KiB limit for the whole profile for now. We could compute it entirely in the DB, which may be faster than pulling the fields out of the DB, and then computing their length in Python. Something like (untested):

PostgreSQL:

```sql
SELECT LENGTH(to_jsonb(jsonb_object_agg(name, value))::text) AS json_byte_length 
FROM profile_fields 
WHERE
  user_id = ?;
```

SQLite:

```sql
WITH json_data AS (
    SELECT json_group_object(name, value) AS json_blob
    FROM profile_fields
    WHERE user_id = ?
)
SELECT LENGTH(json_blob) AS json_byte_length
FROM json_data;
```

(SQLite doesn't support `LENGTH` function on JSON.)

2024-07-31 17:32 UTC, tcpipuk commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
As the key is required to be a string, I thought requiring 1 character would be simpler... though now I guess someone's going to use a single space 🤔

2024-08-05 08:59 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
Or an emoji with a single codepoint, but made up of multiple bytes etc. etc. :family_man_girl_boy:

2024-08-05 09:27 UTC, tcpipuk commented on synapse/rest/client/profile.py
> +    ) -> Tuple[int, JsonDict]:
Aye, I guess my concern was that a single byte of 🌎 shouldn't be valid, whereas setting an emoji as a key name should probably be allowed if someone used 📧 for email, for example?

2024-08-09 20:09 UTC, clokep commented
I pushed some changes to update / flesh out the rest of the MSC, but I haven't yet gone through @anoadragon453's comments so not worth another review yet. (If folks want to test it that would be reasonable...I'm sure it'll break.)

2024-09-08 08:57 UTC, Half-Shot commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
Could we get a `/versions` flag for this, https://github.com/tcpipuk/matrix-spec-proposals/blob/main/proposals/4133-extended-profiles.md#unstable-client-features .

Blocks progress on the client library PRs

2024-09-08 08:57 UTC, Half-Shot commented on synapse/handlers/profile.py
> +    async def get_profile_field(
Noting here that for some reason, I found that this would occasionally take a very long time to complete. I don't know if there is a lock race or something going on, but I found multiple requests to this would take up to 30s.

2024-09-08 09:14 UTC, Half-Shot commented on synapse/handlers/profile.py
> +                    raise SynapseError(404, "Profile was not found", Codes.NOT_FOUND)
N.B. Error is slightly confusing, *profile key* might be a better fit?

2024-09-08 11:41 UTC, clokep commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
Oops I think that got added afterward. Will add.

2024-09-08 21:51 UTC, Half-Shot commented on synapse/handlers/profile.py
> +    async def get_profile_field(
Like all good bugs...I'm failing to repro now. It may have been my browser being funny

2024-09-09 13:05 UTC, clokep commented on synapse/handlers/profile.py
> +    async def get_profile_field(
Maybe the index wasn't built? 🤷

2024-09-09 13:25 UTC, Half-Shot commented on synapse/rest/client/profile.py
> +    async def on_DELETE(
Just noting to update the PR body to reflect that Delete exists.

2024-09-09 19:05 UTC, clokep commented on synapse/handlers/profile.py
> +                    raise SynapseError(404, "Profile was not found", Codes.NOT_FOUND)
It could also be from the user not existing.

2024-09-09 21:52 UTC, Half-Shot commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
That's not what I'm seeing on the MSC? https://github.com/tcpipuk/matrix-spec-proposals/blob/main/proposals/4133-extended-profiles.md#unstable-client-features?

>The client feature uk.tcpip.msc4133 should be advertised on the /_matrix/client/versions endpoint when the PUT and PATCH methods are accepted on the /_matrix/client/unstable/uk.tcpip.msc4133/profile/{userId} endpoint.

Which this PR does, no?

The capability is for whether the client has the ability to write to the profile, but I don't think it is used to determine *support* for the MSC.

2024-09-10 08:24 UTC, tcpipuk commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
Hmm. It occurs to me that GET on the individual keys is also unlikely to work, so probably the MSC needs to be updated to specify a more comprehensive list of endpoints that require that capability? 🤔

2024-09-10 21:03 UTC, clokep commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
> Hmm. It occurs to me that GET on the individual keys is also unlikely to work, so probably the MSC needs to be updated to specify a more comprehensive list of endpoints that require that capability? 🤔

I thought that's technically already allowed by homeservers?

2024-09-10 21:08 UTC, clokep commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
I added the `/versions` field.

2024-09-11 09:23 UTC, tcpipuk commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
> I thought that's technically already allowed by homeservers?

It supports GET for the full profile, and individual GETs on `avatar_url` and `displayname`, but doesn't *explicitly* allow GET of other keys yet. The spec definitely already allows other fields to be *in* the profile, just never offered a way to *interact* with them.

2024-09-11 09:37 UTC, Half-Shot commented on synapse/handlers/profile.py
> +                    raise SynapseError(404, "Profile was not found", Codes.NOT_FOUND)
My motivations aren't strong enough here, and you raise a good point.

2024-09-11 13:20 UTC, clokep commented on synapse/config/experimental.py
> +        self.msc4133_enabled: bool = experimental.get("msc4133_enabled", False)
I think you can be vague and just say the flag enables this MSC using unstable identifiers.

2024-09-19 14:27 UTC, clokep commented on synapse/handlers/sso.py
> +            if "avatar_url" in profile:
I suspect I need to split this to a separate PR to make it clear what the change is.

2024-10-14 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17488) it.</sub>

2024-11-07 12:50 UTC, clokep commented
I think this is close to ready for another review. There's a few open questions on the MSC that will affect this still.

2024-12-27 17:01 UTC, wcjord commented
We're very excited to have this feature! What are the next steps?

2024-12-31 19:23 UTC, clokep commented on synapse/handlers/sso.py
> +            if "avatar_url" in profile:
This change was isolated to a separate PR: #18063.

2024-12-31 19:24 UTC, clokep commented
> We're very excited to have this feature! What are the next steps?

* Part of this was split to a separate PR as requested by the reviewer (#18063).
* After that I'll need to merge `develop` in, then this should be good for review.

2025-01-03 19:14 UTC, clokep commented
@anoadragon453 This should be ready for another review. The commits definitely became very messy so unfortunately probably needs to be reviewed as a single change.

2025-01-09 19:44 UTC, anoadragon453 requested changes
This looks great, thank you! :sparkles: 

Just a few minor points below, but nothing fundamental.

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/storage/databases/main/profile.py
> +            field_path = f'$."{field_name}"'
Should we catch this and return a 400 instead of (presumably) 500'ing?

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/handlers/profile.py
> +            target_user: the user whose avatar URL is to be changed.
```suggestion
            target_user: the user whose profile is to be changed.
```

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/handlers/profile.py
> +            raise AuthError(400, "Cannot set another user's profile")
Looks like this should be a 403 [according to the MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/4133/files#diff-e408d6c936a5ae3f7dd4386ed643830fb2191b459b35cbec73b2987d73cae439R212).

```suggestion
            raise AuthError(403, "Cannot set another user's profile")
```

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/handlers/profile.py
> +            target_user: the user whose avatar URL is to be changed.
```suggestion
        """Delete a field from a user's profile.

        Args:
            target_user: the user whose profile is to be changed.
```

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/handlers/profile.py
> +            field_name: The name of the profile field to update.
```suggestion
            field_name: The name of the profile field to remove.
```

2025-01-09 19:44 UTC, anoadragon453 commented on synapse/http/servlet.py
> +            for method in ("GET", "PUT", "POST", "DELETE", "PATCH"):
Why was this needed?

2025-01-09 19:44 UTC, anoadragon453 commented on tests/rest/client/test_profile.py
> +        self.assertEqual(channel.code, 400, channel.result)
Could you also check for the appropriate `errcode`s in this test?

2025-01-10 18:58 UTC, clokep commented on synapse/http/servlet.py
> +            for method in ("GET", "PUT", "POST", "DELETE", "PATCH"):
Oops, it no longer is!

2025-01-10 19:00 UTC, clokep commented on synapse/rest/client/capabilities.py
> +            }
The MSC says only if the spec version supports it, however. I think when we stabilize we'll want to always include it, but don't need to for now?

2025-01-10 19:02 UTC, clokep commented on synapse/rest/client/profile.py
> +            )
Copy & pasted from the other servlets which don't include it. I can add it though.

2025-01-10 19:15 UTC, clokep commented on synapse/storage/databases/main/profile.py
> +            field_path = f'$."{field_name}"'
Field names can't have double quotes actually, right? According to the [grammar](https://spec.matrix.org/v1.13/appendices/#common-namespaced-identifier-grammar) in the MSC? Maybe we should be checking that upfront at the REST layer.

2025-01-13 10:03 UTC, anoadragon453 commented on synapse/rest/client/capabilities.py
> +            }
Where do you see that? I do see:

> Once this MSC is merged, the client feature `uk.tcpip.msc4133.stable` SHOULD be advertised when these endpoints are accepted at `/_matrix/client/v3/profile/{userId}/{key_name}` until the next spec version where these endpoints are officially written into the spec, e.g.

under [Unstable Client Features](https://github.com/tcpipuk/matrix-spec-proposals/blob/d620259ac07cb38d43fdbb2880ba47a452ed6522/proposals/4133-extended-profiles.md#unstable-client-features), but that's not talking about the capabilities.

2025-01-13 11:52 UTC, anoadragon453 commented on synapse/storage/databases/main/profile.py
> +            field_path = f'$."{field_name}"'
I think it'd be worth enforcing the grammar on the C-S API. We've certainly been bitten by not doing that enough in the past!

2025-01-15 14:14 UTC, clokep commented on synapse/rest/client/capabilities.py
> +            }
From [Capabilities behavior section](https://github.com/tcpipuk/matrix-spec-proposals/blob/main/proposals/4133-extended-profiles.md#behaviour)

> **When capability is missing:** Clients SHOULD assume extended profiles are supported and that they can be created or modified, provided the response from `/versions` indicates support for a spec version that includes this proposal. If a server intends to deny some (or all) changes, it SHOULD use the capability to advertise this, improving the client experience.

I took this to mean that when stable and v1.x is released that supports this we will need to ensure it exists when you can create arbitrary fields.

For unstable, if `/versions` declare support for the unstable MSC then you include this to tell clients they can create/modify. Things, if there's no unstable flag (ie the MSC is disabled) then no need to include this.

@tcpipuk Does that sound like an accurate interpretation of the MSC? Unsure if clarifications are needed (I think the text for stable support is clear.)

2025-01-15 14:15 UTC, clokep commented on synapse/storage/databases/main/profile.py
> +            field_path = f'$."{field_name}"'
Will do! Should be easy enough. Any idea if we have a helper to do that?

2025-01-16 10:11 UTC, tcpipuk commented on synapse/rest/client/capabilities.py
> +            }
My understanding of the usual process would be: once MSC4133 is stable in a new spec version, it'll be assumed that servers advertising the spec version _will_ support profile fields _unless_ they advertise a capability that says they refuse them.

2025-01-17 02:34 UTC, clokep commented on synapse/rest/client/capabilities.py
> +            }
I did realize this is missing the `disallowed` fields though based on whether displayname/avatars can be set though. I'll update it to include that.

2025-01-20 11:12 UTC, anoadragon453 commented on synapse/rest/client/capabilities.py
> +            }
Ah, I see. So client should only assume it's enabled by default once a spec version that includes the MSC is advertised by the homeserver. That makes more sense - thanks for clarifying!

2025-01-20 11:49 UTC, anoadragon453 requested changes
A few small things, but otherwise this looks nearly good to go!

2025-01-20 11:49 UTC, anoadragon453 commented on synapse/util/stringutils.py
> +    return bool(NAMESPACED_GRAMMAR.match(s))
Could you add a couple unit tests for this utility function please?

2025-01-20 11:49 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +                400, "Field name is invalid", errcode=Codes.INVALID_PARAM
Just to make it crystal clear to prospective client devs.

```suggestion
                400,
                "Field name does not follow Common Namespaced Identifier Grammar",
                errcode=Codes.INVALID_PARAM
```

2025-01-20 11:49 UTC, anoadragon453 commented on synapse/rest/client/profile.py
> +                400, "Field name is invalid", errcode=Codes.INVALID_PARAM
```suggestion
                400,
                "Field name does not follow Common Namespaced Identifier Grammar",
                errcode=Codes.INVALID_PARAM
```

2025-01-20 11:49 UTC, anoadragon453 commented on synapse/rest/client/capabilities.py
> +                disallowed.append("avatar_url")
Shouldn't we only add these values to `disallowed` if these config options are set to `false`?

```suggestion
            if not self.config.registration.enable_set_displayname:
                disallowed.append("displayname")
            if not self.config.registration.enable_set_avatar_url:
                disallowed.append("avatar_url")
```

2025-01-20 19:47 UTC, clokep commented
Good catch @anoadragon453! I've added a bunch more tests to ensure this is all working as expected. 👍

2025-01-21 11:11 UTC, merged

2025-01-21 15:00 UTC, clokep commented
Thanks for all the reviews!