Add Admin API to redact all a user's events
element-hq/synapse pull request #17506
Opened 2024-07-30 21:55 UTC by H-Shay

Adds an Admin API to redact all the events of a given user in the provided rooms. If an empty dict is provided, all the events of user in all the rooms they are a member of will be redacted.

2024-07-31 10:03 UTC, MatMaul commented
This looks like a potentially long process, you should probably use the resumable task scheduler so that it survives a restart, and move to an async friendly API, similarly to the [delete room v2](https://element-hq.github.io/synapse/latest/admin_api/rooms.html#version-2-new-version) endpoint.

2024-07-31 10:06 UTC, MatMaul commented
Also feel free to ping me in Matrix (@mat:tout.im) if you need some clarity on how the resumable task scheduler work.

2024-08-01 17:49 UTC, H-Shay commented
> This looks like a potentially long process, you should probably use the resumable task scheduler 

Great point thanks for the tip - I've gone ahead and done so :)

2024-08-01 22:34 UTC, MatMaul requested changes

2024-08-01 22:34 UTC, MatMaul commented on synapse/handlers/admin.py
> +                    await self.event_creation_handler.create_and_send_nonmember_event(
I think some cases that can be explicitly handled are missing here:
- the requester may not have the right to redact the event regarding room rules, so we should probably impersonate the user here instead of using `requester`. The cleanest would be to try first with requester and otherwise impersonate the user I believe.
- the event could already be a redaction. Not sure if we should filter those in `get_events_sent_by_user` or deal with them here.

I probably forgot some stuffs, I'll let the spec pros pile up here :)

2024-08-01 22:34 UTC, MatMaul commented on synapse/handlers/admin.py
> +        result: Dict[str, Any] = {"result": []}
```suggestion
        result: Dict[str, Any] = task.result if task.result else {"failed_redactions": []}
```
We need to use previous task result if available to properly handle resuming and not override previous `failed_redactions`.

2024-08-01 22:34 UTC, MatMaul commented on docs/admin_api/user_admin_api.md
> +{
I think we should add an optional `reason` here that would be pass down to the redaction events.

2024-08-01 22:34 UTC, MatMaul commented on docs/admin_api/user_admin_api.md
> +  "failed_redactions": [],
We may want to have a dict here, with the key being the event id and the value corresponding to the failure error.

2024-08-02 07:17 UTC, MatMaul commented on synapse/rest/admin/users.py
> +        await assert_user_is_admin(self._auth, requester)
I think we should only allow this on local users and document it, it will fail anyway or most of the rooms if it's not the case anyway.

2024-08-02 07:19 UTC, MatMaul commented on synapse/handlers/admin.py
> +                    await self.event_creation_handler.create_and_send_nonmember_event(
We should also probably check if an event is already redacted before redacting it, especially since this action is resumable.

2024-08-06 02:42 UTC, H-Shay commented on synapse/rest/admin/users.py
> +        await assert_user_is_admin(self._auth, requester)
For my own edification, what makes the redact request fail if the user is not local? I skimmed through the code and the only place I saw that would make that happen is https://github.com/element-hq/synapse/blob/e3db7b2d81cabc7e4335afc051e28678e3a9dd02/synapse/handlers/message.py#L1060, which I wonder if can be circumvented by grabbing some prev events and providing them when creating the event dict in `_redact_all_events`. 

It just seems a bummer that admins would not have the ability to redact offensive events on their own server if the offender was non-local - if there's anyway we can make that happen I think we should.

2024-08-06 08:08 UTC, MatMaul commented on synapse/rest/admin/users.py
> +        await assert_user_is_admin(self._auth, requester)
I think it would be rejected because of the redaction rules of the room ?
It may be fine to do so locally and it will be rejected by the federation at state res which is probably fine ?

I don't think you could redact if you are not in the room (hence needing impersonation and being local) but maybe you can in the end ?

I read the spec parts regarding redaction but it's not clearer to me 😅 

Honestly I am mostly guessing here, we need people more knowledgeable than me.

2024-08-09 13:33 UTC, anoadragon453 requested changes
This is looking pretty good so far, thanks for continuing to make sysadmin's lives easier!

2024-08-09 13:33 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +        await assert_user_is_admin(self._auth, requester)
When redacting the events of local users, it would make sense to impersonate the local user to send the redactions. The admin user isn't guaranteed to be in every room the user is in. 

If you're unable to impersonate the user (i.e. any remote user), it would be best to redact the events locally in the database, without sending an `m.room.redaction` into the room.

Unfortunately there's not a great way to do this at the moment without just "censoring" the events in the database (which may be fine? My concern is that typically you want to keep event content around in the database for some time (see the [`redaction_retention_period`](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html#redaction_retention_period) option)). You could extend [`CensorEventsStore`](https://github.com/element-hq/synapse/blob/develop/synapse/storage/databases/main/censor_events.py#L44) to allow for immediately censoring a given set of event IDs.

2024-08-09 13:33 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +        )
It'd make sense to do this in batches, instead of pulling out every event ID all at once (potentially a lot of data!).

Using `OFFSET` and `LIMIT`, we could pull out ~100 event IDs at a time and then send a redaction for each one, before pulling out the next 100?

2024-08-09 13:33 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +-  `rooms` - A list of rooms to redact the user's events in, if an empty list is provided all events in all rooms
```suggestion
-  `rooms` - A list of rooms to redact the user's events in. If an empty list is provided all events in all rooms
```

2024-08-09 13:33 UTC, anoadragon453 commented on synapse/handlers/admin.py
> +        Task to redact all a users events in the given rooms, tracking which, if any, events
```suggestion
        Task to redact all of a users events in the given rooms, tracking which, if any, events
```

2024-08-09 13:33 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +        rooms = body["rooms"]
We should return a `SynapseError` here of `400` when `rooms` isn't provided. Currently this would 500.

2024-08-09 13:33 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +
```suggestion

_Added in Synapse 1.114.0._
```

2024-08-09 13:33 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- failed: a list of event ids the process was unable to redact, if any
```suggestion
- failed: a list of event ids the process was unable to redact, if any

_Added in Synapse 1.114.0._
```

2024-08-09 13:34 UTC, anoadragon453 commented
sidenote: [MSC4084: Mass redactions](https://github.com/matrix-org/matrix-spec-proposals/pull/4084) would make this a lot more efficient.

2024-08-09 13:50 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +                "sender",
The `events` table doesn't have an index for `sender`, so this would result in a very long sequential scan:

```
matrix=> explain select * from events where sender = '@anoa:matrix.org';
                                    QUERY PLAN
-----------------------------------------------------------------------------------
 Gather  (cost=1000.00..179105833.02 rows=67896 width=955)
   Workers Planned: 2
   ->  Parallel Seq Scan on events  (cost=0.00..179098043.42 rows=28290 width=955)
         Filter: (sender = '@anoa:matrix.org'::text)
 JIT:
   Functions: 4
   Options: Inlining true, Optimization true, Expressions true, Deforming true
(7 rows)
```

<details>

<summary>Click to see the current `events` table schema</summary>

```
matrix=> \d events
                      Table "matrix.events"
        Column        |  Type   | Collation | Nullable | Default
----------------------+---------+-----------+----------+---------
 topological_ordering | bigint  |           | not null |
 event_id             | text    |           | not null |
 type                 | text    |           | not null |
 room_id              | text    |           | not null |
 content              | text    |           |          |
 unrecognized_keys    | text    |           |          |
 processed            | boolean |           | not null |
 outlier              | boolean |           | not null |
 depth                | bigint  |           | not null | 0
 origin_server_ts     | bigint  |           |          |
 received_ts          | bigint  |           |          |
 sender               | text    |           |          |
 contains_url         | boolean |           |          |
 instance_name        | text    |           |          |
 stream_ordering      | bigint  |           |          |
 state_key            | text    |           |          |
 rejection_reason     | text    |           |          |
Indexes:
    "event_contains_url_index" btree (room_id, topological_ordering, stream_ordering) WHERE contains_url = true AND outlier = false
    "events_event_id_key" UNIQUE CONSTRAINT, btree (event_id) REPLICA IDENTITY, tablespace "postgres_second"
    "events_jump_to_date_idx" btree (room_id, origin_server_ts) WHERE NOT outlier
    "events_order_room" btree (room_id, topological_ordering, stream_ordering)
    "events_room_stream" btree (room_id, stream_ordering)
    "events_stream_ordering" UNIQUE, btree (stream_ordering)
    "events_ts" btree (origin_server_ts, stream_ordering)
Referenced by:
    TABLE "event_edges" CONSTRAINT "event_edges_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id)
    TABLE "event_forward_extremities" CONSTRAINT "event_forward_extremities_event_id" FOREIGN KEY (event_id) REFERENCES events(event_id) DEFERRABLE INITIALLY DEFERRED
    TABLE "local_current_membership" CONSTRAINT "event_stream_ordering_fkey" FOREIGN KEY (event_stream_ordering) REFERENCES events(stream_ordering) NOT VALID
    TABLE "current_state_events" CONSTRAINT "event_stream_ordering_fkey" FOREIGN KEY (event_stream_ordering) REFERENCES events(stream_ordering) NOT VALID
    TABLE "room_memberships" CONSTRAINT "event_stream_ordering_fkey" FOREIGN KEY (event_stream_ordering) REFERENCES events(stream_ordering) NOT VALID
    TABLE "event_txn_id_device_id" CONSTRAINT "event_txn_id_device_id_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE
    TABLE "partial_state_events" CONSTRAINT "partial_state_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id)
    TABLE "partial_state_rooms" CONSTRAINT "partial_state_rooms_join_event_id_fkey" FOREIGN KEY (join_event_id) REFERENCES events(event_id)
    TABLE "un_partial_stated_event_stream" CONSTRAINT "un_partial_stated_event_stream_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE
```

</details>

2024-08-09 13:52 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +                "events",
Do we want to attempt to redact *every* event a user has sent (including state events)? Or just messages?

2024-08-09 14:24 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +                "sender",
@reivilibre [mentioned](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$m2o1AiwJUdxaMZb1FfpucUy70pkuHQSWAHLEmK4Xde8?via=matrix.org&via=element.io&via=beeper.com) that we could scan `local_current_membership` to see which rooms the user was in and then scan through only those rooms.

This would cut down the query by quite a bit, though would still be a bit slow for larger rooms.

2024-08-09 14:26 UTC, morguldir commented on synapse/storage/databases/main/events_worker.py
> +                "events",
Aren’t there still 3pid invites that break auth if you redact them?

2024-08-09 19:30 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +                "sender",
So I think the query as written should only select the events in a given room? That was the intention anyway - which is why the room id is provided as a keyvalue to the `simple_select_many_txn` - am I confused about this?

2024-08-09 19:41 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +                "sender",
(I can see how the function name would cause confusion about this though, I'll definitely change that)

2024-08-12 08:18 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +                "sender",
Oops, yes I did miss that and that does make this query's scope a lot smaller. It may still be slow in some rooms (Matrix HQ) but I'm not sure we can do much better without an index.

(If it does come to it, perhaps you could walk backwards along the event auth chain and find all events that are auth'd by your join event.)

2024-08-20 21:43 UTC, H-Shay commented
complement failures are flakey partial-state join tests

2024-08-28 09:33 UTC, MatMaul commented on synapse/handlers/admin.py
> +                            requester,
This is going to fail most of the time if we don't impersonate the user.
I think we should use something like `create_requester(event.sender, authenticated_entity=requester)`.

We may try first to redact with the admin requester and fallback to impersonation, it would be a bit cleaner but honestly most of the time impersonation will be needed so not sure it's worth adding the first step with the admin requester.

2024-08-28 16:17 UTC, anoadragon453 requested changes
I'd like to see the impersonation of the event sender explored before merging this PR, as I agree with @MatMaul that you're likely to need that functionality to redact the majority of a user's messages. Perhaps start with a test with a room that contains the user, but not the admin requester, and check whether their messages are redacted.

I'd also like to see an allowlist of event types to redact. I don't think it makes sense to redact state events that a user has sent, for instance (except in the case of `m.room.member` joins, which could contain offensive display name data).

2024-08-28 16:17 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +        Get a list of event ids and event info of events sent by the user in the specified room
I don't see any "event info" being returned?

2024-08-28 16:17 UTC, anoadragon453 commented on synapse/handlers/admin.py
> +        limit = task.params.get("limit")
nit: It feels cleaner to put the 1000 default here, rather than inside `get_events_sent_by_user_in_room`. That allows different defaults for other endpoints that may one day make use of that method.

The `limit` argument of `get_events_sent_by_user_in_room` can then be required.

2024-08-28 16:17 UTC, anoadragon453 commented on synapse/handlers/admin.py
> +                            requester,
I agree that we should try to impersonate the user to increase the success rate of this command. However, trying to redact with the admin requester should be attempted in the case that the user is kicked/banned from the room and we need to redact their messages.

2024-08-28 16:17 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +        def _get_events_by_user_txn(
```suggestion
        def _get_events_sent_by_user_in_room_txn(
```

2024-08-28 16:17 UTC, anoadragon453 commented on synapse/storage/databases/main/events_worker.py
> +                return selected_ids
nit: this may be slightly clearer as:

```suggestion
            else:
                break
```

2024-08-28 21:11 UTC, H-Shay commented on synapse/handlers/admin.py
> +                            requester,
Yeah that is a total oversight on my part when putting this back up for review - I meant to impersonate the user

2024-08-28 23:07 UTC, H-Shay commented on synapse/handlers/admin.py
> +                            requester,
> However, trying to redact with the admin requester should be attempted in the case that the user is kicked/banned from the room and we need to redact their messages.

The code that I added attempts to rectify this by inserting the redactions immediately after the offending message - I did write a test to verify that this mechanism works so I think that we shouldn't need to re-attempt the redactions for that reason.

2024-08-28 23:21 UTC, H-Shay commented on synapse/handlers/admin.py
> +                if event in result["successful_redactions"]:
I was trying to avoid hitting the database :slightly_frowning_face:  but this makes sense

2024-08-28 23:44 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +        Get a list of event ids and event info of events sent by the user in the specified room
leftover - removing

2024-08-29 20:54 UTC, H-Shay commented
Right so I think this is ready for another look. My only concern is the filter mechanism for event types is a bit noddy, any suggestions on how to make that more graceful (or if it matters) are appreciated.

2024-09-06 15:59 UTC, H-Shay commented
@anoadragon453 just wondering if the request review notif got lost? This should be ready for another go-around and is hopefully very close to done.

2024-09-09 12:41 UTC, anoadragon453 requested changes
Sorry, it looks like I got halfway through a review here and then got distracted :|

This PR is close! Just a few things now.

2024-09-11 19:24 UTC, H-Shay commented on synapse/handlers/admin.py
> +                    "m.video",
This was a case of a bad test leading me astray - I wrote the tests with `self.helper.send_event(
                    rm, "m.text", event, tok=self.bad_user_tok, expect_code=200
                )`
rather than 
`self.helper.send_event(
                    rm, "m.room.message", event, tok=self.bad_user_tok, expect_code=200
                )`
which failed when filtering on `m.room.message`, so I assumed that the more granular types were being stored by synapse (which, actually, in my test was true but that is because the test was wrong) and filtered for those types instead.

2024-09-11 19:34 UTC, H-Shay commented on synapse/handlers/admin.py
> +            events = await self._store.get_events_as_list(set(event_ids))
It's not for de-duplicating, I think it is a holdover from another iteration - I've removed it.

2024-09-11 20:47 UTC, H-Shay commented on tests/rest/admin/test_user.py
> +        # create rooms, some with updated redaction rules
This is to account for `The format of [m.room.redaction](https://spec.matrix.org/v1.11/client-server-api#mroomredaction) events has been modified. Client should look for the redacts key under content instead of a top-level event property.` which is room versions 11 and up - essentially this is to verify https://github.com/element-hq/synapse/pull/17506/files#diff-4c599927cdd8981d3ab951a18319077a80426d54b096036cca6f911eb6da162aR473-R476 works in all cases.

2024-09-12 14:39 UTC, anoadragon453 commented on tests/rest/admin/test_user.py
> +        # create rooms, some with updated redaction rules
Aha, that makes sense. Could you note in a comment that that's the redaction rule this test requires?

2024-09-12 15:20 UTC, anoadragon453 requested changes
Just a couple things now, but overall this is looking nearly ready to go!

2024-09-12 19:38 UTC, H-Shay commented on synapse/handlers/admin.py
> +                        if content.get("membership") == "Membership.JOIN":
Right I have switched it back and ensured that the tests are verifying that we are redacting the join event.

2024-09-13 11:10 UTC, anoadragon453 requested changes
Small things now, lgtm otherwise!

2024-09-13 11:10 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- `reason` - Reason the redaction is being requested, ie "spam", "abuse", etc
To pre-empt someone writing "because they are a $%&^" in this field :relaxed: 

```suggestion
- `reason` - Reason the redaction is being requested, ie "spam", "abuse", etc. This will be included in the each redaction event, and be visible to users.
```

2024-09-13 11:10 UTC, anoadragon453 commented on synapse/handlers/admin.py
> +            limit = 1000
nit: Let's put this logic in `start_redact_events`, in case we ever change this default, and someone upgrades their homeserver in the middle of running a redaction task. It would avoid someone performing a redaction process with a limit they didn't expect (if we change the default from 1000 -> 10000, for instance).

2024-09-13 11:10 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +        limit = body.get("limit")
nit: you can use `parse_integer_from_args` and `parse_string_from_args` to ensure the type of these arguments. Otherwise we may start generating events with a non-string `reason` field.

It's also a good idea to verify that `limit` is not `0` or negative.

2024-09-13 11:10 UTC, anoadragon453 commented on changelog.d/17506.feature
> +Add an asynchronous Admin API endpoint to redact all a user's events, and an endpoint to check on the status of that redaction task.
So sysadmins can find and use your new feature :partying_face: 

```suggestion
Add an asynchronous Admin API endpoint [to redact all a user's events](https://element-hq.github.io/synapse/v1.116/admin_api/user_admin_api.html#redact-all-the-events-of-a-user), and [an endpoint to check on the status of that redaction task](https://element-hq.github.io/synapse/v1.116/admin_api/user_admin_api.html#check-the-status-of-a-redaction-process).
```

2024-09-13 18:43 UTC, H-Shay commented on tests/rest/admin/test_user.py
> +                originals.append(join["event_id"])
Room2 is the only room we are using `originals` for, so only the join event and event ids for room2 need to be collected. I can change the array name to `room2_originals` to make that more clear.

2024-09-13 19:58 UTC, H-Shay commented on synapse/rest/admin/users.py
> +        limit = body.get("limit")
I'm slightly confused as this function seems to parse an integer from a request string, and I am trying to get the values from the request's json object - am I missing something here?

2024-09-16 13:03 UTC, anoadragon453 commented on synapse/rest/admin/users.py
> +        limit = body.get("limit")
Oop, you have every right to be confused. Those functions indeed won't be helpful. Could you manually add the mentioned checks instead?

2024-09-16 17:13 UTC, anoadragon453 commented
This just needs a couple very minor points addressed, and then it's good to go: https://github.com/element-hq/synapse/pull/17506#discussion_r1758641091, https://github.com/element-hq/synapse/pull/17506#discussion_r1757013621

2024-09-17 20:22 UTC, H-Shay commented
riiight sorry for the delay - I think this is ready now.

2024-09-18 09:44 UTC, anoadragon453 approved these changes
Right, this LGTM! Thanks for your patience, this is a really welcome change :)

2024-09-18 09:44 UTC, anoadragon453 commented on docs/admin_api/user_admin_api.md
> +- `reason` - Reason the redaction is being requested, ie "spam", "abuse", etc. This will be included in the each redaction event, and be visible to users.
```suggestion
- `reason` - Reason the redaction is being requested, ie "spam", "abuse", etc. This will be included in each redaction event, and be visible to users.
```

2024-09-18 10:08 UTC, merged