Handle lower-case http headers in `_Mulitpart_Parser_Protocol`
element-hq/synapse pull request #17545
Opened 2024-08-08 20:04 UTC by H-Shay

Fixes #17544

2024-08-08 22:19 UTC, frebib commented on synapse/http/client.py
> +                if data[start:end] == b"Location" or data[start:end] == b"location":
```suggestion
                if data[start:end].lower() == b"location":
```
Whilst maybe unconventional, it's valid to pass headers in all uppercase. Generally it's better to perform header matching in a case-insensitive manner

2024-08-08 23:40 UTC, H-Shay commented on synapse/http/client.py
> +                if data[start:end] == b"Location" or data[start:end] == b"location":
Thanks for pointing that out - I was worried about calling `lower()` on non-string bytes and causing an error but thinking about it for a moment the code is in the `on_header_field` function so that shouldn't happen if the parser is doing its job.

2024-08-12 09:39 UTC, anoadragon453 requested changes

2024-08-12 09:39 UTC, anoadragon453 commented on tests/http/test_client.py
> +    data3 = b"\r\n\r\n--6067d4698f8d40a0a794ea7d7379d53a\r\ncontent-type: application/json\r\n\r\n{}\r\n--6067d4698f8d40a0a794ea7d7379d53a\r\ncontent-type: text/plain\r\ncontent-disposition: inline;
nit: Could you update the names of these variables to be more descriptive?

2024-08-12 09:39 UTC, anoadragon453 commented on changelog.d/17545.bugfix
> +Handle lower-case http headers in _Mulitpart_Parser_Protocol.
```suggestion
Handle lower-case http headers in `_Multipart_Parser_Protocol`.
```

2024-08-12 20:08 UTC, Xiretza commented on tests/http/test_client.py
> +    data3 = b"\r\n\r\n--6067d4698f8d40a0a794ea7d7379d53a\r\ncontent-type: application/json\r\n\r\n{}\r\n--6067d4698f8d40a0a794ea7d7379d53a\r\ncontent-type: text/plain\r\ncontent-disposition: inline;
And while you're at it, maybe give the header names a bit more of a sPoNgEbOb look? Only checking the lowercase version is a bit narrow.

2024-08-14 08:48 UTC, anoadragon453 approved these changes
![sponge](https://github.com/user-attachments/assets/60e2409e-e322-4f24-add5-ad0bb114f049)

2024-08-14 08:49 UTC, merged