Sliding sync: Add classes for per-connection state
element-hq/synapse pull request #17574
Opened 2024-08-15 10:12 UTC by erikjohnston

This is some prep work ahead of correctly tracking receipts, where we will also want to track the room status in terms of last receipt we had sent down.

Essentially, we add two classes `PerConnectionState` and a mutable version, and then operate on those.

2024-08-15 23:19 UTC, MadLittleMods requested changes

2024-08-15 23:19 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +        per_connection_state = await self.connection_store.get_per_connection_state(
I think this makes sense given we're literally getting the connection state from the previous request.

```suggestion
        previous_connection_state = await self.connection_store.get_per_connection_state(
```

And then plays well when we want to want to distinguish mutable `new_connection_state` that we want to update

2024-08-15 23:19 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            )
Separating out the `record` functions looks good :+1:

2024-08-15 23:19 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    _statuses: typing.ChainMap[str, HaveSentRoom]
Are we worried about the memory footprint over time? For a long-running connection, this seems like it will grow and grow until we restart the server. Every sync request with updates will add another layer to this `ChainMap`.

There's never a chance to garbage collect anything even once a map layer is completely superseded by the layers below with all of the keys. Seems like we should do a clean-up /consolidation pass after a certain number of layers.

2024-08-16 07:56 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +class PerConnectionState:
Yeah, it's a lot. I don't know if maybe it'd help moving to a different file so its a bit more clearly laid out? Suggestions on naming is also more than welcome.

2024-08-16 08:10 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    _statuses: typing.ChainMap[str, HaveSentRoom]
Yeah so actually when we store the mutable connection state we actually end up doing a `RoomStatusesForStream.copy()`, which then flattens the chainmap into a dict again. I think that stops us from every ending up with nested chain maps like that.

I'm also wanting to rip all this out and replace it with DB tables once the receipts and subscription PRs land, so I'm not overly concerned about resources for this stuff.

2024-08-16 09:05 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +            current_status = self._statuses.get(room_id)
oh yeah, that is much better

2024-08-16 09:21 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    down for that stream in a given room."""
I've renamed to `RoomStatusMap`. I think in future we might want to rename `HaveSentRoom` to something else (as e.g. tracking `timeline_limit`doesn't fit into the name really).

2024-08-19 16:47 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +    _statuses: typing.ChainMap[str, HaveSentRoom]
Ahh, we should add some comments in various places. Something about how the `copy()` flattens the `ChainMap` back out.

Or maybe a better word about, we only ever use the `MutablePerConnectionState` during the lifetime of the request and always end up making a flat `PerConnectionState` copy before we store it in the `ConnectionStore`.

Because we `record_new_state(...)` (which flattens out the `ChainMap`) after each request, the `ChainMap` doesn't grow indefinitely.

2024-08-19 17:00 UTC, MadLittleMods approved these changes
Looks good after understanding the `PerConnectionState` life-times better. I think it would be good to point it out in [some comments](https://github.com/element-hq/synapse/pull/17574#discussion_r1722079233)

2024-08-19 17:11 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    _statuses: typing.ChainMap[str, HaveSentRoom]
Thanks, will try and add some comments.

2024-08-19 17:23 UTC, erikjohnston commented on synapse/handlers/sliding_sync.py
> +    _statuses: typing.ChainMap[str, HaveSentRoom]
Have tried to add a couple of comments in https://github.com/element-hq/synapse/pull/17574/commits/7f5bccc646823c9530f31f8dd18029a015660d13

2024-08-19 19:09 UTC, merged