Sliding sync: Correctly track which read receipts we have or have not sent down.
element-hq/synapse pull request #17575
Opened 2024-08-15 11:41 UTC by erikjohnston

Based on #17574

2024-08-16 00:36 UTC, MadLittleMods requested changes

2024-08-16 00:36 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                )
Restore comment:

```suggestion 
                 # TODO: In the future, it would be good to fetch less receipts
                # out of the database in the first place but we would need to
                # add a new `event_id` index to `receipts_linearized`.
                initial_receipts = await self.store.get_linearized_receipts_for_room(
                    room_id=room_id,
                    to_key=to_token.receipt_key,
                )
```

2024-08-16 00:36 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                    )
Similar to potentially sending down too much state (see `get_current_state_deltas_for_room()` usage above):

Not sure exactly what to do in case of too many but we should at least have this as a placeholder to think about

```suggestion
                    # TODO: Limit the number of receipts we're about to send down
                    # for the room, if its too many we should TODO
                    previously_receipts = (
                        await self.store.get_linearized_receipts_for_room(
                            room_id=room_id,
                            from_key=receipt_token,
                            to_key=to_token.receipt_key,
                        )
                    )
```

2024-08-16 00:36 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            # sending down.
Add a comment about why we're using `per_connection_state.receipts._statuses.keys()`: because we only care about updating `LIVE` rooms to `PREVIOUS`, etc (probably a better way to explain)

2024-08-16 00:36 UTC, MadLittleMods commented on synapse/storage/databases/main/receipts.py
> +        """Get the set of rooms that (may) have receipts between the two tokens."""
```suggestion
        """Given a set of room_ids, find out which ones (may) have receipts between the two tokens (> `from_token` and <= `to_token`)."""
```

2024-08-16 00:36 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_extensions.py
> +                    "timeline_limit": 1,
I assume this is why you changed it:

(no wrapped properly)

```suggestion
                    # We set this to `1` because we're testing `receipts` which interact
                    # with the `timeline`. With receipts, when a room hasn't been sent
                    # down the connection before or it appears as `initial: true`, we
                    # only include receipts for events in the timeline to avoid bloating
                    # and blowing up the sync response as the number of users in the
                    # room increases. (this behavior is part of the spec)
                    "timeline_limit": 1,
```

2024-08-16 00:36 UTC, MadLittleMods commented on tests/rest/client/utils.py
> +        assert channel.code == HTTPStatus.OK, channel.text_body
Should we use this helper for the rest of the `receipts` tests?

2024-08-16 14:25 UTC, erikjohnston commented on tests/rest/client/utils.py
> +        assert channel.code == HTTPStatus.OK, channel.text_body
Yup, we should, just didn't want to inflate the PR

2024-08-19 17:55 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            new_per_connection_state=new_connection_state,
To match `previous_connection_state`:

```suggestion
            new_connection_state=new_connection_state,
```

(throughout)

2024-08-19 17:55 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                state, used to record updates to the state.
```suggestion
            previous_connection_state: Snapshot of the current per-connection state
            new_per_connection_state: A mutable copy of the per-connection
                state, used to record updates to the state during this request.
```

2024-08-19 17:55 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +                # timeline with all the receipts for the room.
```suggestion
                # If we're sending down the room from scratch again for some reason, we
                # should always resend the receipts as well (regardless of if
                # we've sent them down before). This is to mimic the behaviour
                # of what happens on initial sync, where you get a chunk of
                # timeline with all of the corresponding receipts for the events in the timeline.
```

2024-08-19 17:55 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
> +            # the live rooms)
Perhaps something like this? Does this sound better?

```suggestion
            # Now find the set of rooms that may have receipts that we're not sending
            # down. We only need to check rooms that we have previously returned
            # receipts for (in `previous_connection_state`) because we only care about
            # updating `LIVE` rooms to `PREVIOUSLY`. The `PREVIOUSLY` rooms will just
            # stay pointing at their previous position so we don't need to waste time
            # checking those and since we default to `NEVER`, rooms that were `NEVER`
            # sent before don't need to be recorded as we'll handle them correctly when
            # they come into range for the first time.
```

2024-08-19 17:55 UTC, MadLittleMods commented on synapse/handlers/sliding_sync.py
>          rooms: The status of each room for the events stream.
`receipts` hasn't been added to the `Attributes` in the docstring yet

2024-08-19 17:57 UTC, MadLittleMods approved these changes

2024-08-19 20:16 UTC, merged