Support filtering by 'tags' / 'not_tags' in SSS
element-hq/synapse pull request #17662
Opened 2024-09-04 14:56 UTC by dbkr

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-09-11 20:44 UTC, MadLittleMods requested changes

2024-09-11 20:44 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/room_lists.py
> +                }
We can just copy the pattern that `room_types`/`not_room_types` is using (introduced in https://github.com/element-hq/synapse/pull/17337)

2024-09-11 20:44 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +        # Try with `tags=foo`
We should also have a test for `tags=["foo", "bar"]`

2024-09-11 20:44 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/room_lists.py
> +        room_tags: Mapping[str, Mapping[str, JsonMapping]],
We also need to add support for `tags`/`not_tags` for the fallback version of this function -> `filter_rooms`.

There are two paths in Sliding Sync at the moment. One for when we have access to the [Sliding Sync database tables](https://github.com/element-hq/synapse/pull/17512) which can make some things faster and the fallback.

In this case, the implementation is pretty much going to be the same. We just duplicate the logic.

2024-09-11 20:44 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +
We should add a test for:

```
# Test how it behaves when we have both `tags` and `not_tags`.
# `not_tags` should win.
```

2024-09-11 20:44 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +        # )
Leftover cruft we can remove

2024-09-11 20:44 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +            self.sliding_sync_handler.room_lists.filter_rooms_using_tables(
Given the two paths that Synapse can use (new path that uses the sliding sync database tables and fallback path), I guess we should move all of these tests to the rest layer (`tests/rest/client/sliding_sync/test_sliding_sync.py`) so it exercises both.

I can work on that today :fast_forward:

2024-09-11 23:18 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +            self.sliding_sync_handler.room_lists.filter_rooms_using_tables(
Tests moved in https://github.com/element-hq/synapse/pull/17703

I can update this PR once that merges

2024-09-12 21:31 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/room_lists.py
> +        room_tags: Mapping[str, Mapping[str, JsonMapping]],
Added :fast_forward:

2024-09-12 21:31 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> +            self.sliding_sync_handler.room_lists.filter_rooms_using_tables(
Updated :white_check_mark:

2024-09-12 21:37 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/room_lists.py
> +                    }
Logic is exactly the same. Duplication is probably better than trying to abstract it :shrug:

2024-09-12 21:38 UTC, MadLittleMods approved these changes

2024-09-12 21:38 UTC, MadLittleMods commented on changelog.d/17662.feature
> +Add support for the `tags` and `not_tags` filters for simplified sliding sync.
@devonh Given I've added my own touch here, you should probably review this as well

2024-09-12 21:43 UTC, devonh commented on changelog.d/17662.feature
> +Add support for the `tags` and `not_tags` filters for simplified sliding sync.
I'll take a look

2024-09-12 21:59 UTC, devonh approved these changes
LGTM! :smile: 

Thanks for taking this over and pushing it through

2024-09-12 21:59 UTC, devonh commented on synapse/handlers/sliding_sync/room_lists.py
> +                    }
Agreed. Especially since the whole new/fallback approach mean the duplication won't be here long.

2024-09-13 01:18 UTC, merged

2024-09-13 01:19 UTC, MadLittleMods commented
Thanks for the quick review @devonh 🦒

@dbkr Thanks for getting this going making Sliding Sync more compatible with Element Web! 🦃