Sliding Sync: Move filters tests to rest layer
element-hq/synapse pull request #17703
Opened 2024-09-11 22:53 UTC by MadLittleMods

Move filters tests to rest layer

Spawning from https://github.com/element-hq/synapse/pull/17662#discussion_r1755574791. This should have been done when we started using the new sliding sync tables in https://github.com/element-hq/synapse/pull/17630

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-09-11 23:10 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/room_lists.py
> +                        continue
Fixing `filter_rooms_using_tables` (the new path using the new sliding sync tables) to take into account `has_known_state`.

The `_no_stripped_state` tests exercise these scenarios.

2024-09-11 23:11 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_rooms_meta.py
> +    def test_rooms_meta_is_dm(self) -> None:
This test is "new" because I moved the "Ensure DM's are correctly marked"  checking from one of the filtering tests to it's own separate thing here.

2024-09-11 23:14 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_sliding_sync.py
> -    def test_filter_list(self) -> None:
These filter tests already at the REST layer were just moved to `tests/rest/client/sliding_sync/test_lists_filters.py` now that we have a specific file for it.

2024-09-11 23:15 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_sliding_sync.py
> +    def _add_new_dm_to_global_account_data(
Just moving some helpers to the `SlidingSyncBase` so we can use them across the Sliding Sync tests more easily.

2024-09-11 23:15 UTC, MadLittleMods commented on tests/handlers/test_sliding_sync.py
> -class FilterRoomsTestCase(HomeserverTestCase):
These tests we're moved to `tests/rest/client/sliding_sync/test_lists_filters.py` and refactored to interact with the Sliding Sync API directly.

2024-09-12 18:57 UTC, devonh requested changes
Overall looks good to me!
Just a few comments.

2024-09-12 18:57 UTC, devonh commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +            )
I'm not sure how the new tables leads to this behaviour. (I just don't know enough :smile:)
Could you explain to me why we expect no room_ids here, then both the encrypted and unencrypted room_ids after the next sync?

2024-09-12 18:57 UTC, devonh commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +
should this also be `exact=True`?

2024-09-12 19:00 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +            set(response_body["lists"]["foo-list"]["ops"][0]["room_ids"]),
We're thinking about removing it in favor of just a straight list like `room_ids: []` but until then I'll use it (context https://github.com/element-hq/synapse/pull/17671#discussion_r1750928730)

2024-09-12 19:02 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +
More precise :+1:

2024-09-12 19:03 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +            )
No worries (willing to explain whatever)

It's really the opposite. The old path leaks data but we consider that "fine" (see the comment just below)

2024-09-12 19:20 UTC, devonh commented on tests/rest/client/sliding_sync/test_lists_filters.py
> +            )
Ah I get it now. Thanks for filling me in!

2024-09-12 19:20 UTC, devonh approved these changes

2024-09-12 20:27 UTC, merged

2024-09-12 20:27 UTC, MadLittleMods commented
Thanks for the review @devonh 🦌