Sliding Sync: Return room tags in account data extension
element-hq/synapse pull request #17707
Opened 2024-09-13 01:04 UTC by MadLittleMods

Return room tags in account data extension

The account data extension was also updated to avoid copies when we pull the data out of the cache.

Fix https://github.com/element-hq/synapse/issues/17694

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-09-13 19:20 UTC, devonh requested changes

2024-09-13 19:20 UTC, devonh commented on tests/rest/client/sliding_sync/test_extension_account_data.py
> +            {"org.matrix.roorarraz2", AccountDataTypes.TAG},
I think we should extend these tests to also ensure the correct tags are present in each of the responses.
This would highlight the TODO comments in the code.

ie. This assertion should only include `m.server_notice` if the `from_token` was being considered.
Whereas right now it returns `{'tags': {'m.favourite': {}, 'm.server_notice': {}}`

Thoughts?

2024-09-16 15:35 UTC, MadLittleMods commented on synapse/handlers/sliding_sync/extensions.py
> +                account_data_by_room_maps.append(account_data_by_room_map)
It can but the reason they are different is because this branch returns a mutable copy that we can just append to directly. And in the other branch, the cache returns an immutable copy and we have to layer another map on top.

They can be aligned to look the same if you prefer

2024-09-16 15:39 UTC, devonh commented on synapse/handlers/sliding_sync/extensions.py
> +                account_data_by_room_maps.append(account_data_by_room_map)
Ah, I missed that.
In that case, this is fine

2024-09-16 16:46 UTC, MadLittleMods commented on tests/rest/client/sliding_sync/test_extension_account_data.py
> +            {"org.matrix.roorarraz2", AccountDataTypes.TAG},
I don't think we would ever want to return a partial set of tags for a room given they are presented as a pseudo event like this: `{'content': {'tags': {'m.favourite': {}, 'm.server_notice': {}}}, 'type': 'm.tag'}`

Currently, the `from_token` is being taken into account but it's done on a `(user_id, room_id)` level for room tags.

---

Asserting the `content` values would be an improvement though :+1:

2024-09-16 16:55 UTC, devonh commented on tests/rest/client/sliding_sync/test_extension_account_data.py
> +            {"org.matrix.roorarraz2", AccountDataTypes.TAG},
I had assumed the tags should be partial based on this TODO statement: 
https://github.com/element-hq/synapse/pull/17707/files#diff-feaf6d2c2a7bd96225721b03e828ddf4bb4617c15bda08d872f3841a04f41a89R452
```py
                # Add room tags
                #
                # TODO: This should take into account the `from_token` and `to_token`
                tags_by_room = await self.store.get_updated_tags(
                    user_id, from_token.stream_token.account_data_key
                )
                for room_id, tags in tags_by_room.items():
                    account_data_by_room_map.setdefault(room_id, {})[
                        AccountDataTypes.TAG
                    ] = {"tags": tags}
```

If we don't want to return partial sets of tags, then should that TODO be removed? (similar question for the TODO below in the else condition where no `from_token` is present)

2024-09-16 17:03 UTC, devonh commented on tests/rest/client/sliding_sync/test_extension_account_data.py
> +            {"org.matrix.roorarraz2", AccountDataTypes.TAG},
If was always want to return the full tag set for a room, why is there a code path that factors in the `from_token` at all?

2024-09-16 17:17 UTC, devonh commented on tests/rest/client/sliding_sync/test_extension_account_data.py
> +            {"org.matrix.roorarraz2", AccountDataTypes.TAG},
Got it. Thanks for the explanation :cowboy_hat_face:

2024-09-16 18:25 UTC, devonh approved these changes

2024-09-16 18:47 UTC, merged

2024-09-16 18:48 UTC, MadLittleMods commented
Thanks for the review @devonh 🐏