Remove the deprecated cgi module
element-hq/synapse pull request #17741
Opened 2024-09-22 16:22 UTC by V02460

Removes all uses of the `cgi` module from Synapse. It was deprecated in Python version 3.11 and removed in version 3.13 ([“dead battery”](https://docs.python.org/3.13/whatsnew/3.13.html#pep-594-remove-dead-batteries-from-the-standard-library)). 

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-09-22 18:13 UTC, clokep commented on synapse/event_auth.py
> +                    isinstance(v, int)
This is not equivalent and seems unrelated to the other changes.

2024-09-22 20:16 UTC, V02460 commented on synapse/event_auth.py
> +                    isinstance(v, int)
You are right, that was not supposed to go into the PR. I added that accidentally.

For context, on my machine ruff is complaining with
```
synapse/event_auth.py:890:21: E721 Do not compare types, use `isinstance()`
```

2024-09-22 21:57 UTC, clokep commented on synapse/event_auth.py
> +                    isinstance(v, int)
Maybe the wrong version of ruff? A bunch of the type comparisons are explicit to avoid book being an int under the hood.

2024-09-23 08:48 UTC, V02460 commented on synapse/event_auth.py
> +                    isinstance(v, int)
Yes, probably. I already reverted that change.

2024-09-23 08:48 UTC, V02460 commented
I don’t think CI is complaining because of this PR?

2024-09-24 13:00 UTC, sandhose requested changes
Thanks for this, just one nitpick on the replacement for cgi.parse_header

2024-09-24 16:14 UTC, spaetz commented on synapse/http/matrixfederationclient.py
> +    if c_type_parsed != expected_content_type:
Just so it does not get lost, the Email module does the same code, so creating an EmailMessage() each time feels like super-heavy overengineering:

This is what the email module literally does:
https://github.com/python/cpython/blob/38a5beb12a64461a06b84fab285944ecb66de04c/Lib/email/message.py#L29C1-L37C32

2024-09-25 07:48 UTC, sandhose approved these changes

2024-09-25 09:15 UTC, merged