MSC4140: don't cancel delayed state on own state
element-hq/synapse pull request #17810
Opened 2024-10-10 03:08 UTC by AndrewFerr

When a user sends a state event, do not cancel their own delayed events for the same piece of state.

For context, see [the relevant section in the MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/a09a883d9a013ac4b6ffddebd7ea87a827d211b9/proposals/4140-delayed-events-futures.md#delayed-state-events-are-cancelled-by-a-more-recent-state-event).

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-10-10 03:10 UTC, AndrewFerr commented
Depends on https://github.com/matrix-org/complement/pull/742 for Complement tests to pass.

2024-10-14 16:42 UTC, anoadragon453 requested changes
Looks good on the whole, just some small points of feedback.

2024-10-14 16:42 UTC, anoadragon453 commented on changelog.d/17810.feature
> +When a user sends a state event, do not cancel their own delayed events (as per MSC4140) for the same piece of state.
Typically with Synapse changelog entries, we try to start with an action as the first word. Something like:

```suggestion
Update MSC4140 implementation to no longer cancel a user's own delayed events when they send a state event; where the state type and key match that of a scheduled delayed event.
```

2024-10-14 16:42 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +                continue
Out of interest, would it be worth instead adding an argument to `get_partial_current_state_deltas` to filter out state deltas that do not have an associated event ID?

2024-10-14 16:42 UTC, anoadragon453 commented on synapse/storage/databases/main/delayed_events.py
>          Cancels all matching delayed state events, i.e. remove them as long as they haven't been processed.
Could you add the arguments to the docstring of this function please?

2024-10-15 20:41 UTC, AndrewFerr commented on changelog.d/17810.feature
> +When a user sends a state event, do not cancel their own delayed events (as per MSC4140) for the same piece of state.
55e613be9f

2024-10-15 20:41 UTC, AndrewFerr commented on synapse/storage/databases/main/delayed_events.py
>          Cancels all matching delayed state events, i.e. remove them as long as they haven't been processed.
d45595c2ad

2024-10-16 17:26 UTC, AndrewFerr commented
The sytests pass when I run them locally.  Is there a way to retry their CI runs?

2024-10-16 17:46 UTC, MadLittleMods commented
@AndrewFerr Retried :+1:

2024-11-11 03:15 UTC, AndrewFerr commented on synapse/handlers/delayed_events.py
> +                continue
It was decided out-of-band to not pursue adding that argument, so let's leave this as it is.

2024-11-11 05:50 UTC, AndrewFerr commented
Now the only failing tests are the ones that depend on https://github.com/matrix-org/complement/pull/742 (finally!).

2025-01-17 14:19 UTC, hughns commented
@AndrewFerr what's the latest on this PR and addressing any outstanding issues?

2025-01-17 15:06 UTC, AndrewFerr commented
> what's the latest on this PR and addressing any outstanding issues?

This and https://github.com/matrix-org/complement/pull/742 are both ready to be merged (though the latter should be merged first).

2025-03-10 17:54 UTC, AndrewFerr commented
Eugh, looks like I had the wrong understanding of how CI chooses which Complement branch to run on.

In any case, I can assure you that `TestDelayedEvents` passes when using this PR + https://github.com/matrix-org/complement/pull/768.

2025-03-17 16:21 UTC, anoadragon453 approved these changes
This LGTM, thanks for your patience :pray: 

Will merge this PR at the same time as https://github.com/matrix-org/complement/pull/768.

2025-03-17 16:21 UTC, merged