Check if user is in room before being able to tag it
element-hq/synapse pull request #17839
Opened 2024-10-17 05:38 UTC by lamoboos223

create a function in room_member handler to check if a user is a member of a room

checked if a user is in a room before tagging it

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-10-17 05:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17839) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17839) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17839) it.</sub>

2024-10-17 05:45 UTC, lamoboos223 commented
Closes #17819

2024-10-23 17:09 UTC, MadLittleMods requested changes

2024-10-23 17:09 UTC, MadLittleMods commented on synapse/rest/client/tags.py
> +        # check if the user is member of the room and raise error if not
```suggestion
        # Check if the user has any membership in the room and raise error if not.
        # Although it's not harmful for users to tag random rooms, it's just superfluous
        # data we don't need to track or allow.
```

2024-10-23 17:09 UTC, MadLittleMods commented on changelog.d/17839.bugfix
> +Checking if user is member of a room before tagging it. Contributed by Lama Alosaimi.
```suggestion
Check if user has membership in a room before tagging it. Contributed by Lama Alosaimi.
```

2024-10-24 16:56 UTC, MadLittleMods requested changes

2024-10-24 16:56 UTC, MadLittleMods commented on changelog.d/17839.bugfix
> +Check if user has membership in a room before tagging it. Contributed by Lama Alosaimi.
Actually [run the linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters) so [everything is fixed](https://github.com/element-hq/synapse/actions/runs/11493325681/job/32021037714?pr=17839).

2024-10-24 16:56 UTC, MadLittleMods commented on synapse/handlers/room_member.py
> +        result: Optional[Tuple[Optional[str], Optional[str]]] = await self.store.get_local_current_membership_for_user_in_room(user_id=user_id, room_id=room_id)
No need to add a type here. `mypy` can already assume from what `get_local_current_membership_for_user_in_room(...)` returns.

```suggestion
        result = await self.store.get_local_current_membership_for_user_in_room(user_id=user_id, room_id=room_id)
```

2024-10-24 16:56 UTC, MadLittleMods commented on synapse/handlers/room_member.py
> +            raise AuthError(403, f"You are not a member of the room {room_id}")
```suggestion
            raise AuthError(403, "User %s has no membership in room %s" % (user_id, room_id))
```

2024-10-24 16:56 UTC, MadLittleMods commented on synapse/handlers/room_member.py
> +    async def check_user_membership(self, user_id: str, room_id: str) -> None:
Name suggestion (maybe this is better :thinking:) `check_for_any_membership_in_room`

Add a docstring

Because both arguments are strings which could be accidentally swapped, we can add `*, ` to force keyword args.

```suggestion
    async def check_for_any_membership_in_room(self, *, user_id: str, room_id: str) -> None:
        """
        Check if the user has any membership in the room and raise error if not.

        Args:
            user_id: The user to check.
            room_id: The room to check.

        Raises:
            AuthError if the user doesn't have any membership in the room.
        """
```

2024-10-25 18:12 UTC, lamoboos223 commented
Thanks for every review and note dear @MadLittleMods <3

2024-10-25 19:53 UTC, MadLittleMods approved these changes

2024-10-25 19:53 UTC, MadLittleMods commented on synapse/rest/client/tags.py
> +        )
Just to sanity check that we have tests to make sure you can still tag rooms as expected; looks like we have a [couple tests in the Sliding Sync stuff](https://github.com/element-hq/synapse/blob/69e9b753734ebd28d5bed5f7828a8d34e86ec205/tests/rest/client/sliding_sync/test_lists_filters.py#L1712-L1765). Ideally, there would be dedicated tests for this endpoint but this is good enough :fast_forward: 

(no action needed, just documenting)

2024-10-25 19:58 UTC, MadLittleMods requested changes

2024-10-25 19:58 UTC, MadLittleMods commented on synapse/handlers/room_member.py
> +        if result is None:
Actually this is a bit flawed since `get_local_current_membership_for_user_in_room(...)` returns a tuple.

So no matter what, this will be truthy

```
$ python
> asdf = (None, None)
> bool(asdf)
```

We need to check for either of the tuple fields since both will be `None` if a `room_id`/`user_id` pair is not found.

Since this was almost missed, I guess we should probably invest in a couple tests in `tests/rest/client/test_tags.py` (create the new test file)

2024-10-25 19:59 UTC, MadLittleMods commented on synapse/handlers/room_member.py
> +        if result is None:
Sorry for missing this earlier :bow:

2024-10-26 05:07 UTC, lamoboos223 commented on synapse/handlers/room_member.py
> +        if result is None:
On it

2024-10-28 22:13 UTC, MadLittleMods requested changes

2024-10-28 22:13 UTC, MadLittleMods commented on tests/rest/client/test_tags.py
> +#
Updated copyright header

```suggestion
#
# This file is licensed under the Affero General Public License (AGPL) version 3.
#
# Copyright (C) 2024 New Vector, Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# See the GNU Affero General Public License for more details:
# <https://www.gnu.org/licenses/agpl-3.0.html>.
#
```

2024-10-28 22:13 UTC, MadLittleMods commented on tests/rest/client/test_tags.py
> +PATH_PREFIX = "/_matrix/client/api/v1"
Unused

2024-10-28 22:13 UTC, MadLittleMods commented on tests/rest/client/test_tags.py
> +        self.assertEqual(channel.code, 403, channel.result)
This is untested/unformatted but I think we can simplify a bit:

(needs to some docstrings explaining what we're trying to test)

```suggestion
    servlets = [room.register_servlets, tags.register_servlets]

    def test_put_tag_checks_room_membership(self) -> None:
        """
        TODO
        """
        user1_id = self.register_user("user1", "pass")
        user1_tok = self.login(user1_id, "pass")

        room_id = self.helper.create_room_as(user1_id, tok=user1_tok)
        tag = "test_tag"

        # Make the request
        channel = self.make_request(
            "PUT",
            f"/user/{user1_id}/rooms/{room_id}/tags/{tag}",
            content={"order": 0.5},
            access_token=user1_tok,
        )
        # Check that the request was successful
        self.assertEqual(channel.code, HTTPStatus.OK, channel.result)

    def test_put_tag_fails_if_not_in_room(self) -> None:
        """
        TODO
        """
        user1_id = self.register_user("user1", "pass")
        user1_tok = self.login(user1_id, "pass")
        
        room_id = "!nonexistent:test"
        tag = "test_tag"

        # Make the request
        channel = self.make_request(
            "PUT",
            f"/user/{user1_id}/rooms/{room_id}/tags/{tag}",
            content={"order": 0.5},
            access_token=user1_tok,
        )
        # Check that the request failed with the correct error
        self.assertEqual(channel.code, HTTPStatus.FORBIDDEN, channel.result)
```

2024-10-29 19:42 UTC, MadLittleMods requested changes
Looking good!

Just a few formatting things

2024-10-29 19:42 UTC, MadLittleMods commented on tests/rest/client/test_tags.py
> +            None
We don't need to burden the docstring  with this kind of info for tests

```suggestion
        Args:
            None

        Returns:
            None
```

2024-10-29 19:42 UTC, MadLittleMods commented on tests/rest/client/test_tags.py
> +        self.assertEqual(channel.code, HTTPStatus.OK, channel.result)
Good practice to space things out a bit

(also removed that extra login comment)

```suggestion
        user1_id = self.register_user("user1", "pass")
        user1_tok = self.login(
            user1_id, "pass"
        ) 
        room_id = self.helper.create_room_as(user1_id, tok=user1_tok)
        tag = "test_tag"

        # Make the request
        channel = self.make_request(
            "PUT",
            f"/user/{user1_id}/rooms/{room_id}/tags/{tag}",
            content={"order": 0.5},
            access_token=user1_tok,
        )
        # Check that the request was successful
        self.assertEqual(channel.code, HTTPStatus.OK, channel.result)
```

2024-10-30 16:55 UTC, merged

2024-10-30 16:55 UTC, MadLittleMods commented
Thanks for the contribution @lamoboos223 :raccoon:

2024-10-30 17:12 UTC, lamoboos223 commented
My pleasure Eric 🤝

@MadLittleMods