Fix bug when rejecting withdrew invite with a third_party_rules module
element-hq/synapse pull request #17930
Opened 2024-11-13 13:56 UTC by MatMaul

When rejecting a withdrew invite through federation, an out of band event needs to be created.

When doing so with a third_party_rules module installed, `get_prev_state_ids` [is called](https://github.com/element-hq/synapse/blob/e0fdb862cbbddc920a30233024eb99038ee2fb28/synapse/module_api/callbacks/third_party_event_rules_callbacks.py#L285) on the context to calculate the state to pass at `check_event_allowed` callbacks.

The context for outliers is defined [here](https://github.com/element-hq/synapse/blob/e0fdb862cbbddc920a30233024eb99038ee2fb28/synapse/events/snapshot.py#L168), and `state_group_before_event` is None.

This change makes the behavior of `get_prev_state_ids` and `get_current_state_ids` match the one presented in the docstring regarding null state_group.

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-11-14 20:52 UTC, MatMaul commented on synapse/events/snapshot.py
> +            return None
This change is not needed to fix the issue. I put it there because it seems that what the docstring wants to imply, but I am not sure now. We may just want to remove the assert, or do not change anything there. And we could remove `Optional` from the return type, since it's never None.

2024-11-20 16:41 UTC, reivilibre requested changes
Makes sense; just a small change

2024-11-20 16:41 UTC, reivilibre commented on synapse/events/snapshot.py
> +            return None
On balance, I think I would keep the assertion, update the docstring to say it's an error to call this when the event is an outlier and remove `Optional` from the return type indeed.

(For a case we don't even reach, I don't like converting `assert`s to `if ...: return None`, because that might someday hide a bug)

2024-11-26 17:03 UTC, reivilibre approved these changes

2024-12-10 14:26 UTC, reivilibre commented
sorry! probably I was waiting for CI to run, or to re-run after a flake

2024-12-10 14:26 UTC, merged

2024-12-10 14:34 UTC, MatMaul commented
Merci !