feat: Allow multiple values for SSO attributes via comma separating
element-hq/synapse pull request #17949
Opened 2024-11-20 17:19 UTC by meise

In the current `attribute_requirements` implementation it is only possible to allow exact matching attribute values. Multiple allowed values for one attribute are not possible as described in #13238.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-11-20 17:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17949) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17949) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17949) it.</sub>

2024-11-20 17:40 UTC, meise commented
I'm not sure whether the current change is really ideal or whether the [JSON schema](https://github.com/element-hq/synapse/blob/develop/synapse/config/sso.py#L43) should be changed to a value list.

2024-11-20 17:45 UTC, sandhose requested changes

2024-11-20 17:45 UTC, sandhose commented on docs/usage/configuration/config_documentation.md
> +      value: "sales,admins"
I would like to avoid changing the behaviour of existing configuration parameters, and instead introduce new parameters. I'd suggest `one_of`, `values` or `in`
```suggestion
      one_off:
        - "sales"
        - "admins"
```

2024-11-21 20:24 UTC, meise commented on docs/usage/configuration/config_documentation.md
> +      value: "sales,admins"
Code has been adjusted accordingly.

2024-11-26 15:22 UTC, sandhose requested changes

2024-11-26 15:22 UTC, sandhose commented on synapse/config/sso.py
> +        return SsoAttributeRequirement(attribute, value, one_of)
I assume this is because it was vailing if `value` or `one_of` is missing? I think this is because they should have explicitly `None` as default, e.g. `value: Optional[str] = None`

2024-11-26 15:22 UTC, sandhose commented on synapse/config/sso.py
> +           {"required": ["one_of"]},
Is that right? Does that mean that either `value` or `one_of` must be set? I thought it was possible to have neither of them set?

2024-11-27 11:01 UTC, pizkaz commented on synapse/config/sso.py
> +           {"required": ["one_of"]},
Yes, either `value` or `one_of` must be set. Before these changes, the JSON schema had `value` listed as `required` as well.
As far as I understand, `value` *can* be `None`, though. There is, however, no test case ensuring this. I you want I can implement one.

2024-11-27 11:02 UTC, sandhose commented on synapse/config/sso.py
> +           {"required": ["one_of"]},
Note; a test would indeed be helpful!

2024-11-27 11:03 UTC, pizkaz commented on synapse/config/sso.py
> +        return SsoAttributeRequirement(attribute, value, one_of)
Indeed. I will try using default values.

2024-11-27 17:08 UTC, pizkaz commented on synapse/config/sso.py
> +           {"required": ["one_of"]},
Whoa, this is confusing. The [comment](https://github.com/element-hq/synapse/blob/develop/synapse/config/sso.py#L46)

```python
    # If a value is not given, than the attribute must simply exist.
    value: Optional[str]
```

is and has been a lie since 6dade80048380166ac7543d96c4d4686401b1e37, except for CAS, which uses a different JSON schema and thus bypasses the [required rule](https://github.com/element-hq/synapse/blob/develop/synapse/config/sso.py#L52) a few lines below:

```
        "required": ["attribute", "value"],
```

I updated the comment, so people don't need to find this out the hard way, as I did. :wink:

2024-11-27 17:09 UTC, pizkaz commented on synapse/config/sso.py
> +        return SsoAttributeRequirement(attribute, value, one_of)
Works like a charm. Thanks for pointing in the right direction. :slightly_smiling_face:

2025-02-07 15:24 UTC, meise commented
What happens next? What's still missing?

2025-02-10 08:10 UTC, sandhose approved these changes
Sorry, it slipped off my review queue! Thanks for doing this!

2025-02-10 15:36 UTC, merged