Add some useful endpoints to Admin API
element-hq/synapse pull request #17948
Opened 2024-11-20 17:17 UTC by H-Shay

Adds endpoints to the Admin API to:
- fetch the number of invites the provided user has sent in the past 24 hours
- fetch the number of rooms the provided user has joined in the past 24 hours
- Get report IDs of event reports where the provided user was the sender of the reported event

2024-11-20 19:32 UTC, H-Shay commented
I don't think the complement test failures are related...

2024-11-21 01:17 UTC, MadLittleMods requested changes

2024-11-21 01:17 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +_Added in Synapse 1.120.0_
We could organize this next [`GET /_synapse/admin/v1/users/<user_id>/joined_rooms`](https://github.com/element-hq/synapse/blob/develop/docs/admin_api/user_admin_api.md#list-room-memberships-of-a-user) which seems slightly better than at the bottom of the file.

2024-11-21 01:17 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +    async def get_event_report_IDs_by_sender(
```suggestion
    async def get_event_report_ids_by_event_sender(
```

2024-11-21 01:17 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +        sender_id: str,
```suggestion
        event_sender_user_id: str,
```

2024-11-21 01:17 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                        SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?
No need for the extra indentation

```suggestion
                SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?
```

2024-11-21 01:17 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        timestamp = self._clock.time_msec() - (24 * 60 * 60 * 1000)  # 24 hours ago
```
ONE_HOUR_MS = 60 * 60 * 1000
ONE_DAY_MS = 24 * ONE_HOUR
```

```suggestion
        timestamp = self._clock.time_msec() - ONE_DAY_MS  # 24 hours ago
```

2024-11-21 01:17 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                        SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?
We don't have an index on `events.received_ts` so this will probably do a lot of row scanning (be slow and inefficient).

It looks like we also have the [same problem with `event_reports.received_ts`](https://github.com/element-hq/synapse/blob/80e39fd834baeb30b2fa21b9df5da762dfbccb73/synapse/storage/databases/main/room.py#L1656).

We should probably add an index or find an alternative way to sort/filter things. Perhaps we can use `origin_server_ts` as a good enough especially if this is for a local user. Although I'm guessing you want to investigate non-local users which may lie about `origin_server_ts` on their events.

2024-11-21 01:17 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.rm3 = self.helper.create_room_as(self.bad_user, tok=self.bad_user_tok)
Nit: Prefer the full name instead of abbreviations.

```suggestion
        self.room3 = self.helper.create_room_as(self.bad_user, tok=self.bad_user_tok)
```

2024-11-21 19:33 UTC, H-Shay commented on docs/admin_api/event_reports.md
> +GET /_synapse/admin/v1/event_reports/user/$user_id
That sounds more elegant, I have done that.

2024-11-21 23:16 UTC, H-Shay commented
Thanks for the quick review! I've re-written to expand endpoints where possible and added an index on `events.received_ts`. Sorry for the wonky wording on some of the documentation, I was trying to be specific but sounds like I was obtuse instead.

2024-11-22 00:46 UTC, MadLittleMods requested changes

2024-11-22 00:46 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +- `from_ts` - int. Optional. A timestamp in ms from the unix epoch - only rooms joined after the provided timestamp will be returned. Note: https://currentmillis.com/ is a useful tool for converting
Needs wrapping

2024-11-22 00:46 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +GET /_synapse/admin/v1/users/$user_id/invite_count
Clarify that these are invites that the user sent (as opposed to rooms that the user is invited to)

```suggestion
GET /_synapse/admin/v1/users/$user_id/sent_invite_count
```

Previous discussion: https://github.com/element-hq/synapse/pull/17948#discussion_r1851172719

2024-11-22 00:46 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +GET /_synapse/admin/v1/users/$user_id/invite_count
This suffers from the same non-obvious problem that it only looks at the past 24 hours from the URL problem (previous discussion: https://github.com/element-hq/synapse/pull/17948#discussion_r1851171791)

Configurable or updating the URL feels like the way forward.

2024-11-22 00:46 UTC, MadLittleMods commented on docs/admin_api/event_reports.md
> +* `sender_user_id`: string - Is optional and filters to only return event reports against the provided
`sender_user_id` is a bit ambiguous. Since you can interpret to be the "sender of the report" :thinking: 

My [previous suggestion](https://github.com/element-hq/synapse/pull/17948#discussion_r1851166091) was `event_sender_user_id` :shrug:

2024-11-22 00:46 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +_Added in Synapse 1.120.0_
Thoughts? This still seems relevant

2024-11-22 00:46 UTC, MadLittleMods commented on synapse/storage/schema/main/delta/88/05_events_received_ts_index.sql
> +--
Is there any problem around adding a new task to a delta that's already in a Synapse release?

In other words, is it fine to have this in `88` or should it be in `89` now that there is a release candidate that includes `88`? Not exactly sure how Synapse tracks deltas being run. Does it pick up new tasks if it has already run `88` before, etc.

It looks like there are already an `05` task there as well (two actually)? I'm guessing this is mainly an order of how things are run thing so it would be fine as `05` but seems like we should bump it to `06` at-least.

2024-11-22 00:46 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                  """
```suggestion
            sql = """
                  SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?
            """
```

2024-11-22 00:46 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +                args.extend(["%" + sender_user_id + "%"])
There is a bit of prior art here with `user_id` and `room_id` above but I'm confused why we're using `LIKE` and pattern matching.

It seems like we could just do a direct equality condition `events.sender = ?`

What am I missing?

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        from_ts = current_time - (24 * 60 * 60 * 1000)  # 24 hours ago
Can use the same `ONE_DAY_MS` trick

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        current_time = self.reactor.rightNow
I don't see `self.reactor.rightNow` used elsewhere

```suggestion
        current_time = self.hs.get_clock().time_msec()
```

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        # Get rooms using this timestamp, there should be none
```suggestion
        # Get rooms using this timestamp, there should be none
        # since the all rooms were created outside of the `from_ts` 24 hour range
```

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        # fetch rooms with the older timestamp, this should return the rooms
```suggestion
        # fetch rooms with the older timestamp before they were created, this should return the rooms
```

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        for rm in [self.room1, self.room2]:
```suggestion
        for room_id in [self.room1, self.room2]:
```

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +    def test_filter_against_user(self) -> None:
```suggestion
    def test_filter_against_event_sender(self) -> None:
```

2024-11-22 00:46 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +                returned_report_ids.append(event_report["id"])
Might as well make a `Set` from the start

```suggestion
        returned_report_ids = set()
        for event_report in event_reports:
            if event_report["sender"] == self.other_user:
                returned_report_ids.add(event_report["id"])
```

2024-11-22 00:46 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        )
Are we okay with the extra disk space and extra CPU cycles dealing with this index on insert/update?

Seems necessary to the use case so the answer is probably "this is ok" but I'm not the one dealing with the database woes on a daily basis to know for sure. There are already 7 other indexes on the `events` table.

```sh
$ psql synapse
> \d+ events
...
Indexes:
    "event_contains_url_index" btree (room_id, topological_ordering, stream_ordering) WHERE contains_url = true AND outlier = false
    "events_event_id_key" UNIQUE CONSTRAINT, btree (event_id)
    "events_jump_to_date_idx" btree (room_id, origin_server_ts) WHERE NOT outlier
    "events_order_room" btree (room_id, topological_ordering, stream_ordering)
    "events_room_stream" btree (room_id, stream_ordering)
    "events_stream_ordering" UNIQUE, btree (stream_ordering)
    "events_ts" btree (origin_server_ts, stream_ordering)
```

2024-11-22 00:50 UTC, MadLittleMods commented on changelog.d/17948.feature
> +reports where the provided user was the sender of the reported event.
> Sorry for the wonky wording on some of the documentation, I was trying to be specific but sounds like I was obtuse instead.
>
> *-- https://github.com/element-hq/synapse/pull/17948#issuecomment-2492547155*

No problem, I run into the same issue. It's also hard to balance whether "is it just a me problem?"; "is this just my understanding or the way I'm reading it? does it actually need to be updated?" so feel free to push back if you think your way is more clear.

2024-11-22 17:10 UTC, H-Shay commented on docs/admin_api/user_admin_api.md
> +- `from_ts` - int. Optional. A timestamp in ms from the unix epoch - only rooms joined after the provided timestamp will be returned. Note: https://currentmillis.com/ is a useful tool for converting
Just clarify, the issue is that the line is too long?

2024-11-22 17:11 UTC, H-Shay commented on docs/admin_api/user_admin_api.md
> +GET /_synapse/admin/v1/users/$user_id/invite_count
ah missed that, sorry! Have fixed.

2024-11-22 17:11 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +- `from_ts` - int. Optional. A timestamp in ms from the unix epoch - only rooms joined after the provided timestamp will be returned. Note: https://currentmillis.com/ is a useful tool for converting
Yes :+1:

2024-11-22 17:11 UTC, H-Shay commented on docs/admin_api/user_admin_api.md
> +GET /_synapse/admin/v1/users/$user_id/invite_count
I've added a timestamp param, more flexibility means more utility, I think.

2024-11-22 17:53 UTC, H-Shay commented on synapse/storage/databases/main/room.py
> +                args.extend(["%" + sender_user_id + "%"])
Honestly I was matching the form of the extant conditions, I don't see any reason why a direct equality condition couldn't be used (but I am also not sure why the other conditions didn't use direct equality). I'll change my addition.

2024-11-22 18:20 UTC, H-Shay commented on synapse/storage/schema/main/delta/88/05_events_received_ts_index.sql
> +--
So my (probably limited and possibly incorrect) understanding is that database schema versions are not necessarily tied to Synapse releases, but rather changes to the codebase. I didn't increase the schema version since the addition of the index shouldn't affect how the codebase interacts with the database (ie I didn't remove a column, etc) - if the codebase is rolled back, there is no problem with the index remaining. More information can be found [here](https://element-hq.github.io/synapse/latest/development/database_schema.html). You're absolutely right that the task should be incremented though, that was a function of my branch being out of date.

2024-11-22 18:25 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +        )
Honestly I am unclear on this so I've consulted the backend team for their thoughts - will update once I hear back.

2024-11-22 20:15 UTC, MadLittleMods commented on synapse/storage/schema/main/delta/88/05_events_received_ts_index.sql
> +--
I think this answers my question:

> Synapse remembers which delta files it has applied to a database (they are stored in the applied_schema_deltas table) and will not re-apply them (even if a given file is subsequently updated).
>
> https://element-hq.github.io/synapse/latest/development/database_schema.html

And your view of the schema versions seems accurate at-least to my knowledge as well.

I think the `SCHEMA_VERSION` should be `88` (it's already `88`) since we want this index applied with this change to the codebase regardless of whether the code is backwards compatible without it. This comment in the code reinforces that:

https://github.com/element-hq/synapse/blob/4587decd678300217969f1d2f69b226421a33ced/synapse/storage/schema/__init__.py#L22-L27

Totally makes sense not to bump `SCHEMA_COMPAT_VERSION` yet.

I think this discussion can be resolved :white_check_mark:

2024-11-22 20:16 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                        SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?
(an index was added for `events.received_ts`)

2024-11-25 12:33 UTC, reivilibre commented on synapse/storage/databases/main/events_worker.py
> +        )
There are two angles to the cost of adding an index.

As mentioned above, insert/update/delete performance. The most interesting one for us here is insert — we don't *really* want to make it take longer to persist new events if we don't have a good justification for doing so. But I can't *really* give you any numbers, so it's hard to comment on it from a technical perspective.

Update — I don't think we ever change the `received_ts` of an event, so not applicable.

Delete — we purge events, but not really a problem if this goes a bit slower since it's already a 'background'-ish job.

The other angle is how much space this will take on disk. Looking at `events_stream_ordering` (which is also an index on a BIGINT, so the same), this takes 247 GB on matrix.org currently. (See with `\di+` in `psql` BTW)

So adding this index will cost us another 247 GB roughly. That feels a bit on the chunky side unless it's very useful.

Do we have any alternatives? I can think of a few ideas that would help this.

---

## BRIN

A neat trick that applies in this situation is that, because the values in `received_ts` are timestamps of (roughly) when we insert the event, they will — excluding clock issues and so on — only increase.

We could therefore create a BRIN (Block-Range INdex) on this, which is a more lightweight type of index that stores, for each page of rows in the table, the minimum and maximum value of the column.

I'm not sure if this type of index might be upset by `VACUUM FULL`, or restoring a backup, especially since we might be left with gaps in the tables due to purging rooms or events. So in that sense it's a little bit risky.


---

## Using `stream_ordering` instead

`stream_ordering` also (excluding backfilled events) only increases. It's possible you could efficiently convert from `received_ts` to `stream_ordering` using a binary search or something like that, then perform your queries using `stream_ordering`.

However if the server clock isn't consistently / monotonically increasing, then you can't really use `stream_ordering` in its place and so this approach probably reaches its limit.

It'd be suitable for some rough approximation if you were poking around but probably no good for a feature built into Synapse without being able to bypass this problem.

---

## Partial index

Both of your queries only care about `m.room.member` events!

We can restrict the index to only indexing `m.room.member` events and then make sure the query planner notices that's all we care about, when you come to query.
This is mostly good because it makes the index smaller (which should also provide a minor performance boost when reading, because there will be less extraneous index rows to have to consider)

```python
        self.db_pool.updates.register_background_index_update(
            update_name="events_received_ts_index",
            index_name="received_ts_idx",
            table="events",
            columns=("received_ts",),
            where_clause = "type = 'm.room.member'"
        )
```


- ```sql
  SELECT COUNT(event_id) FROM events WHERE sender = ? AND type = 'm.room.member' AND received_ts > ? AND state_key != ?`
  ```
  This query already should make it obvious enough to the query planner that we only care about `m.room.member` events.

- ```sql
  SELECT c.room_id
  FROM current_state_events c
  JOIN events e ON c.event_id = e.event_id
  WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ?
  ```
  likely needs to be adapted to:
  ```sql
  SELECT c.room_id
  FROM current_state_events c
  JOIN events e ON c.event_id = e.event_id
  WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND e.type = 'm.room.member'
  ```

---

## Look-up table

Not saying this is my favourite suggestion right now, but you could make Synapse build and maintain a lookup table that converts the `received_ts` to earliest `stream_ordering`, e.g. on a daily basis.

Sketch:
(please note you would need something symmetrical for negative stream orderings, which I won't write here because it's just a sketch)

```sql
CREATE TABLE events_received_ts_lookup_table(received_day_ts BIGINT NOT NULL PRIMARY KEY, min_stream_ordering BIGINT NOT NULL);
```

when inserting a new event:

```python
received_day_ts = received_ts - (received_ts % 86400_000)
```

```sql
INSERT INTO events_received_ts_lookup_table (received_day_ts, min_stream_ordering)
VALUES (?, ?) -- the received_day_ts and stream_ordering of the event
ON CONFLICT (received_day_ts) DO UPDATE min_stream_ordering = LEAST(min_stream_ordering, EXCLUDED.min_stream_ordering); -- this is probably not entirely correct but you get the idea
```

When querying, you'd first query for the `min_stream_ordering` for the day (falling back to earlier days if it's not present, so `SELECT ... WHERE received_day_ts <= ? ORDER BY .. DESC LIMIT 1`) and use it as an **extra** filter in your existing query, just as a 'hint' to the query planner so it can use the `stream_ordering` index.

```sql
  SELECT c.room_id
  FROM current_state_events c
  JOIN events e ON c.event_id = e.event_id
  WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ?
  AND stream_ordering >= ? -- this `?` is the `min_stream_ordering` for the timestamp (rounded down to the day)
```

Honestly: this is probably too much effort for the circumstances. But it gives you the freedom to choose how much space to dedicate to the look-up table and is pretty space efficient by default. It does add work into the insertion path, but you could do it in a batch job in the background occasionally if needed (again, this is effort though. It's the kind of thing that could be useful in the right circumstances but I think this probably doesn't justify it yet).

---

All in all, I'd probably say the partial index is the right mix for now until proven otherwise. However I am a bit concerned that the queries may not be all that fast, even with the index, because the query still has to scan through a substantial number of rows, only to discard the ones with the wrong `sender`.

2024-11-25 13:19 UTC, erikjohnston commented on synapse/storage/databases/main/events_worker.py
> +        )
> `stream_ordering` also (excluding backfilled events) only increases. It's possible you could efficiently convert from `received_ts` to `stream_ordering` using a binary search or something like that, then perform your queries using `stream_ordering`.

It's worth noting that we already lookup the stream ordering for 24 hr ago (in store `stream_ordering_day_ago`)

2024-11-25 13:21 UTC, erikjohnston commented on synapse/storage/databases/main/events_worker.py
> +                  """
This will also fetch kicks and bans. You probably want to join against the `room_memberships` table

2024-11-25 13:28 UTC, erikjohnston commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ?
There's also `local_current_membership` for local users too.

2024-12-03 16:57 UTC, MadLittleMods commented on docs/admin_api/event_reports.md
> +  user (i.e. where the user is the reported event's sender)
Suggested wording:

```
* `user_id`: optional string - Filter by the user ID of the reporter. This is the user who reported the event and wrote the reason.
* `room_id`: optional string - Filter by room id.
* `event_sender_user_id`: optional string - Filter by the sender of the reported event. This is the user who the report was made against.
```

We could also match the `**string**, optional` formatting that is used in `docs/admin_api/user_admin_api.md` :shrug:

2024-12-03 16:57 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
>  ## List room memberships of a user
"membership" sounds more generic than what this endpoint does

```suggestion
## List joined rooms of a user
```

```suggestion
## List rooms that the user is joined to
```

```suggestion
## List joined membership of a user
```

2024-12-03 16:57 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +the user has joined after a given time, via the `from_ts` param.
We already explain this in the parameters section and I don't see this sort of extra description for other endpoints.

```suggestion
Gets a list of all `room_id` that a specific `user_id` is joined to and is a member of (participating in).
```

2024-12-03 16:57 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +
Feels weird to combine the URL path substitutions with the query parameters but it looks like this file is full of prior art on this.

I see a few spots where we do this:

https://github.com/element-hq/synapse/blob/b257c7ab199f8c800254764d2ac5d4a9708ceaa2/docs/admin_api/user_admin_api.md#L921-L929

We could probably have another section for query parameters:

```
The following parameters should be set as query parameters in the URL:
```

2024-12-03 16:57 UTC, MadLittleMods commented on synapse/rest/admin/users.py
> +    the optional `from_ts` query param.
```suggestion
    Get list of joined room ID's for a user.
```

2024-12-03 16:57 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                  SELECT COUNT(e.event_id) FROM events e JOIN room_memberships rm ON e.event_id = rm.event_id WHERE e.sender = ? AND e.received_ts > ? AND e.state_key != ? AND rm.membership = 'invite
Seems like we could remove `AND e.state_key != ?`. Am I missing something? What is this trying to protect against?

The only thing I can think of is a self-invite but I don't think that is even a thing.

2024-12-03 16:57 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        )
@H-Shay any decision on this front?

The idea to use `stream_ordering` from @reivilibre and the helper that @erikjohnston pointed out (`_find_first_stream_ordering_after_ts_txn(...)`) seems very useful to avoid the extra index and create an efficient query.

2024-12-03 17:17 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +        )
Per @reivilibre's comment "All in all, I'd probably say the partial index is the right mix for now until proven otherwise. ", I added a partial index here.

2024-12-03 17:30 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +            """
Some updates:

 - Wrap and format
 - `USING` statement since we're matching the same column
 - explicit `INNER JOIN` (no reason besides it made me question what kind of join it was initially)
 - Remove `AND e.state_key != ?` condition (see other discussion)
 - Needs a `type = 'm.room.member'` condition to use the new index

```suggestion
            sql = """
                  SELECT COUNT(e.event_id)
                  FROM events e
                  INNER JOIN room_memberships rm USING (event_id)
                  WHERE
                      e.sender = ? AND rm.membership = 'invite'
                      AND type = 'm.room.member' AND e.received_ts > ?
            """
```

This should be updated on the decision from https://github.com/element-hq/synapse/pull/17948#discussion_r1868086802 though

2024-12-03 17:30 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +            event_sender_user_id: search for the sender of the reported event. Ignored if sender_user_id is None
```suggestion
            event_sender_user_id: search for the sender of the reported event. Ignored if event_sender_user_id is None
```

2024-12-03 17:30 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +                    ON events.event_id = er.event_id
Short-hand if we want. It looks like we're just matching the query below though :+1: 

```suggestion
                LEFT JOIN events USING(event_id)
```

2024-12-03 17:30 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +                filtered_report_ids.append(event_report["id"])
We can just make this a set from the start

Previous discussion: https://github.com/element-hq/synapse/pull/17948#discussion_r1853125629

2024-12-03 17:30 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        )
Looking closer, it looks like you might have gone with the partial index approach, https://github.com/element-hq/synapse/pull/17948/commits/4af03879502c3cf0e444f8f8b1a10c498533d58e#diff-28da6922f7ab91da0023fa1d9b4ba5d8fa3d5abe924e9160e0646c852b31f6faR342

Seems workable. My only concern is it might be a bit niche and it's just *more* to add to the database.

Any reason that made you stray away from the `stream_ordering` approach?

2024-12-03 18:20 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +        )
For total completeness one might note that AFAICT finding the timestamp correlated with a stream ordering appears to rely on the function ` _find_first_stream_ordering_after_ts_txn` which searches using `event.recevied_ts` and so without adding an index is also subject to the original concern of slowness re: that column.

2024-12-03 19:10 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        )
The database query for `_find_first_stream_ordering_after_ts_txn(...)` *searches* by `stream_ordering` which has an index. From my point of view, `_find_first_stream_ordering_after_ts_txn(...)` is potentially slow because it takes multiple round-trips from database <-> application until we complete the binary search. I don't think the [comment there](https://github.com/element-hq/synapse/blob/657dd5151ea55533a1119037955952d75793b030/synapse/storage/databases/main/event_push_actions.py#L1278-L1285) is accurate on why it's slow.

Relevant query:

https://github.com/element-hq/synapse/blob/657dd5151ea55533a1119037955952d75793b030/synapse/storage/databases/main/event_push_actions.py#L1326-L1331

There is potential to improve the binary search by using some sort of `WITH RECURSIVE` query to avoid the round-trips but that's a separate thing to fix.

---

If we needed `find_first_stream_ordering_after_ts(...)` in more scenarios, there's an argument to just add the new index for `received_ts` directly for all events because it would improve all of these scenarios:

 - History retention `purge_history_for_rooms_in_range(...)`
 - `/purge_history` Admin API
 - Removing push notifications that are older than a day ago (`synapse/storage/databases/main/event_push_actions.py`)
 - The new use case in this PR for some admin API's to find invites and join membership

Currently, the use cases for `find_first_stream_ordering_after_ts(...)` seem like they apply to more one-shot and occasionally scheduled tasks which aren't being hammered by normal users. Since these tasks don't require immediate speed, we just want to make sure we're not destroying the database.

It feels like these new admin API's fall into the same camp so using `find_first_stream_ordering_after_ts(...)` seems viable.

---

> However I am a bit concerned that the queries may not be all that fast, even with the index, because the query still has to scan through a substantial number of rows, only to discard the ones with the wrong `sender`.

@reivilibre's comment about discarding a bunch of rows is still applicable but is harder to avoid unless we utilize/add more indexes for all of the conditions we're trying to filter by. Overall, it doesn't seem like we stress about this on many of the admin endpoints since they are run occasionally on demand.

2024-12-03 19:24 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +        )
Enlightening! Given this do you believe I should switch to using `find_first_stream_ordering_after_ts` rather than adding the partial index? I am learning here and while I can read about the tradeoffs I don't have an intuition as to which to choose, and the tradeoffs seem relatively equal.

2024-12-03 20:30 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        )
> Enlightening! Given this do you believe I should switch to using `find_first_stream_ordering_after_ts` rather than adding the partial index? I am learning here and while I can read about the tradeoffs I don't have an intuition as to which to choose, and the tradeoffs seem relatively equal.

@H-Shay I feel like I don't have a hard lean (or convincing/good reason) given you've already made the few changes for the partial index already.

I probably would have chosen the `stream_ordering` approach given the prior art in Synapse for it :shrug:

2024-12-03 20:39 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +* `from_ts`: int. A timestamp in ms from the unix epoch. Only
```suggestion
* `from_ts`: int, required. A timestamp in ms from the unix epoch. Only
```

2024-12-03 20:39 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                  SELECT COUNT(e.event_id) FROM events e JOIN room_memberships rm ON e.event_id = rm.event_id WHERE e.sender = ? AND e.received_ts > ? AND e.state_key != ? AND rm.membership = 'invite
It looks like this was removed in https://github.com/element-hq/synapse/pull/17948/commits/574e5c46a7e8f6324c341e3c2ed1e3e5b2226e03 but what was the conclusion?

2024-12-03 20:46 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +            event_sender_user_id is None
```suggestion
            event_sender_user_id: search for the sender of the reported event. Ignored if
                event_sender_user_id is None
```

2024-12-03 20:46 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ?
It looks like the `get_rooms_for_user_by_date(...)` query was updated but it would be good to add some context in the comments there about how we are are able to take advantage of the index on ... because of ...

2024-12-03 20:47 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +GET /_synapse/admin/v1/users/$user_id/invite_count
This has since been updated to `GET /_synapse/admin/v1/users/$user_id/sent_invite_count?from_ts=xxx`

2024-12-03 21:03 UTC, H-Shay commented on synapse/storage/databases/main/events_worker.py
> +                  SELECT COUNT(e.event_id) FROM events e JOIN room_memberships rm ON e.event_id = rm.event_id WHERE e.sender = ? AND e.received_ts > ? AND e.state_key != ? AND rm.membership = 'invite
The removed condition was relevant to an earlier iteration of the query previous to adding the join to `room_memberships` and was attempting to filter for invites by only selecting membership events where the target was not the user. This approach suffered from the fact that this does not rule out kicks or bans, as Erik pointed out, and was remedied by changing the query to join to the `room_memberships` table.

2024-12-03 21:14 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +        self.db_pool.updates.register_background_index_update(
Add some context

(comment hasn't been wrapped)

```suggestion
        # Added to accommodate some queries for the admin API in order to fetch/filter membership events by when it was received
        self.db_pool.updates.register_background_index_update(
```

2024-12-03 21:14 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +                LEFT JOIN events USING(event_id)
We might as well use the same trick for the query below so they match.

We could optionally, also do this for `room_id`

2024-12-03 21:14 UTC, MadLittleMods commented on synapse/storage/schema/main/delta/88/06_events_received_ts_index.sql
> +-- Add an index on events.received_ts to allow for efficient lookup of events by timestamp
```suggestion
-- Add an index on `events.received_ts` for `m.room.member` events to allow for efficient lookup of events by timestamp in some Admin API's
```

2024-12-03 21:14 UTC, MadLittleMods commented on synapse/storage/schema/main/delta/88/06_events_received_ts_index.sql
> +    (8805, 'events_received_ts_index', '{}');
Match the file number

```suggestion
    (8806, 'events_received_ts_index', '{}');
```

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +                returned_report_ids.add(event_report["id"])
Feels like we shouldn't be filtering the actual results as we want the actual snapshot and the server should have done the correct filtering

```suggestion
        for event_report in event_reports:
            returned_report_ids.add(event_report["id"])
```

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +        filtered_report_ids = set()
`filtered_report_ids` vs `returned_report_ids` is a bit ambiguous but it's *fine*.

Just brainstorming some ideas. Perhaps `locally_filtered_report_ids` and `server_filtered_report_ids`

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        room_creation_timestamp = self.hs.get_clock().time_msec()
```suggestion
        before_room_creation_timestamp = self.hs.get_clock().time_msec()
```

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +    def test_from_ts_param(self) -> None:
Needs test description

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_event_reports.py
> +    def test_filter_against_event_sender(self) -> None:
Needs test description

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +            self.helper.invite(self.room3, self.bad_user, user, tok=self.bad_user_tok)
Nit: I find the `invite(...)` calls really hard to read without the keyword args. Up to you.

```suggestion
            self.helper.invite(self.room3, src=self.bad_user, targ=user, tok=self.bad_user_tok)
```

2024-12-03 21:14 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.assertEqual(channel.json_body["invite_count"], 12)
Feels like this test should be split up to test the difference cases:

 - New invites show up
 - Invites before timestamp aren't considered
 - Kicks/bans aren't considered

2024-12-04 00:20 UTC, H-Shay commented
complement failure looks like a flake?

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/room.py
> +            event_sender_user_id is None
Previous conversation: https://github.com/element-hq/synapse/pull/17948#discussion_r1868340282

```suggestion
            event_sender_user_id: search for the sender of the reported event. Ignored if
                event_sender_user_id is None
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +            `events.received_ts`
Subsequent wrapped lines should be indented to separate them from other args.

```suggestion
            from_ts: a timestamp in milliseconds from the unix epoch. Filters against
                `events.received_ts`
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ?
This was added :white_check_mark:

2024-12-04 16:58 UTC, MadLittleMods commented on docs/admin_api/user_admin_api.md
> +
The wording was changed :white_check_mark:

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        invites_sent_ts = self.hs.get_clock().time_msec()
```suggestion
        before_invites_sent_ts = self.hs.get_clock().time_msec()
```

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        current_time = self.hs.get_clock().time_msec()
```suggestion
        after_invites_sent_ts = self.hs.get_clock().time_msec()
```

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        from_ts = current_time - (ONE_DAY_MS)
Why do we care to do any arithmetic on the timestamp? The timestamp by itself is good enough to stress this scenario.

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        invites_sent_ts = self.hs.get_clock().time_msec()
```suggestion
        before_invites_sent_ts = self.hs.get_clock().time_msec()
```

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.reactor.advance(ONE_DAY_MS * 2)
These clock advances don't add anything to the tests as far as I can tell.

2024-12-04 16:58 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.assertEqual(channel.json_body["invite_count"], 12)
Mega test has been split up :white_check_mark:

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/rest/admin/users.py
> +        rooms_list = {"joined_rooms": list(room_ids), "total": len(room_ids)}
```suggestion
        rooms_response = {"joined_rooms": list(room_ids), "total": len(room_ids)}
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/rest/admin/users.py
> +        res = await self.store.get_invite_count_by_user(user_id, from_ts)
```suggestion
        sent_invite_count = await self.store.get_invite_count_by_user(user_id, from_ts)
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +    async def get_invite_count_by_user(self, user_id: str, from_ts: int) -> int:
```suggestion
    async def get_sent_invite_count_by_user(self, user_id: str, from_ts: int) -> int:
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
Using `room_memberships` is probably more straight-forward. Any reason you originally picked `current_state_events`?

I think this is equivalent:
```sql
SELECT room_id
FROM room_memberships AS rm
INNER JOIN events AS e USING (event_id)
WHERE rm.user_id = ?
	AND rm.membership = 'join'
	AND e.type = 'm.room.member'
	AND e.received_ts > ?
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/events_worker.py
> +                  AND e.type = 'm.room.member' AND e.received_ts > ?
Since we only want to look at membership anyway, I think this might be better:

```sql
SELECT COUNT(rm.event_id)
FROM room_memberships AS rm
INNER JOIN events AS e USING (event_id)
WHERE rm.sender = ?
	AND rm.membership = 'invite'
	AND e.type = 'm.room.member'
	AND e.received_ts > ?
```

2024-12-04 16:58 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
We at-least need to match on `e.type` (not `c.type`) to use the new index

```suggestion
                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND e.type = 'm.room.member'
```

2024-12-04 17:01 UTC, MadLittleMods commented on changelog.d/17948.feature
> +reports against a provided user (ie where the user was the sender of the reported event).
Sorry that the review has been a bit stochastic and I wasn't able to pick up on all of these pieces in a single blast.

You might also want to try these queries on `matrix.org` to see if they run fast enough for you. Having to match on `sender` without an index might be more detrimental than we expect.

2024-12-04 18:13 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
No real reason, it was a table I was familiar with/knew about and had the information I was looking for - I was not aware of the more useful-for-this-endeavor `room_memberships` table.

2024-12-04 19:06 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
So i think switching to not using `current_state_events` would remove the benefit of the index discussed here: https://github.com/element-hq/synapse/pull/17948#discussion_r1856540739 - given that should I still switch this?

2024-12-04 19:11 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
I am slightly confused by this - the new index is on `events.received_ts` - just wondering how matching on another column takes advantage of that index?

2024-12-04 22:04 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
The index is on `events.received_ts` but only when `events.type = 'm.room.member'` (the `where_clause` makes it a partial index).

If we match on `current_state_events.type = 'm.room.member'`, the SQL engine might not be smart enough to know we can use the **`events.type = 'm.room.member'`** partial index. `current_state_events.type` vs `events.type` are their own tables with their own columns.

2024-12-04 22:14 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
The benefit you're getting is narrowing down `current_state_events` to only `m.room.member` state events. 

`room_memberships` already gives that to you out of the box.

Perhaps you do mean to use `current_state_events` as `room_memberships` will include all historical membership which can include rooms that the user joined and subsequently left or were banned.

It all depends on whether you want only get rooms the user is currently joined or all rooms the user *has* joined since the `from_ts`. The docstring currently says `Fetch a list of rooms that the user has joined since the given timestamp.`

The `/users/(?P<user_id>[^/]*)/joined_rooms` endpoint describes it as `Get list of joined room ID's for a user.` which seem to a bit different. I'm assuming you want to align things to the endpoint so `current_state_events` makes sense. The docstring for `get_rooms_for_user_by_date` should probably be updated to say something about "has joined since the `from_ts` and is still joined"

2024-12-06 18:33 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
I got some clarification on this and the intent was to get all rooms joined within the time period, including those that were subsequently left. Given this, do you think it is sufficient to make this clear in the `from_ts` parameter documentation, or does this diverge from the endpoint description sufficiently that it is necessary to create and use a different endpoint?

2024-12-06 18:34 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
Ah that makes sense, thanks for explaining.

2024-12-06 19:49 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                    WHERE c.state_key = ? AND c.membership = 'join' AND e.received_ts > ? AND c.type = 'm.room.member'
> [...] the intent was to get all rooms joined within the time period, including those that were subsequently left
>
> [...] does this diverge from the endpoint description sufficiently that it is necessary to create and use a different endpoint?

Feels like a new endpoint is in order.

Perhaps `/users/(?P<user_id>[^/]*)/membership_history` or `/historical_membership` with `?membership=join` and `?from_ts=xxx` query parameters. These are just initial thoughts so apply more thought.

2024-12-09 21:07 UTC, H-Shay commented
I suspect complement test failures are flakes...

2024-12-10 17:13 UTC, MadLittleMods requested changes

2024-12-10 17:13 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.to_kick_tok = self.login("kick_me", "pass")
It looks like the `to_kick` user is only used in one test. We should just move it there and rename it to `to_kick_user_id`

2024-12-10 17:13 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        self.reactor.advance(60)
We can turn off or adjust the rate limiting in the tests.

Per-test:

```py
    @unittest.override_config(
        {"rc_invites": {"per_user": {"per_second": 0.5, "burst_count": 3}}}
    )
```

For all of the test cases (add this above `prepare(...)`):

https://github.com/element-hq/synapse/blob/5cf74c2da0c9d94db2fe8bb91234890a14bb7b91/tests/rest/client/sliding_sync/test_sliding_sync.py#L77-L81

2024-12-10 17:13 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        after_room_creation = self.hs.get_clock().time_msec()
Why don't we need to use the `+ 1` trick here that was used in another test?

2024-12-10 17:13 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        )
We could loop here

2024-12-10 20:10 UTC, H-Shay commented on tests/rest/admin/test_user.py
> +        after_room_creation = self.hs.get_clock().time_msec()
The sql for the room join count matches on `e.received_ts > ts`, while the sql for the invite count matches on `e.received_ts >= ts`. I think technically it should be  `>` rather than `>=` since the documentation states we are searching for "after the provided timestamp", so I've changed it to reflect that.

2024-12-11 00:49 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        )
Oh, sorry. I didn't realize there were different actions in here. Loop doesn't help.

2024-12-11 01:09 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +        after_room_creation = self.hs.get_clock().time_msec()
Any prior art we should be matching? Seems like being inclusive is more intuitive but it would be best to be consistent with whatever we're doing now.

The other place we use `from_ts` query parameter is a `>=` comparison (`/statistics/users/media`):

https://github.com/element-hq/synapse/blob/5da7081197d4b65b3e3241b80726d95a2867eaff/synapse/storage/databases/main/stats.py#L721-L723

The `since` parameter for `/sync` is a `>` comparison. Same with the `pos` parameter for [Sliding Sync](https://github.com/element-hq/synapse/blob/5da7081197d4b65b3e3241b80726d95a2867eaff/synapse/handlers/sliding_sync/__init__.py#L200).

For `/messages`:

https://github.com/element-hq/synapse/blob/5da7081197d4b65b3e3241b80726d95a2867eaff/synapse/storage/databases/main/stream.py#L700-L701

---

I don't think that makes it very clear one way or the other.

2024-12-11 01:20 UTC, MadLittleMods commented on changelog.d/17948.feature
> +reports against a provided user (ie where the user was the sender of the reported event).
(please resolve discussions if they are now resolved, comment a conclusion if it was beyond a simple fix and a decision was made)

2024-12-11 01:20 UTC, MadLittleMods commented on tests/rest/admin/test_user.py
> +            shorthand=False,
First time I'm seeing this option. I don't think it's needed here since the path starts with `/_matrix`

2024-12-11 01:20 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                SELECT rm.room_id
This technically doesn't need to return the list of `room_ids` anymore for the endpoint it's used with.

Up to you.

2024-12-11 01:20 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +    async def get_rooms_for_user_by_date(self, user_id: str, from_ts: int) -> frozenset:
```suggestion
    async def get_rooms_for_user_by_date(self, user_id: str, from_ts: int) -> FrozenSet[str]:
```

2024-12-11 18:02 UTC, H-Shay commented on tests/rest/admin/test_user.py
> +        after_room_creation = self.hs.get_clock().time_msec()
:shrug: I'll change it to `>=` to match the other use of a `from_ts` param - I am also swayed by your comment that `>=` is more intuitive. I don't have a strong feeling either way.

2024-12-11 18:21 UTC, H-Shay commented on synapse/storage/databases/main/roommember.py
> +                SELECT rm.room_id
The endpoint should be returning the count - I left the function returning the list since that might be useful to someone in the future and the work is already done :shrug:

2024-12-16 18:06 UTC, MadLittleMods commented on synapse/storage/databases/main/roommember.py
> +                SELECT rm.room_id
Only consideration there is there is no limit and someone could have joined a lot of rooms and now we're moving data that we don't care about.

It's fine until we run into a problem though.

2024-12-16 18:20 UTC, MadLittleMods approved these changes
Assuming you're happy with how this works and performs. I haven't tested it out myself.

2024-12-16 19:09 UTC, H-Shay commented
Awesome thanks! When you get a chance can you hit the merge button? I haven't the powers to do so myself.

2024-12-16 19:27 UTC, merged