MSC4076: Add disable_badge_count to pusher configuration
element-hq/synapse pull request #17975
Opened 2024-11-29 15:17 UTC by manuroe

This PR implements https://github.com/matrix-org/matrix-spec-proposals/pull/4076.

The MSC is not merged yet but I have not put this new code under a experimental feature flag. The behavior change is very limited to the homerserver / client / push gateway interfaces. It can only happen if the client asks for it. 

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-12-02 08:41 UTC, manuroe commented
The MSC just got the very last change we needed. This PR can be reviewed.

2024-12-02 19:52 UTC, anoadragon453 requested changes

2024-12-02 19:52 UTC, anoadragon453 commented on changelog.d/17975.feature
> The MSC is not merged yet but I have not put this new code under a experimental feature flag. The behavior change is very limited to the homerserver / client / push gateway interfaces. It can only happen if the client asks for it.

The purpose of the experimental feature flags are primarily to prevent it from being available by default - clients can't rely on a feature existing while it's still unstable.

I understand that you need a homeserver with APNs configured to test this change. Would beta.matrix.org work for your purpose? If not, we can talk about making this feature available to only specific users through Synapse's [Experimental Features API](https://element-hq.github.io/synapse/latest/admin_api/experimental_features.html#experimental-features-api).

2024-12-02 19:52 UTC, anoadragon453 commented on synapse/push/httppusher.py
>                      # 'missed_calls': 2
Given that MSC4076 calls for eliminating this field, we may as well do it here:

```suggestion
```

2024-12-02 19:52 UTC, anoadragon453 commented on tests/push/test_http.py
> +    def test_badge_count_disabled(self) -> None:
nit: There's a lot of duplicated code between these three tests. You could use `parameterized` to generate test cases instead. For example:

```python
from parameterized import parameterized
#...

@parameterized.expand([
    # Badge count disabled
    (True, True),
    (True, False),
    # Badge count enabled
    (False, True),
    (False, False),
])
def test_msc4076_badge_count(self, disable_badge_count: bool, event_id_only: bool) -> None:
        # Register the user who gets notified
        user_id = self.register_user("user", "pass")
        access_token = self.login("user", "pass")

        # Register the user who sends the message
        other_user_id = self.register_user("otheruser", "pass")
        other_access_token = self.login("otheruser", "pass")

        # Register the pusher with disable_badge_count set to True
        user_tuple = self.get_success(
            self.hs.get_datastores().main.get_user_by_access_token(access_token)
        )
        assert user_tuple is not None
        device_id = user_tuple.device_id

        # Set the push data dict based on test input parameters
        push_data = {
            "url": "http://example.com/_matrix/push/v1/notify",
        }
        if disable_badge_count:
            push_data["org.matrix.msc4076.disable_badge_count"] = True
        if event_id_only:
            push_data["format"] = "event_id_only"

        self.get_success(
            self.hs.get_pusherpool().add_or_update_pusher(
                user_id=user_id,
                device_id=device_id,
                kind="http",
                app_id="m.http",
                app_display_name="HTTP Push Notifications",
                device_display_name="pushy push",
                pushkey="a@example.com",
                lang=None,
                data=push_data,
            )
        )

        # Create a room
        room = self.helper.create_room_as(user_id, tok=access_token)

        # The other user joins
        self.helper.join(room=room, user=other_user_id, tok=other_access_token)

        # The other user sends a message
        self.helper.send(room, body="Hi!", tok=other_access_token)

        # Advance time a bit, so the pusher will register something has happened
        self.pump()

        # One push was attempted to be sent
        self.assertEqual(len(self.push_attempts), 1)
        self.assertEqual(
            self.push_attempts[0][1], "http://example.com/_matrix/push/v1/notify"
        )

        if disable_badge_count:
            # Verify that the notification DOESN'T contain a counts field
            self.assertNotIn("counts", self.push_attempts[0][2]["notification"])
        else:
            # Ensure that the notification DOES contain a counts field
            self.assertIn("counts", self.push_attempts[0][2]["notification"])
            self.assertEqual(
                self.push_attempts[0][2]["notification"]["counts"]["unread"], 1
            )
```

This also has the benefit of testing one more case :slightly_smiling_face:

2024-12-03 08:20 UTC, manuroe commented on tests/push/test_http.py
> +    def test_badge_count_disabled(self) -> None:
thanks @anoadragon453 for the review. I did not know `parameterized`. I am going to play with it and push a commit.

2024-12-03 14:24 UTC, manuroe commented on changelog.d/17975.feature
beta.matrix.org will be good for us to test it on iOS.

Do I still need to make the changes under an experimental feature flag?

2024-12-03 15:12 UTC, anoadragon453 commented on changelog.d/17975.feature
@manuroe yes please. Otherwise it will become default-enabled on matrix.org, and clients may start to rely on it.

You need only to add another option to [`synapse/config/experimental.py`](https://github.com/element-hq/synapse/blob/develop/synapse/config/experimental.py) and gate the feature on it being enabled.

2024-12-03 17:00 UTC, manuroe commented on changelog.d/17975.feature
I used `msc4076_enabled`. The PR is ready for another review.

2024-12-03 22:58 UTC, anoadragon453 approved these changes
Thanks for your patience on this one. This now LGTM!

2024-12-03 22:58 UTC, merged

2024-12-04 07:27 UTC, manuroe commented
Thanks @anoadragon453 for the help!