Add recaptcha_{private,public}_key_path config option
element-hq/synapse pull request #17984
Opened 2024-12-02 15:35 UTC by V02460

Adds the config options `recaptcha_private_key_path` and `recaptcha_public_key_path`. Tests and docs are included.

A public key is of course no secret, but it is closely related to the private key, so it’s still useful to have a `*_path` variant for it.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-12-16 23:36 UTC, MadLittleMods requested changes

2024-12-16 23:36 UTC, MadLittleMods commented on synapse/config/captcha.py
> +`recaptcha_private_key_path`. These are mutually incompatible.
We can dumb this down a bit:

```suggestion
You have configured both `recaptcha_private_key` and
`recaptcha_private_key_path`. Only one or the other can be specified at a time.
```

2024-12-16 23:38 UTC, MadLittleMods commented on synapse/config/captcha.py
> +`recaptcha_private_key_path`. These are mutually incompatible.
This is a slight variation on the typical error message we've been using for this:

```
Conflicting options 'macaroon_secret_key' and 'macaroon_secret_key_path' are
both defined in config file.
```

I like the version that this PR has but we should probably be consistent and update all the other similar errors.

2025-01-09 14:30 UTC, V02460 commented
@MadLittleMods: Could you clarify what you want the error message to be?

For these PRs I did not use my own wording, but took it from `registration_shared_secret`: https://github.com/element-hq/synapse/blob/aab3672037ee9ea71c54c89c86d9c0cc35ae184f/synapse/config/registration.py#L37-L40

2025-03-23 05:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/synapse?pullRequest=17984) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/synapse?pullRequest=17984) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/synapse?pullRequest=17984) it.</sub>

2025-07-14 16:10 UTC, MadLittleMods commented on synapse/config/captcha.py
> +`recaptcha_private_key_path`. These are mutually incompatible.
> For these PRs I did not use my own wording, but took it from `registration_shared_secret`: https://github.com/element-hq/synapse/blob/aab3672037ee9ea71c54c89c86d9c0cc35ae184f/synapse/config/registration.py#L37-L40

Fair enough :fast_forward: 

It looks like we aren't consistent with this either. Another version:

https://github.com/element-hq/synapse/blob/51296684498012217d6104deb5509f15dad93864/synapse/config/key.py#L94-L97

2025-07-14 16:37 UTC, MadLittleMods approved these changes

2025-07-14 16:37 UTC, merged

2025-07-14 16:39 UTC, MadLittleMods commented
Thanks for continuing down this path @V02460 :slightly_smiling_face: