Add MSC3861 config options admin_token_path and client_secret_path
element-hq/synapse pull request #18004
Opened 2024-12-06 12:36 UTC by V02460

Adds two config options `admin_token_path` and `client_secret_path` to the experimental config under `experimental_features.msc3861`. Also includes tests.

I tried to be a good citizen here by following `attrs` conventions and not rewriting the corresponding non-path variants in the class, but instead adding methods to retrieve the value.

It is noteworthy that in this patch each access to the client secret or the admin token will re-read it from file. In the current state a ConfigError will be raised at runtime when the file can not be read anymore. You might prefer another form of error handling than the current behavior.

A big pro of directly using the secret contents from file is that it enables secret rotation without having to restart Synapse.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2025-01-31 17:35 UTC, MadLittleMods requested changes

2025-01-31 17:35 UTC, MadLittleMods commented on synapse/config/experimental.py
> +        return self._client_secret
> It is noteworthy that in this patch each access to the client secret or the admin token will re-read it from file. In the current state a `ConfigError` will be raised at runtime when the file can not be read anymore.

Is there a different idiomatic pattern with `attrs` where we can just read from the file once?

It looks like we just access `config.client_secret()` once in `__init__()` in the usage but I don't think we should make downstream consumers think about having to cache this value because of the expensive/slow file read each time.

2025-01-31 20:45 UTC, V02460 commented on synapse/config/experimental.py
> +        return self._client_secret
The context in which I made this design decision is the following: I’ve started thinking about secret rotation in Synapse and would like to have it supported eventually. For that to work, the consumers of secrets *have* to know about updates to the secret in use (and sometimes previous secrets as well).

I find the small scope of this change (together with the unwieldiness of `attrs`[^1]) a good place to get a first taste of how updating secrets might work.

Regarding your concern about performance: I’d expect such a small file to be cached by the OS and very quick to be accessed. If that would not be the case, memory mapping or the use of inotify would be a more full-fledged solution. But does this MR actually cause any performance regression?

[^1]: I don’t blame you, `attrs`, it’s simply not the task you were made for.

2025-01-31 21:30 UTC, MadLittleMods commented on synapse/config/experimental.py
> +        return self._client_secret
> I’ve started thinking about secret rotation in Synapse and would like to have it supported eventually

This feels like a pre-optimization and something that needs discussion on whether we even want to support it and strategies for how best to tackle.

> Regarding your concern about performance:

I don't think it's a performance problem in its current form. I just don't think that downstream consumers using `config.client_secret()` should have to think about it. It should just always be an in-memory thing after startup.

For example, if we wanted to support secret rotation, we could have a watcher on the file that would only update when the file changes (not read the file each time). But this is just another example of a strategy that should be discussed in a separate, dedicated secret rotation discussion. And why I don't think we should attempt to figure it out with this PR.

---

In any case, I think we should figure out how best to read the file once on startup.

2025-02-03 16:14 UTC, V02460 commented on synapse/config/experimental.py
> +        return self._client_secret
The updated patch set now only reads in the files once at startup.

To allow consumers access to the raw values close to what is written in the config, the attributes `_{client_secret,admin_token}{,_path}` are part of the dataclass – with leading underscore to underline their lower-level nature. The methods `client_secret` and `admin_token` on the other hand provide convenient access for a consumer to the secret, independently of where it initially came from.

You are right, I think those maybe-future plans should not impede the best solution to the problem at hand. It was not my intention to overload the PR with a discussion about secret rotation. In the meantime I had some helpful and structuring conversations about it at FOSDEM, and I will write up an issue to discuss it further.

2025-02-03 16:41 UTC, MadLittleMods commented on synapse/api/auth/msc3861_delegated.py
> +        self._admin_token: Callable[[], Optional[str]] = self._config.admin_token
Ahh, it's meant to be a callable :fast_forward:

2025-02-03 16:42 UTC, MadLittleMods approved these changes

2025-02-04 09:15 UTC, V02460 commented on changelog.d/18004.feature
I don’t think experimental features are currently documented there – I could not find `admin_token` nor `client_secret` either.

2025-02-04 18:45 UTC, MadLittleMods commented on changelog.d/18004.feature
Good call :+1:

2025-02-04 18:45 UTC, MadLittleMods approved these changes

2025-02-04 18:45 UTC, merged

2025-02-04 18:46 UTC, MadLittleMods commented
Thanks for the contribution @V02460 🐫

Sorry for the review noise at the end :bow: