Define delayed event ratelimit category
element-hq/synapse pull request #18019
Opened 2024-12-09 20:18 UTC by AndrewFerr

Apply ratelimiting on delayed event management separately from messages.

MSC4140

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-12-10 09:14 UTC, hughns reviewed
Please see question inline about the default value.

2024-12-10 09:14 UTC, hughns commented on docs/usage/configuration/config_documentation.md
> +It defaults to: `per_second: 10`, `burst_count: 100`.
Why are the defaults so different from `rc_message` which is what is currently used? I expect the default for `rc_delayed_event` to be similar.

2024-12-10 13:40 UTC, AndrewFerr commented on docs/usage/configuration/config_documentation.md
> +It defaults to: `per_second: 10`, `burst_count: 100`.
The default is more lax to permit refreshing delayed events often / in a loop without risk of ratelimiting, whereas "actual" messages are sent less frequently / not periodically and benefit from a stricter ratelimit.

2024-12-19 17:02 UTC, anoadragon453 requested changes

2024-12-19 17:02 UTC, anoadragon453 commented on tests/rest/client/test_delayed_events.py
> +        for i in range(2):
```suggestion
        for _ in range(2):
```

2025-02-06 10:20 UTC, fkwp commented
@AndrewFerr what is the current status on this topic?

2025-02-06 17:29 UTC, AndrewFerr commented
> @AndrewFerr what is the current status on this topic?

I still need to address the review comments, but once that's done, this should be good to go (barring further review).  It should also be usable for testing/development until then.

Since this ratelimit targets the simpler management commands of cancel/restart/get, it's less complicated than [the ratelimits we want for delayed messages themselves](https://github.com/element-hq/synapse/pull/18018), which does require more thought.

2025-02-07 20:14 UTC, AndrewFerr commented on synapse/config/ratelimiting.py
> +            defaults={"per_second": 10, "burst_count": 100},
Fair enough.  For call connection management, the js-sdk defaults to sending a refresh once every 8 seconds, so the high ratelimit was just to be sure that it would never get in the way.

I like the idea of a per-device limit rather than a high allowed rate.  That permits a usecase of many devices of the same user connected to the same call, as they'd each need to send their own call refreshes & would get blocked if the ratelimit were per-user.

2025-02-07 20:29 UTC, AndrewFerr commented on docs/usage/configuration/config_documentation.md
> +It defaults to: `per_second: 10`, `burst_count: 100`.
b2b1e228fd

2025-02-07 20:29 UTC, AndrewFerr commented on synapse/config/ratelimiting.py
> +            defaults={"per_second": 10, "burst_count": 100},
5b2ae48804

2025-02-07 20:29 UTC, AndrewFerr commented on tests/rest/client/test_delayed_events.py
> +        for i in range(2):
b1dd548401

2025-02-10 06:51 UTC, anoadragon453 commented on synapse/config/ratelimiting.py
> +            defaults={"per_second": 10, "burst_count": 100},
Hrm, I'm against doing it on a per-device basis. If we do so, a user can register 100 devices and then suddenly send 100 events/s.

What's the use case for a single user being in the same call >3 times?

2025-02-10 06:56 UTC, anoadragon453 commented on synapse/config/ratelimiting.py
> +            defaults={"per_second": 10, "burst_count": 100},
Ah sorry, this is for event management, not for sending events.

In that case this is probably fine - it's not as heavy as actually sending events.

2025-02-10 06:59 UTC, anoadragon453 approved these changes
This LGTM!

Complement test failures are a flake. Note that `TestDelayedEvents/delayed_state_events_are_kept_on_server_restart` has been flakey for a while; could you please fix that in another PR @AndrewFerr :)

2025-02-10 06:59 UTC, anoadragon453 commented on demo/start.sh
> +			  burst_count: 1000
Note that this should also be added to Sytest's config in a PR on that repo. See this example: https://github.com/matrix-org/sytest/pull/1394

2025-02-10 06:59 UTC, anoadragon453 commented on synapse/handlers/delayed_events.py
> +        # TODO: Instead apply rateliming based on the scheduled send time.
```suggestion
        # TODO: Instead apply ratelimiting based on the scheduled send time.
```

2025-02-10 13:37 UTC, AndrewFerr commented on synapse/config/ratelimiting.py
> +            defaults={"per_second": 10, "burst_count": 100},
I've renamed the config key to be more clear that it's just for management and not the events themselves.

2025-02-10 13:53 UTC, AndrewFerr commented on demo/start.sh
> +			  burst_count: 1000
https://github.com/matrix-org/sytest/pull/1395

2025-02-20 13:20 UTC, AndrewFerr commented
This should be ready to merge now.  The only change since the review is b014c078cb.

2025-02-25 17:22 UTC, merged