Properly purge state groups tables when purging a room
element-hq/synapse pull request #18024
Opened 2024-12-10 15:58 UTC by MatMaul

Currently purging a complex room can lead to a lot of orphaned rows left behind in the state groups tables.
It seems it is because we are loosing track of state groups sometimes.

This change uses the `room_id` indexed column of `state_groups` table to decide what to delete instead of doing an indirection through the event ids.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2024-12-18 11:58 UTC, erikjohnston requested changes

2024-12-18 11:58 UTC, erikjohnston commented on synapse/storage/databases/main/purge_events.py
> +        )
Unfortunately these tables don't exist in the main DB, which is why the functions were in the state store. I think you just need to move the function from this file to that?

2024-12-20 13:50 UTC, erikjohnston approved these changes
Thanks!

2024-12-20 13:50 UTC, erikjohnston commented on synapse/storage/databases/state/store.py
>              keyvalues={},
```suggestion
            keyvalues={"room_id": room_id},
```

2024-12-20 13:50 UTC, erikjohnston commented on synapse/storage/databases/state/store.py
>          self.db_pool.simple_delete_many_txn(
```suggestion
        self.db_pool.simple_delete_txn(
```

2024-12-20 13:50 UTC, erikjohnston requested changes
Ah, bah I can't edit the PR. Can you commit the simplifications to the delete?

2025-01-06 13:10 UTC, erikjohnston approved these changes
Woo, thanks!

2025-01-06 13:12 UTC, erikjohnston commented
@MatMaul sorry, looks like the tests didn't trigger, could you push an empty commit or something?

2025-01-06 13:13 UTC, erikjohnston commented
Ooooh, there are conflicts, sorry!

2025-01-06 14:14 UTC, MatMaul commented
Argh sorry, self inflicted wound (the other conflicting PR is mine :sweat_smile: ).

2025-01-06 15:32 UTC, merged

2025-01-07 20:10 UTC, olmari commented
Ooh, does this mean the https://github.com/erikjohnston/synapse-find-unreferenced-state-groups is getting less in the future?