Add the ability to filter by state event type on admin room state endpoint
element-hq/synapse pull request #18035
Opened 2024-12-16 21:48 UTC by H-Shay

Adds a query param `type` to `/_synapse/admin/v1/rooms/{room_id}/state` that filters the state event query by state event type.

2024-12-23 12:52 UTC, anoadragon453 requested changes

2024-12-23 12:52 UTC, anoadragon453 commented on synapse/rest/admin/rooms.py
> +                )
Why this arbitrary limitation? What if someone has a custom state event type they want to query for?

2024-12-23 12:52 UTC, anoadragon453 commented on docs/admin_api/rooms.md
> +    of this type will be returned.
```suggestion
* `type` - The type of room state event to filter by, eg "m.room.create". If provided, only state events
    of this type will be returned (regardless of their `state_key` value).
```

2024-12-23 12:52 UTC, anoadragon453 commented on changelog.d/18035.feature
> +Adds a query param `type` to `/_synapse/admin/v1/rooms/{room_id}/state` that filters the state event
```suggestion
Add a query param `type` to the [Room State Admin API](https://element-hq.github.io/synapse/develop/admin_api/rooms.html#room-state-api) that filters the state event
```

2024-12-23 12:52 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +
Could you add tests for:

* Passing the query parameter but with an empty value (`""`)
    -> Expect that no state events are returned.
* Passing a type for an event that's not in the room.
    -> Expect that no state events are returned.

2024-12-23 12:52 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +        self.assertEqual(400, channel.code)
```suggestion
        self.assertEqual(400, channel.code)
        self.assertEqual(channel.json_body["errcode"], "M_BAD_REQUEST")
```

It's a good idea to check for `errcode` values when validating error conditions.

2025-01-03 15:04 UTC, anoadragon453 approved these changes
LGTM, thanks!

2025-01-03 17:18 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +            f"/_synapse/admin/v1/rooms/{room_id}/state?type=''",
Turns out if you do `?type=`, then you indeed end up with `type = ""`.

Of course, then we end up ignoring `type` altogether due do the `if type`, which is falsy for an empty string.

https://github.com/H-Shay/hq_synapse/blob/25c0726c330ee65b04779c25d69ea3f13fa4a17a/synapse/rest/admin/rooms.py#L468-L474

So all state is returned.

I think this behaviour makes sense (ignore if empty string) rather than having no results returned. You can't have an empty type for an event, so this is an invalid parameter value.

If you agree, could you update the test to say that `5` results should have been returned, such that it passes?

2025-01-03 18:56 UTC, H-Shay commented on tests/rest/admin/test_room.py
> +            f"/_synapse/admin/v1/rooms/{room_id}/state?type=''",
Makes sense to me! I've made the change - if you're happy with it can you merge it when you get a chance?

2025-01-07 22:31 UTC, H-Shay commented on tests/rest/admin/test_room.py
> +            f"/_synapse/admin/v1/rooms/{room_id}/state?type=''",
@anoadragon453 gentle nudge on this so it doesn't get forgotten :)

2025-01-08 15:35 UTC, anoadragon453 commented on tests/rest/admin/test_room.py
> +            f"/_synapse/admin/v1/rooms/{room_id}/state?type=''",
Thanks for the nudge! Somehow I had missed the notification for the last comment :facepalm:

2025-01-08 15:37 UTC, anoadragon453 approved these changes
This LGTM, thanks!

2025-01-08 15:37 UTC, anoadragon453 commented on changelog.d/18035.feature
> +that filters the state event.
Sadly due to my notifications this didn't end up in the RC, so the changelogs won't combine. I've changed it to a new one below.

```suggestion
Add a unit test for the `type` parameter of the [Room State Admin API](https://element-hq.github.io/synapse/develop/admin_api/rooms.html#room-state-api).
```

2025-01-08 15:38 UTC, merged