Speedup the building of Docker images
element-hq/synapse pull request #18038
Opened 2024-12-18 09:32 UTC by sandhose

This uses a few tricks to speed up the building of docker images:

 - This switches to use `uv pip install` instead of `pip install`. This saves a bunch of time, especially when cross-compiling
 - I then looked at what packages were not using binary wheels: I upgraded MarkupSafe to have binaries for py3.12, and got back to Python 3.12 because hiredis didn't have builds for py3.13 with the version we were using
 - The generation of the requirements.txt is arch-agnostic, so I've switched this one to run on the build architecture, so that both arch can share it
 - The download of runtime depdendencies can be done on the build architecture through manual `apt-get download` plus `dpkg --extract`
 - We were using -slim images, but still installed a bunch of -dev dependencies. Turns out, all the dev dependencies were already installed in the non-slim image, which saves a bunch of time as well

2024-12-19 12:31 UTC, anoadragon453 requested changes
A few very minor things, but otherwise this LGTM. This included a few tricks I wasn't aware of myself. Thanks for taking the time to go through and do this!

Needs a `git revert d113209` before merge, of course.

2024-12-19 12:31 UTC, anoadragon453 commented on docker/Dockerfile
> +ENV UV_LINK_MODE=copy
Could you leave a comment explaining why this is useful?

2024-12-19 12:31 UTC, anoadragon453 commented on docker/Dockerfile
> +      openssl:${arch} || exit 10; \
Why `exit 10`? Is the exit code returned by `apt-get download` in case of failure not appropriate?

2024-12-19 12:31 UTC, anoadragon453 commented on docker/Dockerfile
> +      echo "Process: ${package_name}"; \
```suggestion
      echo "Extracting: ${package_name}"; \
```

2025-01-27 17:48 UTC, AndrewFerr commented on docker/Dockerfile
> +ENV UV_LINK_MODE=copy
From https://github.com/astral-sh/uv/blob/main/docs/guides/integration/docker.md#caching:

> Changing the default [UV_LINK_MODE](https://github.com/astral-sh/uv/blob/main/docs/reference/settings.md#link-mode) silences warnings about not being able to use hard links since the cache and sync target are on separate file systems.

2025-01-27 17:48 UTC, AndrewFerr commented on docker/Dockerfile
> +RUN --mount=type=cache,target=/root/.cache/uv \
Should `UV_LINK_MODE=copy` be set here as well?

2025-02-18 15:56 UTC, sandhose commented on docker/Dockerfile
> +      openssl:${arch} || exit 10; \
Probably coming from a copy-paste somewhere :D
Removed it

2025-02-18 15:56 UTC, sandhose commented on docker/Dockerfile
> +ENV UV_LINK_MODE=copy
Added a comment

2025-02-18 15:57 UTC, sandhose commented on docker/Dockerfile
> +ARG POETRY_VERSION
Not sure what you mean?

2025-02-18 16:16 UTC, AndrewFerr commented on docker/Dockerfile
> +ARG POETRY_VERSION
I mean to replace line 52 with this one, which will limit the scope of this build arg to stage 0 (which is the only stage that needs it).

2025-02-18 16:22 UTC, sandhose commented on docker/Dockerfile
> +ARG POETRY_VERSION
Oh right, it's just that I like version definitions to be at the top of the Dockerfile, makes it easier to upgrade everything

2025-02-18 16:32 UTC, AndrewFerr commented on docker/Dockerfile
> +ARG POETRY_VERSION
Okay, feel free to leave it as it is then :slightly_smiling_face:

2025-02-18 18:59 UTC, anoadragon453 approved these changes
LGTM after temp commit revert. Thanks!

2025-02-19 10:55 UTC, merged